### ISSUE TITLE
Unstop Jam after end of Period

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#10]
Unstop jam once the Period Clock has expired doesn't return clocks to their previous states

**Comment by JeneralPain** [comment]
Can you provide the steps to reproduce?

**Comment by bullseye555** [comment]
Wow, this is an old one... Lol.

From recollection, after the period clock had reached 0 with the jam clock still >0, if the SBO incorrectly Stopped the jam, this started the Intermission clock. 
Undo Stop Jam did not then return the clocks to the before Stop Jam states (eg, period 0, jam >0<2:00, intermission at x). This was at the end of first period - I don't recall checking to see if this also occurred after the second period and the game was at unofficial final.

I can't confirm the specific version any longer, but it was 3.9.0 or 3.9.1.

**Comment by frank-weinberg** [comment]
I've recently checked and my changes that went into 3.9.2 do not fix this. I intend to look into fixing it but canot promise a timeline.

**Comment by brian-brazil** [comment]
I believe this was fixed.
