### ISSUE TITLE
Remove the "legacy" PT screen

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#101]
the actual differences from the "Penalty Tracking" sheet are basically nil at this point (the main difference is the Penalty Tracking Sheet supports colors), so the only purpose the legacy Penalty Tracker screen seems to serve is an opportunity to introduce bugs.

I would like to remove the legacy Penalty Tracking sheet, and make the ptcolor version the "default".  Does any one see a reason to keeping the legacy screen around?

**Comment by brian-brazil** [comment]
I'd like us to reduce the number of screens generally for a maintainability standpoint, this seems like a good place to start.

**Comment by frank-weinberg** [comment]
I would look into factoring common functionality into a library. This way we can have multiple similar screens without duplicating a lot of code. (This should also be done for overlays.)

ETA: That being said, the PT vs. Legacy PT screens are different implementations of the same screen and keeping both seems rather pointless.

**Comment by brian-brazil** [comment]
All 4 of the PT/IWB screens are basically identical internally (the tcd one is subtly different for no apparent reason), CSS may be enough to differentiate them.

**Comment by brian-brazil** [comment]
In relation to overlays, do we really need 15 of them? We seem to have built up a repository of overlays used at tournaments years ago, and continuing to add more that need to maintained eternally (while lacking historical context to understand why each of the current 15 exists) is possibly not the best of plans.

I think we might better serve the community by providing a clear API (e.g. WS docs) plus some libraries to deal with the WS and then encouraging ad-hoc overlays and screens to be developed 3rd party and linked off the wiki. We can then trim down what we have to a core set (e.g. we only need one IWB).

**Comment by AdamSmasherDerby** [comment]
I'd like to dissent in part and concur in part here.  The PT/IWB section could definitely use some cleanup, yes.  On the other hand, the PT screen and IWB screens serve different functions.  One is for readability for users like the box and benches, and the other is for data entry.  One of each should be retained.

There's definitely some redundant overlays in there as well.

However, as a matter of philosophy, most of our users are not technically savvy enough to implement various views themselves.  I don't see the harm in having a library of available views for teams to chose from.  We could perhaps better organize them, put them in a sub screen from the main screen, etc., but I think it's a real value-add to have more possibilities available straight out of the box.

**Comment by brian-brazil** [comment]
> I don't see the harm in having a library of available views for teams to chose from.

I'm not saying that they shouldn't be developed, I'm saying that it might not be the best idea to have them in this repository to be maintained by this team. For example something like the proposal to allow a configurable number of penalties before foul out like requires non-trivial changes to each of the 4 penalties pages we already have, which is already pushing it IMHO. It's difficult to push forward with new features if we're held back by tens of screens that aren't all 100% necessary. So one IWB and one PT sounds fine to me. Two IWBs is less clear.

**Comment by AdamSmasherDerby** [comment]
Perhaps a good metric would be that we only need one screen per internal function, but can have multiple options for things that are part of the audience experience, so that teams can choose how to do their presentation.

By that approach, we'd get rid of the legacy PT screen (which I completely agree is redundant) and move the TCDG WB display into the "Audience views" category.  (And rename it something sensical, like "Audience Whiteboard View.")

There's also no reason that we can't deprecate old screens as they break or are replaced.  As far as I know, the only thing that breaks on the PT screens if you foul out at 4 is the color coding, which doesn't strike me as a deal breaker. That is also something that could eventually be updated if that becomes a settable parameter.

**Comment by brian-brazil** [comment]
> (And rename it something sensical, like "Audience Whiteboard View.")

I'm honestly not sure how that'd develop. Screens should not be named after particular tournaments/events IMHO.

> which doesn't strike me as a deal breaker.

That gets us in a weird situation where some screens work and some don't, which will cause at the least confusion. In my opinion a screen is either in and supported, or it's moved elsewhere/deleted.

**Comment by AdamSmasherDerby** [comment]
> > (And rename it something sensical, like "Audience Whiteboard View.")

> I'm honestly not sure how that'd develop. Screens should not be named after particular tournaments/events IMHO.

I think we're saying the same thing.  I agree that screens should have general names.  I also think that the screen currently named TCRD WB has value.  So I think we should keep it, but rename it something general.

In terms of the "foul out on fewer penalties" thing - if we set the limit to 4, that just means that things don't change color before the skater leaves the game.  I just don't see that we have to define that as a bug - that could just be normal behavior.

**Comment by brian-brazil** [comment]
If we have a feature that allows the 7 to be changed by the user to 4, then any place that's still using the 7 is a bug. Software should behave consistently, and without gotchas.

**Comment by AdamSmasherDerby** [comment]
That depends on if you think "yellow" should mean "5 total penalties" or "foulout - 2."  If it's the former, then nothing breaks. :)
