### ISSUE TITLE
Replace GetOpt library

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#102]
the GetOpt library is licensed under GPLv2, and thus (to my understanding) prevents actually dual-licensing the scoreboard under Apache/GPLv2.

The only place we use GetOpt is to pass arguments in Main.java. [commons-cli ](https://commons.apache.org/proper/commons-cli/)  would be a good replacement.

**Comment by brian-brazil** [comment]
The arg parsing is simple enough that we could do it by hand.
