### ISSUE TITLE
Add screens that display LT and SK sheets

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#104]
When running paper and electronic games data in parallel, having these screens will allow for easy cross checking either during or after the game (before exporting to statsbook).
Ideally, the data displayed can also be edited.

**Comment by brian-brazil** [comment]
Did you mean PT rather than SK? We currently lack the information to do SK sheets.

This work is dependant on my cleanup of the `game` directory, which will make the LT data available in the standard ways.

**Comment by frank-weinberg** [comment]
I meant SK (we have a PT screen already that fits this bill well enough for practical purposes) and am aware that this will require tracking more data and the finishing of other WIP. Just wanted it put on record as something to do down the road (and maybe have in mind when designing data structures).
