### ISSUE TITLE
(Request) Lineup clock to reset to 0 when entering any type of Time Out

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#11]

**Comment by JeneralPain** [comment]
We did speak about this, the line up clock shouldn't be restarting at the end of a TIME OUT (of any kind), you simply add the 30 seconds to the "time out".

**Comment by JeneralPain** [comment]
This seems to be a big thing in Europe but isn't anywhere else including the US.

Currently the officiating guidelines DO NOT stipulate the LINE UP clock starts at the conclusion of a TTO, OR, or OTO, it simply goes straight into the JAM.

**Comment by brian-brazil** [comment]
This request is about the start of a timeout, not the end of one so it's something different.

@bullseye555 Can you explain why you want this?

**Comment by bullseye555** [comment]
As per what @JeneralPain mentioned, to handle similar to some European leagues so you could end the time out and re-enter lineup at 0 without having to triple assign a keyboard shortcut to stop TO, reset and start Lineup

Further discussion external to this forum doesn't warrant this in Australia, but as CRG is used internationally having Lineup reset to 0 at when Jam or TO clocks start would allow for those leagues that DO do it that way to do it easier(ish).

**Comment by brian-brazil** [comment]
A feature was very recently added to enable this usage, so this issue can be closed.

**Comment by bullseye555** [comment]
Agreed
