### ISSUE TITLE
Make Foul-Out Penalty Count a Ruleset item

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#111]
(breaking this out from bullseye555's comment in #66 as it's a bit more of an undertaking than the other style tweaks)

>Can I add one to this - an option in Ruleset (or policies or config, whichever path it goes down) to be able to set # penalties in a game. Then when you're running a 20 min half game with reduced number of penalties, the PT and IWB screens will have their colour highlights based on that (eg: set 5 penalties instead of 7, and it will yellow at 3, orange at 4 and red at 5 etc)(can also open another ticket, if deemed too far from the original to be included in it) 

I think this is a good use of a Ruleset item, and we'll need to update the warning thresholds to be keyed off of this value as well, instead of just based on 7.  I don't think we should allow more than 9 penalties for display reasons, however (Do Rules have a concept of maximum possible value, outside of how Clock objects work?)

**Comment by AdamSmasherDerby** [comment]
I think the case of 10 penalties is so inhumanly rare that we don't need to explicitly allow for it.  The StatsBook doesn't even have the option to enter a 10th penalty manually.

**Comment by official-sounding** [comment]
I'm thinking more of a case where someone might want to increase the foul-out limit to be more than 7, for instance in some sort of 90 minute/10 penalty foul-out type game.

That is probably even more niche than the fewer penalties situation, but I bring it up mostly to say that there likely needs to be a validation limit on setting a foul out limit higher than 9 to indicate that the UI won't support it.
