### ISSUE TITLE
Clock sync is broken

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#113]
At current master clock sync is not working, with the period/jam/lineup clocks not advancing on the same second.

~~In addition there was other clock weirdness. In one case at EuroDerbyCon the period clock expired, then the jam clock, then rather than going to intermission the lineup clock started. We also had two cases where it seems the lineup clock either was running during a jam, or something else that caused it to be over a minute just at the end of the jam. The other two issues were intermission related. I'm suspecting that this is related to the clock sync not working, and wondering if the scoreboard is even usable without clock sync.~~ Edit, this is a different bug. See #118

**Comment by bullseye555** [comment]
I thought it was just me... I had my CRG (3.9.3) go into lineup instead of
intermission twice in the weekend...

**Comment by brian-brazil** [comment]
Are you sure that was 3.9.3, and not one of the various dev releases that have been made in the past few months?

**Comment by brian-brazil** [comment]
I've done some testing, and confirmed that #93 is where this was introduced.

**Comment by bullseye555** [comment]
https://drive.google.com/open?id=1zp5-7iBv-CDiGxgQC4ULAUIyrP9B5BMn

Links to a zip of the setup used (this is pre-use). Jeneral Pain has the PC
this was installed on, so could potentially provide the post-use data from
it.

**Comment by brian-brazil** [comment]
Okay, that is indeed a 3.9.3 jar so the clock weirdness is an unrelated issue.

**Comment by brian-brazil** [comment]
This turns out to be a simple typo.
