### ISSUE TITLE
Can't change team Alternate name from Team/Time screen

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#116]
If you click on a team name you get two text boxes with the team name, and the `operator` alternate name. You can change the team name here, but when you click on the 2nd textbox both textboxes are then hidden. This textbox should either work (preferred), or be removed.

![screenshot_2018-07-24_16-04-06](https://user-images.githubusercontent.com/7115638/43147589-4e76b25e-8f5b-11e8-8c77-ecd92ee0908c.png)

**Comment by JeneralPain** [comment]
This is aged, can someone please investigate the correction here?
