### ISSUE TITLE
Clock weirdness in at least 3.9.3

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#118]
In one case at EuroDerbyCon the period clock expired, then the jam clock, then rather than going to intermission the lineup clock started. We also had two cases where it seems the lineup clock either was running during a jam, or something else that caused it to be over a minute just at the end of the jam. The other two issues were intermission related. I'm suspecting that this is related to the clock sync not working, and wondering if the scoreboard is even usable without clock sync. In #113 this was also reported in 3.9.3, so is likely not related to more recent changes.

**Comment by brian-brazil** [comment]
When looking through the code last week I noticed that event handling is basically completely async, so there's (almost) no guarantees as to what order listeners will see different events. I suspect that may be the cause of this, however it's fairly gnarly and fixing it is likely to introduce deadlocks. What we probably want to do is limit the async to the places that could back up, such as sending the WS and Twitter updates and have everything else sync.

**Comment by brian-brazil** [comment]
In addition, a single threaded event system is probably not the worst idea from an understandability standpoint.

**Comment by frank-weinberg** [comment]
I have Unit tests for all the clock stuff mostly finished. And strting tomorrow work should no longer be super busy, so I hope to finish them within the week. Hopefully that will at least help narrowing down, where these weirdnesses are coming from.

**Comment by frank-weinberg** [comment]
And I can confirm that events are not always received in the order in which they are generated. Caused me some effort when writing the unit tests.

**Comment by brian-brazil** [comment]
Yeah, the event handling needs a rewrite (it also leaks memory, yay). I'd want to hold off until we've a good bit more unittests before doing that though, as the potential for collateral damage is very high.

**Comment by frank-weinberg** [comment]
We also have a significant chunk of clock handling code in event handlers as a heritage from having it in policies. We should probably look to move away from that as much as possible. (But this is also better done after unit tests are there.)

**Comment by brian-brazil** [comment]
I think it's okay if we can make it synchronous, but locking will be fun then. Let's cross that bridge when we come to it, and try to fix one thing at a time.

**Comment by brian-brazil** [comment]
This is all fixed now.
