### ISSUE TITLE
Interactive Overlay state not persisted across restarts

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#12]
Hi,

I've noticed that the overlay state (http://localhost:8000/views/overlays/interactive/admin.html) isn't being auto-saved with the other state such as score. This means that if the operator needs to restart the scoreboard, we'll lose the overlays on our video streams as the operator has no knowledge of the video setup.

Please persist this state as part of the auto-save.

**Comment by jaredquinn** [comment]
@mmitton as the Interactive Overlay uses the Custom.* Name space in the websocket only; how/where in core should I persist data.   The data @brian-brazil is requesting is the state of clock displays.
