### ISSUE TITLE
Highlight penalties until beginning of next jam

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#143]
Feedback from the Kalamazoo Continental Cup (I was CHNSO and used CRG for PT). Feature request 
to highlight "new" penalties until the beginning of the next jam.

Desired behavior:
1) PT on tablet enters new penalty
2) penalty view shows new penalty as green background
3) green backgrounds stays green
4) it goes to white when the scoreboard starts the next jam

**Comment by brian-brazil** [comment]
This was already handled in #112, we went with underlining penalties in the current jam.
