### ISSUE TITLE
Text-based penalty whiteboard mobile view

### ISSUE THREAD

**Issue by riffreff** [rollerderby/scoreboard#15]
The PWB view is not optimised for mobile devices. Please add this (or similar) to the CSS, so that if coaches access the PWB on their phones they see the teams vertically instead of next to each other:

@media only screen and (max-width: 1023px) {
	.Team.Team1, .Team.Team2 {
	position: relative;
	width:100%;
	display:block;
	margin:0;
	padding-bottom:2em;
}
}

**Comment by brian-brazil** [comment]
@riffreff Did you changes handle this?

**Comment by riffreff** [comment]
Yes. This is solved ans implemented
