### ISSUE TITLE
Feature Requests -- RDCL

### ISSUE THREAD

**Issue by akeyes** [rollerderby/scoreboard#170]
Adjustments to make the scoreboard fully compatible with [RDCL](http://therdcl.com/) games.

[RDCL rules](http://therdcl.com/wp-content/uploads/2017/12/RDCL-Rules.pdf)

- Allow for intermissions of different lengths. A full RDCL game is played with 4 quarters, with a minimum of 5 minutes between quarters 1&2, and quarters 3&4. (rule 2.4.2) Between quarters 2&3, a minimum of 15 minutes is required. (rule 2.2.2)
- Add an option to prevent the period (quarter) clock from expiring between jams. The rules require that if there is time on the period (quarter) clock after a jam ends, another one will be played. (rule 2.4.5) The most likely option would be to pause it at 0:01 if it reaches that during lineups.

Everything else (as far as I am aware) is easily done with the existing CRG scoreboard. I have not looked into the penalty tracker aspect of the scoreboard in relationship to RDCL. That would open up the option of adding additional support for rule 7.5, penalty jams beyond just using "Timeout before period end". (tl;dr: Penalties are served during the jam after they are earned, and for the full length of the jam. In the event that, during the last jam of the game, the team in the lead earns one or more penalties, an additional jam is played. This repeats until the winning team skates a clean jam.)

**Comment by frank-weinberg** [comment]
Well timed request - I'm going over the ruleset right now anyways, so rules for the two bullets will likely be included in my next PR.

Penalty jams could probably simply be run as overtime jams. (The socrebord doesn't require a tied score in order to run an overtime jam.)
