### ISSUE TITLE
Official Reviews not shown in SB Display

### ISSUE THREAD

**Issue by AlpenYeti** [rollerderby/scoreboard#173]
On Official Reviews, the dot does not appear to be impacted. It does not blink while the OR is being stated, and does not go off if OR has been lost.

**Comment by brian-brazil** [comment]
Thanks for reporting, which screen is this exactly?

**Comment by AlpenYeti** [comment]
I report the OR on the Operator Control Pannel, where the counter updates correctly, but the dot does not reflect the state of the OR on the "Main Scoreboard" display pannel.

**Comment by AdamSmasherDerby** [comment]
In addition, it appears that background colors are not being set for the OR dots from the "scoreboard_dots" color.

**Comment by AdamSmasherDerby** [comment]
I don't have time to fix this weekend (tournment this weekend) but it looks like the color problem is the same as referenced in pull #121 - the divs for the official review include pseudoclasses, (:before and :after) which can't have the colors set directly the way normal classes are.

**Comment by JeneralPain** [comment]
I can confirm in the 3.9.5 test build I have done, this issue is now resolved. When we close #183 completely then this issue will be closed.

**Comment by JeneralPain** [comment]
This has now been fixed thanks to #183 

When the next release comes out, you'll find this bug goes away. :)
