### ISSUE TITLE
Conditional tweets are not triggered by a clock that is counting down

### ISSUE THREAD

**Issue by riffreff** [rollerderby/scoreboard#18]
It works when the respective clock is counting up. It does not work with the triggering clock counting down. 

Example: Tweet that Jam has started, five seconds into the Jam. Neither %cjts=115, nor %cjtms=1:55 trigger a tweet when the Jam clock is counting down. It works however, if the Jam clock is counting up.

The same goes for the pre-set tweets every five minutes of the period. They do not work unless the period clock is counting up.

**Comment by official-sounding** [comment]
I don't think this is strictly a bug, more a limitation on how the conditional tweet system works.  The conditional only really knows point-in-time state (eg, the jam clock reads "0:05") it can't really tell what way the clock is ticking.

In a perfect world, you could specify a condition like %cjes to represent "jam time elapsed" or %cjrs as "jam time remaining", but that would be a pretty major complication to an already very complicated seeming part of the code.  It's a reasonable candidate for unit tests, which I would think would be seriously required before we mess around with this part in anger.

To set up this rule with the jam time counting up, you should be able to set the rule as %cjts=5 or %cjms=0:05 to have it trigger correctly.

**Comment by brian-brazil** [comment]
#90 got us part of the way there.

**Comment by frank-weinberg** [comment]
The timeElapsed/timeRemaining functions added in #93 should also be useful here

**Comment by JeneralPain** [comment]
Is this still a problem?

**Comment by brian-brazil** [comment]
There's still something not right here, I believe it's due to the different rounding the FormatSpecifier is doing as against the Clock code.
