### ISSUE TITLE
Enforce 'NO CACHE' across build

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#184]
We have run into a few bugs at NZ Top 10 using Version: v3.9.5-21-g960192f-20181010005549

One of these included that there was a difference between displays. IE: The SBO had said "Time out before period end", but everything suggested the game had ended, yet the SB display showed exactly what they'd asked for.

We found that when NO CACHE was enforced in the browser using Dev tools in Chrome and turning it off in FF52 (on Rasperry Pi), that the issues with this completely cleared.

Can we please get NO CACHE enforced in the HTML code?

**Comment by frank-weinberg** [comment]
Your version is from right before #181 was merged, which seems to do what you request. Can you please retest with a build that includes this PR?

**Comment by JeneralPain** [comment]
Yep will try it.

**Comment by brian-brazil** [comment]
This is done.
