### ISSUE TITLE
Sudden FULL FREEZE in v3.9.5-21-g960192f-20181010005549

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#185]
When using v3.9.5-21-g960192f-20181010005549 it will suddenly FREEZE without warning. All clocks will lock (on all displays pulling data) and the SBO will be unable to make ANY changes to the scoreboard.

The java output has no errors displayed.

The only fix is to restart the java instance.

(will get the java ver shortly)

**Comment by frank-weinberg** [comment]
This needs more info. When does it freeze? On user input? On a clock running down? Any other event?

**Comment by JeneralPain** [comment]
The scoreboard operator was literally sitting idle during "Line Up" period with PERIOD running, LINE UP running and waiting to hit "start jam". The clocks then fully froze, and no input would change anything on any display.

There was nothing untoward in the java screen either.

**Comment by JeneralPain** [comment]
Confirmed this happens with a newer build that I did today as below.
Java version is SAME across both builds.

BUG with Complete java instance lock.
CRG Version: v3.9.5-25-g915a377-20181014061343
Java: Version 8 Update 144 (build 1.8.0_144-b01)

(I built that at 0830am NZDT +12)

Steps to occurrence...
1. Jam ended with STOP BUTTON (ie: called off).
2. Official review with OTO to Team OR
3. OR completed, STOP BUTTON to Line Up
4. Line up clock froze at 17sec
5. No further inputs accepted.
6. SBO had to restart CRG instance manually by closing CRG window and restarting 'scoreboard-windows.exe'
7. Clocks restored and normal functionality restored.

Can confirm:
All remote heads displaying the scoreboard all showed "LINE UP 17" until SBO restored CRG instance and functionality came back.

**Comment by JeneralPain** [comment]
Java applet log:

Both freezes showed nothing untoward in the log...

> Loaded auto-saved scoreboard XML from .\config\autosave\scoreboard-0-now.xml
> Starting auto-save
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Clock to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Score to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.ShowJammers to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Clock to On
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Score to On
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to Upcoming
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.ShowJammers to On
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Error sending JSON update: java.io.IOException: closedOut 1000:Idle for 300098ms > 300000ms
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to Upcoming
> 
> 
> 
> Loaded auto-saved scoreboard XML from .\config\autosave\scoreboard-0-now.xml
> Starting auto-save
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to RosterTeam1
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to RosterTeam2
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to Upcoming
> Setting ScoreBoard.FrontendSettings.Overlay.Interactive.Panel to null

**Comment by brian-brazil** [comment]
> Error sending JSON update: java.io.IOException: closedOut 1000:Idle for 300098ms > 300000ms

Well the good news is that the fix I added for the issue at British Champs is all working.

**Comment by JeneralPain** [comment]
Well, it appears it was the java build. Since upgrading the java build the issue has cleared.
