### ISSUE TITLE
Clocks not synced if manually started/stopped

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#191]
Maimed reported at the European Cup that the clocks got out of sync. Current theory is that this was operator error, as it corrected itself at the next jam. Thus it seems that manually starting/stopping clocks may get things out of sync. Not the end of the world (or something operators should have to do), but probably worth looking into.

**Comment by JeneralPain** [comment]
Is there code we can implement that triggers sync logic if manual operations are used?

**Comment by frank-weinberg** [comment]
I observed an instance of this in the first jam of Dock City - Tiger Bay after first the Jam Clock and then the Period Clock were adjusted Mid-Jam. I don't know why this happens but as adjusting the Period Clock during a Jam is forbidden in regulation play, I consider this not super high priority. (Plus AFAIK the version used at playoffs predates the last changes to the clock code.)

> Is there code we can implement that triggers sync logic if manual operations are used?

Manual start and automatic start use the same function. So this can not be a factor.

**Comment by JeneralPain** [comment]
Is this still a problem @brian-brazil or @frank-weinberg ?
