### ISSUE TITLE
[Feature Request] Change to how teams names are inputted for a more intuitive UI/UX.

### ISSUE THREAD

**Issue by Judge-Tread** [rollerderby/scoreboard#194]
When you add a team in the "Teams" tab, it's not clear that you need to populate the dialogue box before clicking add team. (Button is greyed out, but it's not clear that that is what the box is for.

I suggest removing the dialogue box, and merely having a button labeled "add team", which brings up a pop up box that prompts you to add the name of the team (clarifying that this is what will be displayed on the scoreboard). 

It would be awesome, if within that pop up box, you have the options to input what you want displayed on the scoreboard/operator controls etc to simplify the UI/UX of customising team displays.

It may be just how my brain works, but given how most of Carolina is WYSIWYG when it comes to buttons, this one isn't!

Disclaimer: I know nothing about the programming involved in CRG, merely many games of operation/set up/swearing at CRG! #

**Comment by JeneralPain** [comment]
Hey Judge,

Agree on this one, will add it to the list of "Good to have" things.

Just need to look at the priority of things, it shouldn't be a huge change to the codebase to make it happen. 

Thanks

JP
