### ISSUE TITLE
penalty tracker: pressing jam-1 et jam+1 increment et decrement 2

### ISSUE THREAD

**Issue by AlpaGont** [rollerderby/scoreboard#2]
When pressing -1 and +1 button while encoding a penalty for a player, th action resulting is doing a +2/-2 on jams

**Comment by jaredquinn** [comment]
Can you please provide details of the version of CRG, operating system and browser you are running.

**Comment by jaredquinn** [comment]
Found the issue and have corrected it in the current dev release.  It will be included in the next beta zip.

The ptcolor.html was loading index.js along with ptcolor.js which was double up the click event handlers.
