### ISSUE TITLE
Twitter - Call Back URL Security Protocol

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#214]
The updated Twitter security protocol means that the Twitter system requires "the call back URL" to be entered in the app.twitter site along with its secret/security API.

Need to track down the developer who wrote the initial plugin and get the security details for that app.twitter account to update the API callback.

**Comment by JeneralPain** [comment]
Have messaged @xrobau and Jon Obst to see if I can get the Twitter details for the API/Security Key/etc.

**Comment by JeneralPain** [comment]
URL to fix this problem is: https://developer.twitter.com/en/apps

Then we need to verify the API Code etc is up to date.

**Comment by AdamSmasherDerby** [comment]
I'm working backwards - it was already set up when Michael Mitton was developer, so I'm going to try to get in touch with Mr. T.

**Comment by xrobau** [comment]
I'll fix this today. I kept forgetting about it. I would be doing it now, but in my absence my chair has been repurposed, so I need to buy another one.

There is some complexity with the url callback, so I may need to put something on the rollerder.by domain that acts as an API.

Apologies for my lazyness 8)

**Comment by JeneralPain** [comment]
Okay, the scoreboard account now has the following Call Back URL's enabled

http://localhost:8000
http://192.168.1.2:8000
http://10.10.10.2:8000
http://172.16.20.2:8000

Just need to update the Twitter API within the CRG platform and merge the request

**Comment by JeneralPain** [comment]
Just need someone to test as I can't see any specific API or Auth codes being sent from CRG JAVA/CSS etc through to Twitter. I'm of the belief it compares the oauth callbackurl to the database and now they're in there, it should "just work", however needs testing.

**Comment by JeneralPain** [comment]
Failed... 

Error: Twitter Exception : 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following). Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings

**Comment by JeneralPain** [comment]
Refer to Commit #9813073

**Comment by JeneralPain** [comment]
After speaking to Dixie-Wrecked we've figured it out, it's all about how we pass the data over to Twitter...

http://10.90.1.220:8000/controls/twitter_auth.html
^^ this one is just JP's test bed.
http://172.16.20.2:8000/controls/twitter_auth.html
http://127.0.0.1/controls/twitter_auth.html
http://192.168.1.2:8000/controls/twitter_auth.html
http://localhost:8000/controls/twitter_auth.html
http://127.0.0.1:8000/controls/twitter_auth.html
http://10.10.10.2:8000/controls/twitter_auth.html

**Comment by JeneralPain** [comment]
Tested and working!
