### ISSUE TITLE
Official Review Retained Colors incorrect if dot color specified

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#23]
When the scoreboard dots are set to red, the "retained review" cross becomes black on red, not red with a transparent background.

I see *why* this is happening;
1. The normal OR dot is actually an empty css element with rounded corners inside a div. The dot has a background color set to black, and the div has no background color.
2. When an OR is retained in this case, the dot element is replaced with two other containers, a vertical stripe and a horizontal one. Each of those containers has a color of black, and they overlap to make a cross. The new "dot retained" element has a background of "none" so it shows the background color.
3. However, when a color is set for the scoreboard dots, rather than being assigned to the elements inside the div, it is rather assigned to the div *itself*. That means that when the cross is generated, it's still black, and the transparent background shows the color of the div through on the corners.

What needs to happen is that when a color is assigned for the scoreboard dots, it gets assigned to the crossbars, and to the Dot element, but NOT to the background of the div itself.

**Comment by The--Captain** [comment]
Fixed.
