### ISSUE TITLE
Allow user to set order of jams in score view

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#236]
In the current dev version, the operator screen shows the jams with the most recent at the top of the list.  There is certainly a logic for this order, but I suspect there will be strong demand for the option to set it in the opposite order. I would suggest adding this as a configurable option if it isn't already and I just haven't found it.

**Comment by frank-weinberg** [comment]
The score display on the operator screen is intended primarily for when the operator needs to adjust prior scoring trips and secondarily for the SKs to do a quick cross check between jams. Both will be in the vast majority of cases for recent jams, so having those at the top where they can be seen without scrolling makes sense.

What use case do you see for having them the other way round that wouldn't be served at least as well by a designated score sheet screen (which is on my to do list)?

**Comment by AdamSmasherDerby** [comment]
In most cases, the SK won't have separate computers - resource limitations being what they are, you're going to have SKs with clipboards looking over the SBO's shoulders at the screen in almost all cases.  It will be much easier to verify paperwork correctness if the screen is oriented in the same order as the  paperwork.

Ideally, you'd have a separate scrollable frame at the bottom that pushes earlier jams out of frame so that the latest jams are always visible.

I'm not saying we should get rid of the option to do it the other way, but I would strongly suggest the ability to display it to match the paperwork should be easily accessible.

**Comment by frank-weinberg** [comment]
It shouldn't be a frame (as in the HTML entity), as that has the significant downside that the edit popup will be limited to that frame. But I can see it working if we have a scrollable section for the score sheets - if the parameters are right.

But I don't know what the best parameters are - obviously the height must be such that the bottom is always visible. But should we always use all the available height? Or limit it to a certain amount of rows? Make it adjustable? And doing either requires HTML/JS/CSS functions I'm not currently familiar with.

So I'm ok with adding such an option but I won't be doing it myself in the near future.

**Comment by AdamSmasherDerby** [comment]
Yeah, I didn't mean frame in that sense, sorry for the confusion.  Frontend is something I can work on, but is there going to be a section for configurable UI parameters somewhere?  Where's the best place to put the option to change it?

**Comment by frank-weinberg** [comment]
Since it's affecting the operator screen only, the best place is probaly with the controls at the top of that screen. (If that gets too full at some point, we will have to figure out a better alternative, but so far we have always been able to just drop some older options when we got to that point.)

**Comment by brian-brazil** [comment]
From using these screens in practice, the ordering isn't a problem when double-checking stuff as I'd always do it at each jam.

**Comment by charlie-chaperon** [comment]
> Since it's affecting the operator screen only, the best place is probaly with the controls at the top of that screen.

I think the Scoreboard Settings Screen would be the most natural place for changing the order. 
That way, the operator screen is kept clean. Users who want to have another view probably don't need to change the setting multiple times or in-game.

**Comment by frank-weinberg** [comment]
Closing this given that the original request is phrased as "I expect people to want this" and in the four years since nobody has actually asked for this (as far as I am aware) .

If there is actual desire for this feature, feel free to reopen.
