### ISSUE TITLE
Add program version number to state

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#239]
In order to make things easier on API users in the future, it will be helpful if there's a clear way to determine which version of the scoreboard was used both from the output file and during the game.  This might actually warrant a top-level variable "ScoreBoard.Version:", but if not, it could probably get thrown in with "ruleset".

**Comment by brian-brazil** [comment]
We should probably dump all the state we have in that file out.

**Comment by AdamSmasherDerby** [comment]
> We should probably dump all the state we have in that file out.

I'm not quite sure what you're suggesting here. "Dumping" in the sense of writing to disk or "Dumping" in the sense of "getting rid of?" :)

**Comment by brian-brazil** [comment]
Dumping in the sense of writing it out.
