### ISSUE TITLE
Add local timezone to state

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#240]
Since all absolute times are given as UNIX timestamps, there's no way to determine the local time of game start.  Not a high priority feature, but presumably an easy add. (And a required field on the IGRF.) (Apologies if this is already present and I'm not finding it.)

**Comment by brian-brazil** [comment]
> presumably an easy add

In general this isn't possible. We could find out the timezone that the machine is running in, but this isn't the same thing as the local timezone. E.g. I've used my laptop which has Irish time in various European locations which are an hour off. If anyone is using a more server type approach they should be using UTC.

**Comment by AdamSmasherDerby** [comment]
Just because the computer's clock time _can_ be wrong, doesn't mean we shouldn't record it. (The score could be wrong too, but we record that.)

Two things:

1. I would guess approximately 95% or more of our use case is this software on a laptop belonging to a league or a league member that never travels more than 50 miles from the venue.

2. Given that we require the system time to be correct for the "Start Game at Time X" function to work, I suspect the local time is correct on the vast majority of those systems.

If you think it makes more sense to just record the value on the system clock at game start than the local timezone, I can get behind that.  I could see users being much more likely to just change the clock than their timezone if they move their computer across the line. But "Local clock at start" is valuable enough to risk it sometimes being wrong.
