### ISSUE TITLE
Feature Request:  Warmup Times indicated on Scoreboard

### ISSUE THREAD

**Issue by EricAgostinelli** [rollerderby/scoreboard#243]
a while ago at Clover Cup, Adam Smasher and I were discussing the idea of having Warmup Countdown Clock for teams to be displayed on the scoreboard in addition to the "Time To Derby" clock.  This would allow the teams to be able to see how much time is remaining for their warmups before the other team gets their opportunity.   This certainly could be a non-required option, but would be very helpful and efficient for tournaments.

**Comment by JeneralPain** [comment]
Thinking about this, I don’t know of any tournament that this would be useful for honestly. This is generally self managed by the crews in the “time to derby”.

However, I will put it on the wish list as a low priority change as there are bigger more important things than telling a team how much warm up time they have.

**Comment by frank-weinberg** [comment]
With the new game data handling for CRG 5 allowing to set up warmup times ahead of the game is easy.
Having an extra clock in the backend is also easy. Figuring out how to start it at the correct time is less obvious but should be doable.

What I don't have a good idea for is how to best do the UI. The "Time To Derby" takes up most of the space, so just placing the warmup time next to it will probably make it too small. Doing a two clock layout as during the jam would either mean that the "Time To Derby" clock switches place between warmups or that the visual relation from the warmup clock to the team is lost. If anybody has a good idea how to do this, I'm open to implementing it.

**Comment by JeneralPain** [comment]
Just reading your comments Frank, you're right, where can you put this without chewing up real estate.

Would changing the "clock order" make a difference?
- Team Warm Up [Team 1]
- Team Warm Up [Team 2]
- Time to Derby
- Period 1
- Half Time
- Period 2
- Game Finished clock?


Though I look at the tournament round I played in last weekend and we just literally split the track in half, and only shared during the "laps" phase I guess. So I don't know how much value it would contribute.

**Comment by frank-weinberg** [comment]
I don't think displaying warm up time instead of time to derby is a good idea. Warm up time is only of interest to the team(s), everybody else in the venue (audience, announcers, officials) will want to know time to derby.

**Comment by JeneralPain** [comment]
Yeah I spoke to a few people on my side of the ball we call Earth, they don't see any value.

As this is 3+ years old with no feedback from the original poster @EricAgostinelli , closing with this comment.
