### ISSUE TITLE
MAC version unable to open

### ISSUE THREAD

**Issue by ashleyjamesbrown** [rollerderby/scoreboard#26]
Current System

MAC OS 10.12.5
JAVA 8 update 161 (build 1.8.0_161-b12) 

When dbl click the app attempts to open and then auto closes. Likely to be a legacy Java issue on Mac ?

Can anyone confirm similar or a fix workaround. Ive just become involved with local derby team and need to score this weekend.

**Comment by riffreff** [comment]
Drop this script file in the root of the folder, unzip it
[startscoreboard-mac.zip](https://github.com/rollerderby/scoreboard/files/1702508/startscoreboard-mac.zip)  and run it. It should start CRG on a Mac (this issue came with Sierra)

**Comment by ashleyjamesbrown** [comment]
Thanks.

Following error occurs. 

> Saving session...
...copying shared history...
...saving history...Error: Unable to access jarfile lib/crg-scoreboard.jar
truncating history files...
...completed.
Deleting expired sessions...10 completed.

The file isnt in the libs folder ive just crg-scoreboard.mf

**Comment by riffreff** [comment]
Please follow the link and use the zip file there for the working scoreboard, not the code in development here on github!

https://drive.google.com/drive/folders/0B5MEhWEBhGKVSTlTZW1mcFdobnM

**Comment by ashleyjamesbrown** [comment]
Absolutely brilliant. Works fine with the google code and the script you asked me to unzip. :-) Thanks a lot that will keep the NSO scoring team happy to use the code they have always used.

**Comment by rogerharkavy** [comment]
Just checking, do we have this documented properly in the wiki?

https://github.com/rollerderby/scoreboard/wiki/Installing-the-Scoreboard-Software

**Comment by JeneralPain** [comment]
Did you get this working Ashleyjamesbrown?

**Comment by ashleyjamesbrown** [comment]
Yes apologies - its working thanks to the script and the version from google code.

**Comment by rogerharkavy** [comment]
@ashleyjamesbrown Just verifying, the wiki instructions for this are accurate and complete, correct link and everything?

**Comment by davesgonechina** [comment]
Encountering this same problem, and in response to @rogerharkavy question, I do not see in the documentation how to build or otherwise download the crg-scoreboard.jar for Mac installations.

**Comment by davesgonechina** [comment]
The missing bits seem to be:

1) Install Apache Ant: brew install ant
2) Build with Ant: ant -f build.xml
3) Run scoreboard-Mac.app

**Comment by brian-brazil** [comment]
I'd suggest we look at switching to scoreboard-Linux.sh for Macs.

**Comment by GorramRob** [comment]
Is it the 3.9.5-53 or 3.9.6 version you're trying to use? I did the same thing (though on windows/linux) trying to use those were errant releases. If you're not, try using 3.9.5.

And is it possible to delete those two errant releases from the releases list since they seem to be causing confusion?

**Comment by davesgonechina** [comment]
@GorramRob  v3.9.5-53-53, ~a git clone of the dev branch IIRC.~ downloaded this release: https://github.com/rollerderby/scoreboard/releases/tag/v3.9.5

**Comment by davebdb** [comment]
> The missing bits seem to be:
> 
> 1. Install Apache Ant: brew install ant
> 2. Build with Ant: ant -f build.xml
> 3. Run scoreboard-Mac.app

Same for Linux.  Need to be in the directory where build.xml is at.  Thanks!
