### ISSUE TITLE
Feature request: "read only" version of Penalty Tracker page.

### ISSUE THREAD

**Issue by rogerharkavy** [rollerderby/scoreboard#29]
This would be useful for bench coaches to point their smartphones or tablets at, allowing them to see the penalties without being able to modify them.

**Comment by yetzt** [comment]
well, if they can access the "readonly" version, nothing would keep them from accessing the fullversion as well. this would at least demand access control to the scoreboard web interface.

**Comment by rogerharkavy** [comment]
I'm comfortable enough with a read-only page and relying on the honor system that the viewers will not go to the read-and-write page.

**Comment by riffreff** [comment]
This already exists. See Graphical Penalty Whiteboard and
Text-based Penalty Whiteboard under scoreboard/html/views/wb/
They need some css work to make them responsive, I mentioned this before but haven't gotten around to make this a pull request:
https://github.com/rollerderby/scoreboard/issues/15

**Comment by rogerharkavy** [comment]
I didn't know this was implemented, however I am guessing this hasn't made it into a new build.

In the latest released version in the Google Drive folder (3.9.0, dated March 29, 2017), these are the only options on the start page:

Main Operator Control Panel
Main Scoreboard
(Minimal Animations)
BETA Websocket/JSON Scoreboard
(Minimal Animations)
Ruleset Editor
Mobile Device Operator Controls
Media Management
Overlays
Load/Save Scoreboard "Stream" (beta quality!)
Twitter update controls (beta quality!)
Team Lineup Control Panel (beta quality!)
Scoreboard Assistant
Penalty Tracker

The \crg_3.9.0-current\crg-scoreboard_3.9.0-20160408192330\html\ folder does not have a views subfolder.

Looking in the GitHub folder, I see this was implemented 10 months ago with "3.9.1" in the comments. Was 3.9.1 actually built and released?

**Comment by riffreff** [comment]
I might be using the crg_current.zip built from the same day, which contains these files (and links)

**Comment by JeneralPain** [comment]
I'm running 3.9.0 and have it working? Yes this is the "Editable" version but if you see my comment below where if you run a headless computer (ie: Raspberry Pi) as a display only, then they can't edit it and I dont think anyone will go out of their way to connect a mouse. 

http://mothership.jenn.id.au:9001/controls/pt/

**Comment by rogerharkavy** [comment]
I was looking for a non-editable version of the board, so the 3.9.0 one will not be suitable.

I'm going to try the 3.9.1 and 3.9.2 dev versions, it seems like they will have what I am looking for.

**Comment by jaredquinn** [comment]
@rogerharkavy   our current versioning is basically point releases (3.9, 4.0) are stables, and any minor points are incremental/bugfixes without major feature changes.   3.9 was a major version because we implemented a bunch of new features including penalty tracking.  3.9.1 was the first set of fixes ontop of 3.9.0.

Jon Foxx was working on various penalty board displays.

**Comment by The--Captain** [comment]
Is this still an issue, considering the whiteboard view in 3.9.1?

**Comment by rogerharkavy** [comment]
I will test it out in 3.9.3 this week.

**Comment by rogerharkavy** [comment]
Whiteboard display works and looks very good, thanks for implementing this.
