### ISSUE TITLE
REQUEST: Team Import / Export

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#30]
Was discussing with rob at Epic Scrim about the usefulness of IMPORT EXPORT.

When I'm setting up the 3 servers for URDP (which all pull the single xml repository), it saves me having to enter 26 teams into the system when I can create one big spreadsheet and hit "IMPORT" instead of having to type in up to 260 skaters into the system.

**Comment by official-sounding** [comment]
There are a couple of external tools that handle this currently (to my knowledge):

* The Big O uses [This Google Sheets & C#-based solution](https://drive.google.com/drive/folders/0B5yMffsmyMJBaVI0RmdZQl9fUzg) to generate their team XML.  upsides are it's very battle tested, downsides are that you need to have a workbook-per-team.
* I wrote a [small utility](https://github.com/official-sounding/statparse) that parses an IGRF and emits CRG XML.  It is very rough around the edges however, and the igrf workflow is not ideal for tournaments.

converting a roster in a format similar to the WFTDA Mothership roster export is probably the biggest hole out there.  I had actually planned to work on that this week (likely as an external utility, but written in an easy-to-integrate-into-crg way), and will update when I have something to show for it.

**Comment by JeneralPain** [comment]
The tournament I run we aren't WFTDA mandated or anything like that, just simply a tournament that uses the ruleset.

**Comment by jaredquinn** [comment]
Long term plan for Teams is to move all the team management functionality out to a seperate app and do Import/Export using an API.   This could even ultimately (and optionally) connect to WFTDA's charter database using this API to pull in complete rosters. 
 
Team management doesn't need to be part of core; and I would be reluctant to make changes to the current structure in there.

**Comment by brian-brazil** [comment]
Copying&pasting in rosters is now supported.
