### ISSUE TITLE
REQUEST: Overtime Jam Trigger

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#31]
So I had an overtime jam, what would be fantastic is if the scores are tied and the Period is 2 and the period clock is 0 (or 30min) depending on how the backend sees it, that it automatically suggests "DO YOU WANT AN OT JAM?" or the OT jam highlights/flashes in some way.

Like how the "END OF PERIOD CONTROLS" glows when we go into unofficial final.

**Comment by frank-weinberg** [comment]
I don't think a popup would be a good idea. Usually there are points signalled after the end of a Jam and a popup would have to be closed to enter them. (And if points are entered one by one and the popup springs up after, say, 3 of 4 are entered, that would even give the impression of a tie, when there is none.)

Making the button glow is probably a minor fix. But it will also be of limited use as the button is hidden in the "End of period controls" submenu.
