### ISSUE TITLE
SK/LT line colours don't match paperwork

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#325]
Both show two lines the same when there's a star pass - which doesn't follow paperwork.

Also SK is counting lines from the top rather than the bottom, so the top line is always white rather than the bottom line of a period always being white.

**Comment by frank-weinberg** [comment]
I consider the grouping a feature as it makes it obvious which Jam a SP line belongs to.

**Comment by brian-brazil** [comment]
If you're checking what colour line is next with the SKs, it's a problem
though. We can distinguish that in another way.
