### ISSUE TITLE
Ruleset Editor Blank Values on Initial Ruleset creation

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#340]
When first entering the ruleset editor, if you create a new ruleset that has another existing ruleset as it's parent, all of the editors are active, and their values are blank (as if you had created a new ruleset without a parent).

Additionally, once an existing ruleset has been opened, the ruleset editor exhibits the correct behavior upon creating a ruleset (all values populated, all editor check boxes are not checked).

**Comment by brian-brazil** [comment]
Confirmed.
