### ISSUE TITLE
NI unable to be selected once deselected

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#356]
Build https://github.com/rollerderby/scoreboard/files/3456083/crg-scoreboard_v3.9.5-227-g5d403a6b-20190731183523.zip

In the instance that a Jammer is accidentally given lead and then the lead is removed from the scoreboard, the NI for that Jammer can't be reinstated by selecting the NI button. If they've not had an initial pass by the time the jam finishes, they need to manually have the NI reinstated

**Comment by frank-weinberg** [comment]
You can remove trip2 either using the "Trip -" button (if the next Jam hasn't started yet) or after clicking on it in the SK sheet.

**Comment by bullseye555** [comment]
Thanks Frank

Closing 356 - merging to Feature Request 355
