### ISSUE TITLE
Changes after declaring the score final don't get added to the game data file

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#377]
Such changes are a regular occurence when PT/LT/PBT compare their notes, which usually isn't completed before "Final Score".
This can be worked around by unsetting and resetting the "Final Score" flag after all changes have been made, but there should be a more obvious way.

**Comment by frank-weinberg** [comment]
After running full PLT this weekend with a crew that had read the Wiki page mentioning this bug and workaround and me present as well, we had 1 game out of 13 where the workaround was applied. Based on that experience I'd say this has to be fixed before release.

**Comment by aoanla** [comment]
The "obvious" solution would be to provide a "finalize statsbook" button, which basically does all the same things that Final Score does [but doesn't toggle the Scoreboard state that sets the display]?

**Comment by brian-brazil** [comment]
We could write out the file on all changes after final, but would need some care to not accidentally blow things away on Start New Game.

**Comment by aoanla** [comment]
I agree, which is why I think it's probably mechanically easiest to do this by providing the Operator with a button to press to Finalise things, before Starting a New Game (with a separate Button). My interpretation of the issue with the workaround is that "toggle Final Game state" doesn't easily map to an actual operation in the average human brain, but "Finalise Statsbook" (or even "Sign off Statsbook") feels like an actual thing that people do at the end of a bout.

**Comment by brian-brazil** [comment]
I think this is something that shouldn't require any operator action.

You can always grab a copy of the copy to statsbook page.

**Comment by frank-weinberg** [comment]
> I think this is something that shouldn't require any operator action.

I fully agree.

I had the idea to write after every change except clock changes once the score is final. But we'll have to check if the amount of writes remains reasonable and how this interacts with "Start New Game".

**Comment by brian-brazil** [comment]
Performance isn't a major concern once the game is over, I'd worry more if there was a journalling filesystem in use as it may eat disk a bit there but I doubt that'll come up.
