### ISSUE TITLE
Penalty Ticker on stream overlay

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#387]
Feature request from an official while watching champs:

It would be nice to have information about recently added Penalties on the overlay during gameplay. Maybe as a popin item that shows player and code and disappears after a few seconds or as a ticker on a separate line.

**Comment by brian-brazil** [comment]
One thing to think about is what happens when an NSO misenters a penalty, or corrects an old one.

**Comment by frank-weinberg** [comment]
Changes to penalties still displayed should update the display, once gone, updates should probably be ignored.

And when LT is being used we could display them as long as they are either unserved or their corresponding box trip is ongoing.
