### ISSUE TITLE
Basic question: saving a game/scoreboard

### ISSUE THREAD

**Issue by NancyEH** [rollerderby/scoreboard#39]
On the FB page, someone said it was possible to save a scoreboard by right-clicking, then "save as". I don't see a "save as" there, just a "save **link** as", which is what I did. I could then "save as" scoreboard.

However, the file that shows up is not exactly gibberish, but darned close (screenshot). What am I missing in the process? 

![screen shot 2018-03-23 at 6 17 23 pm](https://user-images.githubusercontent.com/37547310/37855615-87159fb2-2ec6-11e8-8609-165b789af954.png)

**Comment by rogerharkavy** [comment]
@NutHatchME They were probably referring to the functions on the Save/Load tab. See the wiki: https://github.com/rollerderby/scoreboard/wiki/Save-Load
