### ISSUE TITLE
Un-stop jam doesn't reset fieldings and flags

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#397]
Start a jam with a jammer selected, mark lead, stop jam, unstop jam.

You'd expect the jammer to still be fielded, and Call to be unmarked - however that doesn't happen. This seems to be due to ScoreBoard.Team not getting updated, which I suspect is related to updateTeamJams using Flags.INTERNAL.

**Comment by reflexdd** [comment]
I noticed a similar behavior. I sleceted skaters via LT page and started a jam and un-started the Jam. Skaters in the LT-Section are still marked green but can't be reseted via the bench-button.  if you would select a new Skater that skater will also be marked green. 
To unselect those skaters for the un-started jam it is needed to reselect those skaters to remove them.
![Screenshot_2019-11-27 Lineup Tracker](https://user-images.githubusercontent.com/58275718/69763656-28fd8700-116e-11ea-9d22-c9af5bf9ffa8.png)
