### ISSUE TITLE
Check screen usability for color blind users

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#410]
Last weekend I had a PLT who had a very hard time noticin the light blue highlight on the shaded rows of the PLT screen. This caused problems as the source of skaters not being reset to the bench was unclear.

**Comment by brian-brazil** [comment]
Do we know which type of colourblindness they had?

**Comment by frank-weinberg** [comment]
No. They did not even mention colourblindness as source of the problem. Just that they could hardly make out the highlight.

**Comment by brian-brazil** [comment]
Found some filters online, and it's barely visible for Protanopia (red-green blindness).

We might want to consider adding indications beyond colour for anything critical, to make sure we catch everyone. In this case maybe something like Box/In/Pending for the text?

**Comment by frank-weinberg** [comment]
We have the Box field in the LT part and the Penalty in the PT part and I guess both need to be changed. The changing text should work quite well for the Box field but I'm not sure there's enough room in the penalty field.

**Comment by brian-brazil** [comment]
Penalty codes are only one letter, so we could put some other indicator there. We could also choose some unicode arrow and put it in the corner.

**Comment by frank-weinberg** [comment]
If you have an idea, go ahead. I'll be woring on the Jammer names and undo first.

**Comment by bullseye555** [comment]
How about something like
  ◻ = Penalty Issued and not yet served or serving
  ◯ = Penalty being served
  ◼ = Penalty served ?

https://en.wikipedia.org/wiki/List_of_Unicode_characters#Geometric_Shapes
U+25FB ◻ White medium square
U+25FC ◼ Black medium square
U+25EF ◯ Large circle

~Bullseye

**Comment by brian-brazil** [comment]
I was looking at ◀ and ◁, as on the PLT screen anyway that points towards the meaning which will be text.

**Comment by brian-brazil** [comment]
I'd also avoid anything for when a penalty is served, as that's the usual case and thus we should avoid cluttering things up in that case.

**Comment by bullseye555** [comment]
Yeah,

Happy with that :)

~Bullseye

**Comment by brian-brazil** [comment]
Here's a first shot at it:
![Screenshot_2019-12-09_00-46-57](https://user-images.githubusercontent.com/7115638/70399610-722ac200-1a1d-11ea-9f1d-980c7cbf64b6.png)

I went for consistency between the LT and PT parts of the page.

**Comment by bullseye555** [comment]
And that'll be the same on the standalone PT page?

Otherwise looks good

**Comment by brian-brazil** [comment]
Yes, presuming you've got Track Penalty Serving enabled which you should only do if you have LTs of some form (or want to get your ePT to do eIWB - which the UI is not designed for).

**Comment by bullseye555** [comment]
Yeah - EXTREMELY unlikely that you'll have ePT tracking penalty serving. If
there's no ePLT, the Penalty Serving will likely be set to Automatically
Served

**Comment by frank-weinberg** [comment]
On first glance it looks a bit crowded. But I guess that's because there's an unusually high density of markings in this screenshot. And after a short time of getting used to it it's fine.

**Comment by reflexdd** [comment]
what about having the arrow pointing towards the Box when they are on the way. That makes it more clear that they are going to the box.

**Comment by brian-brazil** [comment]
I think having the same arrow gives more of a hint of what this means than two different arrows would.

**Comment by reflexdd** [comment]
But then having only one arrow pointing towards right would be sufficent to distinguish the blue and red and it would be more intuitive readable

**Comment by brian-brazil** [comment]
eLT however doesn't have the penalty code cell, just the Box cell.

**Comment by reflexdd** [comment]
yep, but also in eLT it would make more sense having only the arrow pointing to the right. 
Wouldn't it be sufficient information to have it like in the attached Screen?
![pt-lt-arrow](https://user-images.githubusercontent.com/58275718/70440832-5b26b700-1a93-11ea-9fd4-7bc3a3e64685.jpg)

**Comment by brian-brazil** [comment]
That has the equivalent problem then though, the ones on the PT side don't point to the box.

**Comment by reflexdd** [comment]
Ok I see hat you mean, but I would't have related the arrow in the PT Section to the Box-Field at the first sight. For me it would still read as "on the way to the Box serving the following Penalty"

**Comment by frank-weinberg** [comment]
I think having the arrows point towards the "Box" resp. Penalty code they refer to makes sense.
But I'd then read the (filled) arrow pointing to the "Box"/Penalty as "Skater is currently in the box/serving this penalty". The unfilled one as "on the way" then flows naturally from that.

**Comment by reflexdd** [comment]
then maybe that one in combination with a dot for serving would make also sense. But also the not filled arrow would look good.
![pt-lt-arrow-point](https://user-images.githubusercontent.com/58275718/70443545-a394a380-1a98-11ea-8205-851564567a5a.jpg)

**Comment by frank-weinberg** [comment]
If we use different shapes, how about a Pause (⏸) for sitting?

**Comment by reflexdd** [comment]
Those two vertical lines could be irritating when serving an I
The ◼ would be also associated with "stopped"

**Comment by brian-brazil** [comment]
Paused could be confused with Pivot. If we ever add ePBT I can also see that being confused with timing being stopped.

**Comment by frank-weinberg** [comment]
Different approach: Use a period for completely served penalties, mimicing the dot on the physical IWB. Then @reflexdd 's large dot for currently serving is just an emphasized version of this dot.
And for unserved, an exclamation point could be an option, indicating that this needs attention/further action.

Additional advantage: This degrades gracefully when a user doesn't have a unicode font.

**Comment by brian-brazil** [comment]
That makes sense.

**Comment by brian-brazil** [comment]
Though what would you use for currently serving (as against served)?

**Comment by frank-weinberg** [comment]
As I wrote: The large dot from https://github.com/rollerderby/scoreboard/issues/410#issuecomment-563263832

**Comment by brian-brazil** [comment]
I think having the same shape in two different sizes will cause confusion when users are talking about this feature, something more distinct would be good.

**Comment by brian-brazil** [comment]
I played around a bit, and an endash seems to work. And it's kinda like sitting...

**Comment by brian-brazil** [comment]
![Screenshot_2019-12-14_14-32-16](https://user-images.githubusercontent.com/7115638/70850108-8c7df900-1e7e-11ea-9878-9e20865f2f9f.png)
