### ISSUE TITLE
Duplication of Undo button when reassigning shortcut key

### ISSUE THREAD

**Issue by GorramRob** [rollerderby/scoreboard#429]
Running 4.0.1, while assigning keyboard shortcuts, if a key is assigned to the undo button, then another button/control is hovered over and the same keyboard key is pressed again, the undo button flashes (as expected) but a second undo button appears next to the original undo button. 

Refreshing the operator screen is a quick work-around (the operator screen refreshes with only a single undo) but this looks like a small bug.

**Comment by brian-brazil** [comment]
Yeah, internally undo and replace are actually separate buttons. This is harmless but should be fixed at some point.
