### ISSUE TITLE
Bug - Start a Jam / Star Pass / Un-Start-Jam

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#433]
I was playing arround a bit with the Star Pass and Un-Start-Jam-Button and noticed an unexpected behaviour:
Select J/P > Start Jam > Star Pass > Un-Start Jam > Start Jam

I would expect that also the push of the Star-Pass-Button would be revoked. But if you start the Jam again the SP is still set active.

I know this will mostly not happen but I have the impression it should be fixed.

Noticed on v4.0.1

**Comment by brian-brazil** [comment]
If memory serves this is on purpose, it's one of several stats (in particular score) that are not changed in case someone in confusion does lots of undo-ish actions.

**Comment by frank-weinberg** [comment]
Yes, this is a conscious choice. There is no obviously and always correct way of handling Un-Starting a jam for which data (SP, Trip+, Points) has already been entered. But

1. it is more likely that the Undo was in error than that both the Start and the entry of Jam data have been in error and
2. it is generally harder to recreate deleted data than to remove extraneous data.

**Comment by AdamSmasherDerby** [comment]
I agree with the status quo, and recommend closing this issue.
