### ISSUE TITLE
Handle forfeits

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#437]
Currently forfeits are not modelled in the scoreboard, and it's not obvious how to go from being in the middle of a period to final score - before even indicating what has happened (particularly if the team with the higher score forfeited).

We should probably track this (end of period controls I guess?) and have a way to display it on the scoreboard and overlay.

**Comment by AdamSmasherDerby** [comment]
I don't think indicating "FORFEIT" on the scoreboard is necessary, but a button that is marked "End Game" or the like under the "End of Period Controls" seems useful. On the scoreboard, "Final Score" is enough of a public facing indication that the game is over, and the circumstances around forfeits are so diverse that it's not really useful to try and account for them individually.

**Comment by brian-brazil** [comment]
I was kinda thinking of remote audiences. At least in house the announcers can explain what's going on, but that may not be the case for a stream.
