### ISSUE TITLE
Star Pass + Initial Trip Points

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#440]
When trying to record initial trip points (say, during an overtime jam 😄 ) after a star pass, the initial points seem to bounce around between the original jammer and the new jammer.

Replication Steps:
1. Start an overtime jam (or for now, a normal jam), with jammers and pivots assigned
2. Click the "Star Pass" button
3. Click the "Score +1" button
a. Points will be recorded on the original jammer
4. Click the "Trip +1" button (or wait for the trip to advance automatically)
a. Points will now be recorded on the new jammer
5. Click the "Trip -1" button
a. Points bounce back to the original jammer

It appears impossible to record a the following scenarios
1. Original Jammer scores points on Trip 1, New Jammer scores points on trips 2 through n
2. New Jammer scores points on Trip 1 but never makes it to trip 2.

Low Priority, but the bouncing between jammers suggests that there is something subtle going on with the trip assignments.

**Comment by frank-weinberg** [comment]
I think this is purely a frontend issue. The case of points on initial/first trip and SP on first or second trip has just been forgotten.
