### ISSUE TITLE
Cannot edit points on trips 11+

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#441]
(I am guessing this is a known issue, but want to log it since I was playing at the margins to generate test cases for Smasher's tool)

When a jammer has 10 or more trips, the scoreboard does not allow for editing of points recorded on trips 11 or beyond.  If I catch the issue during lineups, I can fix the issues using the trip/score buttons, but in subsequent jams trips and points beyond 11 are "locked in".

It's obviously an incredibly niche issue that will (never?) show up in normal game play, but the inability to edit the score on trips 11+ can create a situation where the score is irreparably wrong -- A scoreboard operator would have to remove points from a previous scoring trip to make the scoreboard display correctly.

**Comment by frank-weinberg** [comment]
I remember @brian-brazil recently mentioning the idea of adding "Previous Trip" and "Next Trip" buttons to the edit box. That would cover this issue.

**Comment by brian-brazil** [comment]
Yeah. It should be rare enough that that's sufficient.
