### ISSUE TITLE
Period clock changes missing from scoreboard display

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#444]
I ran current HEAD at a tournament this weekend and about half the time when the period clock was adjusted during a timeout the last change did appear on the operator screen but not on the main scoreboard. (Both on the same machine as the backend.)

I intend to look into this myself in the coming days but wanted to flag this for other dev users and as a blocker for the 4.0.2 release.

**Comment by brian-brazil** [comment]
Just tested this on dev, but no sign of any issues.

**Comment by frank-weinberg** [comment]
Testing here, I had no issues for the first 3 or 4 attempts, since then I see it consistently. On every manual change (and only on manual changes) of a countdown clock the scorebaord display will go to a value 1s too low. count up clocks are fine, changes triggered by clock ticks are fine. This does not make any sense at all.
