### ISSUE TITLE
Entering Abitrary Scoring Trips on SK Sheet

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#448]
In the current scoreboard, you can click on any scoring trip and enter a score in that trip, even if there are not scores in previous trips.  Whereas on the ePT sheet, if I click in an empty box in the row for a given skater, I will enter the "first available" penalty for that skater, rather than in the box that I actually clicked on.   

As a visual aid, I am talking about clicking somewhere in the highlighted section
![image](https://user-images.githubusercontent.com/1295669/74754460-3f7c2180-5237-11ea-90f3-fcff6db2925d.png)

Fortunately, the underlying data model + front-end code seems to do the right thing when I enter points in an arbitrary trip.  Currently, CRG-to-Statsbook doesn't pick up the trips, however.

I think that the current behavior is something of a foot-gun/overly surprising, especially given the mismatch with how the ePT page operates.  Additionally, There isn't necessarily a use case for the current behavior, so I think it would be worth discussing alternative behaviors:

1. Open on the next empty scoring trip (in the case of the above screenshot, open on "Trip 3").  Essentially align the behaviors between ePT and eSK
2. Open on the last entered scoring trip (in the case of the above screenshot, open on "Trip 2").
3. A somewhat hybrid approach, open on the current trip if the jam is active and the score is 0 (eg if there is only a "." in the box), otherwise open on the next trip.
4. Don't open a pop-up if it's not a current scoring trip or the next scoring trip.
5. Something else entirely.

**Comment by brian-brazil** [comment]
1 would make the most sense to me. I think that's safe even if the backend has advanced the trip but the frontend doesn't know about it just yet.

**Comment by frank-weinberg** [comment]
I'd be fine with 1 as well.
