### ISSUE TITLE
Clear All Teams Functionality?

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#449]
v4 removed all of the "clear the scoreboard" functionality, but I believe there is a sufficient use case to allow users to clear down at least teams, and possibly teams+media.

The use case I envision: Using a given laptop for a tournament, I would like to be able to set up a bunch of teams, possibly load in ads or other media, then after the tournament clear out all the teams I added while retaining other elements (say, custom rulesets, prior games played, other settings)

I could create multiple copies of the scoreboard directory to accomplish this currently, but that can (and has, when I've done this in previous versions) lead to confusion when a user has to restart the scoreboard.

I'm happy to scratch my own itch on this, but I wanted to take the temperature on how much resistance there would be to a pull request that added this sort of functionality.

**Comment by reflexdd** [comment]
But removing teams and media is available in the new version. Or do you mean something like selecting multiple teams and removing all at once?

**Comment by official-sounding** [comment]
you can remove one team at a time, but that can be tedious if you need to remove all the teams for a tournament (could easily be 20-30 teams if you have multiple copies set up for different color schemes).  It's a somewhat niche use case admittedly but also potentially common enough to justify the relatively simple addition.

**Comment by frank-weinberg** [comment]
I'm not opposed to having this functionality per se but I wonder how much intended use it would actually see compared to use as a foot-gun.

Given that this can be done in pure frontend and will presumably be used by the person preparing the scorebaord, maybe do it as a custom screen? If it becomes popular that would be a good reason to then integrate the functionality here.

**Comment by AdamSmasherDerby** [comment]
This is something I had to do a LOT with older versions, where the program slowed down more and more as the team list grew.

I don't think it's QUITE as urgent now that the lag doesn't grow with the team list.

That said - a lot of leagues (in the states at least) have a number of one time opponents that they won't see again for a long time.  The team list can gradually get quite cluttered with rosters that, at best, will be completely out date by the time the opponent returns, and in many cases, will NEVER return.

I think it's a reasonable button to add to the main distro.

One could also envision a "Utilities" custom screen that has a number of frontend-achievable tasks, although off the top of my head I don't have any ideas for other likely candidates.
