### ISSUE TITLE
Expulsion should allow selection of a penalty

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#45]
Current standard practices (on paper) are that when a skater is expelled, a penalty code is entered on the paperwork, not "EXP".  We should probably update the penalty tracker to follow this practice.  Recommended method:  When the FO/EXP box is clicked, instead of the only options being "FO" and "EXP", the option screen should start with "FO," and then list unique EXP options for each possible foulout code.

My understanding at present (reflected in the statsbook) is that EXP codes would not be needed for "I" or "X".

For example:
"FO" "EXP-A" "EXP-B", "EXP-C", "EXP-D", etc...

**Comment by official-sounding** [comment]
More of a rules question than anything, but under the 2018 penalty codes, I can't really conceive of a way to get an expulsion for Illegal Position any more, I left it as a possible code though, only excluding I & X.

**Comment by AdamSmasherDerby** [comment]
It's unlikely, but a team who willfully refuses to reform a pack, or a blocker who chases a jammer for three turns ignoring the initial failure to return penalty could possibly incur this.

**Comment by brian-brazil** [comment]
This was fixed.
