### ISSUE TITLE
Point users to the Wiki page

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#453]
Can someone with the necessary rights please make a link to https://github.com/rollerderby/scoreboard/wiki/Changes-in-Version-4 and Brains Videos as prominently visible as possible to anybody who visits the user Facebook group?

It's annoyng as hell to read complaint thread after complaint thread where almost al the specific items that are mentioned are covered on both of those resources.

**Comment by ghost** [comment]
Wouldn't it be with pinning a post in the facebook group explaining the resources available to support operators in using 4.0.1 and setting up a 4.0.1 FAQ page on the wiki, which could directly link to some of the recurrent issues which people are having?

**Comment by JeneralPain** [comment]
This will be done shorty

**Comment by frank-weinberg** [comment]
I have had an unexpected burst of available time and used it to update the wiki. So pointing to the specific page should no longer be necessary.
