### ISSUE TITLE
Re-instate manual score over-rides

### ISSUE THREAD

**Issue by SticksandStoner** [rollerderby/scoreboard#455]
Would it be possible to reinstate the ability to manually overtype the scores? This would be invaluable to facilitate rapid reinstatement of play following a catastrophic CRG failure that has required more than a java restart.

**Comment by frank-weinberg** [comment]
The data model requires that any point is assigned to a specific trip. The specific scenario you describe can be covered by adding all the required points to a single trip. (Assuming you don't care about the stats at that point.)

**Comment by SticksandStoner** [comment]
Is there a faster way of doing this than adding every point individually and creating new jams for every jam that's happened? Fundamentally, we had a timeout increase in length by 2+ minutes because we had to add 20+ jams and approx. 200 points in order to have a public facing match to the number of jams and number of points.

This isn't good for gameflow, and is incredibly stressful for officials.

**Comment by frank-weinberg** [comment]
For the jams there is no other way than iserting them one at a time. Depending on where in the period you are it may be worth considering to leave the jam number wrong or maybe off by 10 or 20.

For the points click on trip 2 for any jam in the paperwork and in the popup enter the number of points for that team.

**Comment by ghost** [comment]
That is an added layer of complexity to fix a simple error (or in this particular incident the java app hard crashing)

**Comment by SticksandStoner** [comment]
> For the points click on trip 2 for any jam in the paperwork and in the popup enter the number of points for that team.

That's good to know - I hadn't seen any reference to that being possible in any of the documentation, however useful for the future.

**Comment by SticksandStoner** [comment]
> For the jams there is no other way than iserting them one at a time. Depending on where in the period you are it may be worth considering to leave the jam number wrong or maybe off by 10 or 20.
>

I don't think this is really an appropriate solution, given the number of people at a derby game who use the jam number information (paper PLT, box timers, potentially announcers and stream). 



Yes, there *should* be systems which ensure that people aren't reliant on the scoreboard display for that, but in reality, that relies on everyone knowing what jam number CRG died on and maintaining a record.

**Comment by frank-weinberg** [comment]
https://github.com/rollerderby/scoreboard/wiki/Changes-in-Version-4#sk-sheets mentions it right around a screenshot of the popup. https://www.youtube.com/watch?v=NFCDHcGLf2Q&list=PLWi76Bd9Lfof46zUSEdZY7vrsF7WA6NxK&index=8&t=205s explains it as well. (They don't cover this case explicitly but explain that you can enter point s in the poup.)

**Comment by SticksandStoner** [comment]
> https://github.com/rollerderby/scoreboard/wiki/Changes-in-Version-4#sk-sheets mentions it right around a screenshot of the popup. https://www.youtube.com/watch?v=NFCDHcGLf2Q&list=PLWi76Bd9Lfof46zUSEdZY7vrsF7WA6NxK&index=8&t=205s explains it as well. (They don't cover this case explicitly but explain that you can enter point s in the poup.)

Brilliant. I had made the assumption that adding a score greater than 4 would simply refuse to work, given that just dropping speed scores in didn't work.

**Comment by frank-weinberg** [comment]
> I had made the assumption that adding a score greater than 4 would simply refuse to work

The Wiki page now explicitly mentions that a trip can hold arbitrarily many points.

> I don't think this is really an appropriate solution, given the number of people at a derby game who use the jam number information (paper PLT, box timers, potentially announcers and stream).

The thing is that adding the option to add multiple Jams at once will make the interface even more complex. And for a use case that we would hope to be pretty rare. (If the backend regularly crashes so hard that a new game has to be started, we have a big problem.)

But combined with the request from the group a couple of days ago about setting up scenarios for  a scrimmage, maybe we can add a section to the Start New Game popup where you can set specific times, period/jam number, scores, and timeouts used. Since we are starting with a fresh game then, we avoid all the complications of figuring out where to remove jams/points/etc. that caused the direct edit options to be removed.
