### ISSUE TITLE
Is release.html necessary?

### ISSUE THREAD

**Issue by rogerharkavy** [rollerderby/scoreboard#46]
We have a release notes page that hasn't been updated since 3.9.1:

https://github.com/rollerderby/scoreboard/blob/dev/html/release.html

Is this file necessary when we have detailed release notes on the GitHub releases page?

https://github.com/rollerderby/scoreboard/releases

**Comment by yetzt** [comment]
it's nice for end users to see whats changed in between versions without having to resort to reading commit messages on github. not every scoreboard operator out there is a developer. since there hasn't been a stable release [since 3.9.0](https://drive.google.com/drive/folders/0B5MEhWEBhGKVSTlTZW1mcFdobnM) (release as in "on the google drive", not as in "release on github") it's up to date, but don't refrain from maintaining that file.

**Comment by rogerharkavy** [comment]
I agree, it's good for users to see what has changed and release notes are useful, but they are already getting them from the page where we are telling them to download the software:

https://github.com/rollerderby/scoreboard/releases

Duplicating this information in release.html seems redundant. Also, if the file isn't being updated on a regular basis, it isn't useful.

**Comment by JeneralPain** [comment]
Could we not put this into the front page of CRG in the pull when people grab the zip?

Like "release notes" when you hit the :8000 page?

**Comment by rogerharkavy** [comment]
@JeneralPain I'm not entirely sure I understand what you're proposing, but I originally opened the issue because:

- release.html hasn't been updated since 3.9.1
- Release notes are already provided on https://github.com/rollerderby/scoreboard/releases
- It doesn't make sense to maintain this information in two places

**Comment by JeneralPain** [comment]
Agree it hasn't been updated...

I'm saying have it on the GITHUB location, but then also build it into the actual app itself, so it's visible to the scoreboard also. Like a link on the primary home page of the actual scoreboard itself. Which could pull that data from the releases page (like when we build it and create the zip).

**Comment by rogerharkavy** [comment]
I think putting any additional information on the start page would add unnecessary clutter.

To me, the question "What's new with this release of the software?" only needs to be answered once for the person who is going to be downloading and installing it, and if you put that information on the download page, they're definitely going to see it.

**Comment by JeneralPain** [comment]
Actually I heavily agree with your last points about clutter and keeping it simple.
