### ISSUE TITLE
Clarify the use of the "Insert Before" button for trips

### ISSUE THREAD

**Issue by charlie-chaperon** [rollerderby/scoreboard#460]
**Situation:**
If you click on any trip in the SK sheet, the scoreboard will open a dialogue for that trip. 
Let's assume the following example:

* White Jammer 12 got lead, and completed the scoring trips 2 and 3 with 4 points, calls the jam and recieves 0 points for trip 4 as they entered the EZ.

* The SK shows:
0 points (Initial)
4 points (trip 2)
0 points (trip 3)

* The SBO wants to add another trip with 4 points and clicks on trip 2, the dialogue opens.
* The SBO clicks on "Insert Before" to add another trip.

**What the Scoreboard does:**
The Scoreboard inserts a new trip 2 with 0 points. All subsequent trips are moved to the right (or +1), so now the SK shows:

0 points (Initial)
0 points (trip 2)
4 points (trip 3)
0 points (trip 4)

**The issues:**
a) It is not very clear, what "Inserting Before" actually means. 
Labeling it "Insert a trip with 0 points before that trip" is more precise but too long.
b) after Inserting a new trip 2 with zero points, the dialogue is still labeled the same:
"Period X Jam Y Trip 2" and it still shows 4 points, although in the SK you can already see 0 points for that trip. The SBO can add as many trips as they want, but can only remove one at a time as the dialogue closes after you hit "Remove"

The label of the dialogue is misleading because it doesn't update the trip.

**possible solutions:**
a) Add a description for the "Insert Before" Button.
b) close the dialogue automatically after "Insert Before" is hit (like when you hit "Remove"). After the Dialogue for trip 2 is opened again, it should now show 0 points.
c) Change the 4 points in the counter to 0 after hitting "Insert Before"
d) advance the label "Period X Jam Y Trip 2" so that it shows trip 3 after hitting "Insert Before"

**Comment by frank-weinberg** [comment]
Some changes to this button have already gone in and will be in the next version:

- The text on the button is changed to "Insert Trip". The hope is that this makes it clearer that the trip will be inserted in the place that was clicked on. (Same goal as a)
- After inserting the new trip the editor switches to editing the newly inserted trip (c).

Does this resolve the issue?

**Comment by charlie-chaperon** [comment]
That sounds good. 
It actually is what I described under c).

Additional proposal:

- name the Button "Insert preceding Trip" - does that sound better or understandable?
- Is it possible to add another field near the "Insert trip" button where you can already define the points (standard would be 0)?

**Comment by frank-weinberg** [comment]
> name the Button "Insert preceding Trip" - does that sound better or understandable?

Not to me. 

> Is it possible to add another field near the "Insert trip" button where you can already define the points

That brings the risk that users confuse it with the one where you can edit the current trip. And as the popup switches, click button then type points doesn't take longer than typing points first and clicking after that.
