### ISSUE TITLE
[BUG / URGENT] Penalty data should be persistent on server restart

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#47]
When the Java server is restarted, the penalty data is not retained.  It probably needs to be. With WFTDA moving to use this functionality for playoffs/cups/champs, I would consider this a _very_ high priority item from a reliability standpoint.

**Comment by JeneralPain** [comment]
This has been proven by CRG DEV team, and I have prioritised as urgent. It's now under significant discussion.

**Comment by brian-brazil** [comment]
This can be closed with #59
