### ISSUE TITLE
Announce the release of v4.1.1 in the Facebook group

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#474]
v4.1.1 has been released today. Since I'm not on Facebook, I can't do the announcement myself.

**Comment by JeneralPain** [comment]
Hi Frank,

If you want to send me the details I'll get this done for you now?

Regards

Jen

**Comment by JeneralPain** [comment]
I have done this.

**Comment by frank-weinberg** [comment]
Thank you.
