### ISSUE TITLE
URGENT - No Penalty Codes Visible

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#475]
Version: 4.1.1
Browser: Chrome 84.0.4147.125 (Official Build) (64-bit)

Verified bug in CHROME, EDGE and IE (in both incognito & normal mode).

To reproduce:
1. Start game
2. Go into PT screen
3. Select penalty to issue it.
4. Screen is completely blank.
@frank-weinberg as you released 4.1.1, you may know what has changed.

**Comment by JeneralPain** [comment]
Build log:
https://pastebin.com/TpcSSSGa

**Comment by frank-weinberg** [comment]
I can reproduce this and am looking into it. The problem seems to be in the backend.

I'll bring out 4.1.2 with a fix as I got it. (Hoping for today european time.)

**Comment by JeneralPain** [comment]
Thanks @frank-weinberg :) appreciate it.

No rush given we aren't allowed to play contact sports anyway...

This is what happens when the world uses Norton Antivirus.

**Comment by frank-weinberg** [comment]
4.1.2 is up with the fix.

> No rush given we aren't allowed to play contact sports anyway...

In some parts of the world people are back to scrimmaging as far as I am aware. And either way it's a good opportunity to train getting a fix release out quickly.
