### ISSUE TITLE
Closing the CRG with write-access to new devices disabled locks the operator out

### ISSUE THREAD

**Issue by charlie-chaperon** [rollerderby/scoreboard#477]
**Summary:** Disabling write access to new devices might cause unintended feature behavior as it can lock out the operator running the CRG.

**tested versions:** CRG v4.1.1 and v4.1.2

**Description:** When the scoreboard is turned off while write access for new devices is turned off in the Devices tab, the scoreboard will resume at the point of cancellation, but the user will be locked out.

This is due to the fact that the device running the CRG will get a new identity which will interpreted as a new device without write permissions. The old identity is still shown (Read and Write).

Since every input is rejected ("Not authorized for Set" message pops up) it isn't possible to start a new game or to reactivate access. Though this seems to behave as intended, there should be a way to regain access.

**Suggestion:** Write access should always be enabled for the device running the CRG software. This way, it will also be possible to change the main CRG device (e.g. during halftime or after a major crash).

**Comment by frank-weinberg** [comment]
> there should be a way to regain access.

There are ways (that take a bit of effort, however). See https://github.com/rollerderby/scoreboard/wiki/Using-the-Scoreboard-on-a-Network#regaining-write-access-when-you-are-locked-out-of-the-scoreboard

But I'll look into if your suggestion can be implemented with reasonable effort as an additional option.

**Comment by charlie-chaperon** [comment]
I should have known there is already a wiki entry :D

- [x] Method 2 works fine and is easy to do.

- [ ] Method 1 did not work, probably because step h) doesn't work:

- After i select my backup json and press "Replace running scoreboard" nothing seems to happen, no confirmation, no loading graphic, no interruption. Tested it with Firefox 68.10.oesr and Chromium 73.0.3683.75 on Debian 9. It might be a browser problem though.

Still, i think permanent write access for the device running CRG  is a reasonable solution because i cannot think of a setting where this would be a security problem.

_Edit: Thanks for considering, Speedy. Designing it as an option sounds like a good idea. It could be activated (or not) by default._
