### ISSUE TITLE
(Un-) Official Score is not displayed at the end of a game

### ISSUE THREAD

**Issue by charlie-chaperon** [rollerderby/scoreboard#478]
**CRG versions tested**: 

- v4.1.1

- v4.1.2

- v4.0.1 - this version works properly

**used browsers**: Firefox 68.10.0esr without addons (history deleted after closing) and Chromium 73.0.3683.75 (history is kept)

**Steps to reproduce:**

1. Start New Game
2. Start first Jam, adding points is optional
3. Set period time to 10 seconds and let the period expire
4. Set the Intermission clock to 10 seconds
5. After Intermission ended, set period (2) clock to 10 seconds
6. Start new Jam, optional data input

After the jam ends with no time left on the period clock, the scoreboard shows "Intermission" + a timer instead of "Unofficial Score". Additionally the End of period controls button does not flash.

**Further Information:**
This also happened after i used the scoreboard to track an online game, without setting the clocks. The (Un)Official Score display is not triggered.

**Comment by frank-weinberg** [comment]
The fix for this (and your other issue) is now released in 4.1.3.
