### ISSUE TITLE
REQUEST: Add button to main interface to restart period clock and lineup clock after an OTO, where there are <:30s left on period clock.

### ISSUE THREAD

**Issue by voidptr** [rollerderby/scoreboard#48]
In prior releases, it was possible to automate this process by binding the old stop TO, start lineup, start Period clock buttons to a single key. Now that these buttons were removed, this is no longer possible.

This is a business rule that is required by the rules of roller derby, and it happens often enough that we need a proper button for it. 

Maybe locate it somewhere nearby to where we put the new endTO/startLineup button?

**Comment by frank-weinberg** [comment]
Instead of adding a new button it should be possible to add a detection for this situation to the logic applied for the end TO button. This should probably be configurable in the rules editor.

As a workaround making the start/stop buttonsfor the individual clocks accessible again would solve the immediate problem. But these buttons should not be needed during normal gameplay.

**Comment by AdamSmasherDerby** [comment]
The requirement to restart the period clock again after a timeout is ONLY necessary when there are 30 seconds remaining on the period clock and there would *not* have been another jam.  If there *would* have been another jam, there's no necessity to restart the period clock.

So the lineup clock is irrelevant here - the period clock controls in all cases.

However - we DO need a way to simultaneously end the timeout and restart the period clock.

**Comment by AdamSmasherDerby** [comment]
For now, best practice would seem to be 
1. Click the timeout clock.
2. Clock Stop
3. Click the period clock.
4. Click start.

This is something that should be fixed for sure, but at least there's the steps for making it happen as it stands now.

**Comment by JeneralPain** [comment]
The team in the development crew have discussed this at length, given the potential impacts specifically to high level sanctioned play where this is a requirement, we have tagged this as an urgent issue. We will do our best to release a patch/update to this as quickly as possible.

Thanks

JP - Issues Management Team

**Comment by voidptr** [comment]
The lineup clock aspect of this is actually VERY IMPORTANT. Consider the following pair of scenarios:

Scenario 1: Jam ends, there's enough time for another jam (35s on the period clock). Period clock ticks down to 15, lineup clock is at 20. JT is getting ready to say 5s. HR blows OTO. Time passes. OTO ends, period clock restarts (because there are less than 30s), lineup-clock does not continue from where it was. Everyone is confused, because there are now less than 30s to start the next jam. 

Scenario 2: Jam ends, there's enough time for another jam (35s on the period clock). Period clock ticks down to 15, lineup clock is at 20. JT is getting ready to say 5s. HR blows OTO. Time passes. OTO ends, period clock restarts (because there are less than 30s), **lineup clock restarts at 20. JT calls 5 seconds at Lineup Clock 25. Jam starts.** 

Obviously, however, there's potential for additional confusion with a lineup clock starting midway through its run. What the appropriate behavior is merits additional discussion.

**Comment by frank-weinberg** [comment]
@voidptr In your scenarios the period clock *does not start*. Rules 1.3.3 only introduces a special case, if no jam would have occured without the timeout. Officiating procedures 3.1.2 explicitly confirms that the period clock is not started in your scenario(s).

**Comment by voidptr** [comment]
I agree. However, if the rule is implemented as an automatic restart based on purely detecting the clock time, with no regard for the lineup clock state, then the wrong thing would happen. 

I mentioned it because Speedy proposed an automatic, non-button-based fix in the Facebook post.

**Comment by voidptr** [comment]
@frank-weinberg And I see you proposed the same thing above. Are you Speedy? ;)
