### ISSUE TITLE
Can't access "jarfile lib/crg-scoreboard.jar"

### ISSUE THREAD

**Issue by rodoreda29** [rollerderby/scoreboard#487]
Hi y'all,

I am having some issues running the program. I am not very knowledgeable but trying to set up my computer for my league's next bout :)

I have downloaded the last version of the CRG scoreboard (v4.1.4) and downloaded and installed/opened both versions of Java Oracle for macOS (Arm 64 Compressed Archive, Arm 64 DMG Installer, x64 Compressed Archive, x64 DMG Installer). 

Every time I try to run it (both the file "scoreboard.sh">open with>Terminal and opened the file "start.html"), it doesn't work. Attached to this request there are screenshots of both attempts.

The question here is if there's something still missing, or maybe I cannot run it with this computer (it is a macOS v11.5.1 with a M1 chip)? Any help is more than welcome.

Thanks!

<img width="1440" alt="Screenshot 2021-11-01 at 22 58 56" src="https://user-images.githubusercontent.com/71662621/139747611-228031e5-52d7-4ef0-a098-b211971a9e0f.png">

<img width="857" alt="Screenshot 2021-11-01 at 22 51 09" src="https://user-images.githubusercontent.com/71662621/139747154-a17bcfc9-89a3-4978-b6a2-13c62841e3bd.png">

**Comment by frank-weinberg** [comment]
Did you extract the archive file? CRG won't run directly from the zip.
If that's not the problem, you could try opening a Terminal in the folder with CRG and running it from there. (On Linux you'd have to type "./scorebaord.sh", I assume it's the same on macOS.)
