### ISSUE TITLE
Display a resume of games in game data tab, and ability to switch

### ISSUE THREAD

**Issue by zou1312** [rollerderby/scoreboard#488]
Currently, the game data tab only displays file names and only allow to download them. To see the score (for instance) of a past game, you need to download it, then re-upload it on Scoreboard Data tab, which may seems a bit dumb. There could be a button like "Load this game" to quickly switch back to it. And maybe with that, a button to create a savefile for the current game to be sure not losing anything.

Also, a resume of score next to filename could be nice (I've just been asked what was the scores of last two games, and I was like "hm wait, how am I supposed to get that easily")(but I understand this may be a bit difficult to do, implying parsing files a calculating scores, or maybe adding a field with calculated score at the moment of saving?).

What do you think?

**Comment by frank-weinberg** [comment]
For CRG 5 I am working on functionality to allow editing (and thus viewing) of the stats/data of previous (or upcoming) games without having to load them as the current game. This should address your main request.
The current draft for the (new) games overview screen does not include scores, but I think it's worth considering if they can be added to it.

(I currently hope to have a first beta version of CRG 5 early next year and an official release at some point in that year.)

**Comment by zou1312** [comment]
Wow, I didn't even know CRG 5 was a thing, great! Thanks, I'm waiting for the beta :)
