### ISSUE TITLE
Should old logo files be removed?

### ISSUE THREAD

**Issue by rogerharkavy** [rollerderby/scoreboard#50]
See here, logos were added in 2012:

https://github.com/rollerderby/scoreboard/tree/dev/media-src/images/teamlogo

I am assuming many of these logos have either changed since they were added in 2012, and I would guess that none of them are being distributed with permission of those leagues. Should these files be removed?

**Comment by frank-weinberg** [comment]
I would say yes.

**Comment by brian-brazil** [comment]
Removing them makes sense to me.
