### ISSUE TITLE
Test 5.0-beta

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#501]
[Version 5.0-beta](https://github.com/rollerderby/scoreboard/releases/tag/v5.0-beta) has been released and needs to be tested.

**Comment by bullseye555** [comment]
Adding a few suggestions in here just as I've been playing around with it. Planning on a more extensive test later on
1. Suggest forcing a max width on logos on the scoreboard page (maybe a _resize to fit_ ?) - wide images force parts of the SBO panel off the screen

(Also, not sure how **Monster Smash** was picked up as the default image, I didn't upload it and couldn't repeat it)

![image](https://user-images.githubusercontent.com/28804763/153735487-1b099623-22f1-4605-bf10-fcb3e95f692a.png)
  
 2. Add a _Return to Index Page_ link to the ScoreBoard Data page  http://172.24.10.51:8010/settings/sb_data/
 
 3. On IGRF Page, selecting a Team assignment for a PBT, SK, etc., shouldn't automatically update the other operators **if** there is more than one other entry for that role eg: What if we have 4 PBTs? (unlikely, but still possible). Looks like entries are paired, as it doesn't change all the PBT's when one of them is updated

**Comment by bullseye555** [comment]
> (Also, not sure how Monster Smash was picked up as the default image, I didn't upload it and couldn't repeat it)
Have been able to recreate the issue
1. Fresh extract of CRG 5.0 (BETA)
2. Navigate to _Teams_ in Operator Panel
3. Add a League to Team 1
4. Add a Team to Team 1

The Team Name added at point 4 above then gets created with filename _IMAGE.PNG_ and assigned as the logo for both teams

![image](https://user-images.githubusercontent.com/28804763/153741212-2960f75e-f65f-4c45-bb5f-8dee974b3f80.png)

**Comment by frank-weinberg** [comment]
Thanks for testing & giving feedback.

> Suggest forcing a max width on logos on the scoreboard page (maybe a resize to fit ?)

They are scaled to 50px height, which works fine for actual logos. I have now added a width limit of 200px to catch logo files with unexpected aspect ratios. (The logo will be distorted instead of breaking the screen.)

> Add a Return to Index Page link to the ScoreBoard Data page

Good idea. I've added it to the other settings and data management pages as well.

> On IGRF Page, selecting a Team assignment for a PBT, SK, etc., shouldn't automatically update the other operators if there is more than one other entry for that role

Didn't think about that possibility. Good catch.

(All fixes will be in the next release which could be a second beta or an official one depending on what else is found in this one.)

> The Team Name added at point 4 above then gets created with filename IMAGE.PNG and assigned as the logo for both teams

I've tried your steps using 3 different browsers (Chrome 97, Firefox 97, Opera 83, all on Linux; fresh extract for each one) but could not reproduce this behavior. I'm also not aware of anything anywhere in the CRG code that would create a PNG file. Could this be a browser plugin interfering or something like that?

**Comment by bullseye555** [comment]
Thanks @frank-weinberg - That was only a muck around with it during a scrim, I haven't yet put it through a full-game with IGRF in/out scenario

Regarding the image, let me do some more digging to see what's happening. I was using Win11 - I'll see how it behaves on Win10 (different PC with no addons etc)
