### ISSUE TITLE
Announce v5.0.0 and forward feedback on some issues reported on Facebook

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#503]
**CRG 5.0.0 has been [released](https://github.com/rollerderby/scoreboard/releases/tag/v5.0.0).** This should be announced in the Facebook group.

Also when preparing the release I went through the public Facebook group to see if any feedback on the beta was posted there and found a couple of posts where I think I can help the OPs. Since I can't post there myself it'd be nice if these answers could be forwarded to the respective posts.

#### Color Picker Default Color ([Post by Benjamin Doyle on March 17](https://www.facebook.com/groups/derbyscoreboard/posts/4890633761018357/))

This is included in 5.0.0.

#### Operator Page not loading on Chrome v100 ([Post by Dave Almond on March 30](https://www.facebook.com/groups/derbyscoreboard/posts/4923083001106766/))

The files reported as not found have been removed going from 3.x to 4.0.0. Since it works using a different IP address I'm assuming there is a file from 3.x stuck in the browser cache and this causes the issue. If so, clearing the browser cache should resolve it.

#### Disappeared "Box" buttons ([Post by Yvonne Dietrich on April 1](https://www.facebook.com/groups/derbyscoreboard/posts/4927068467374886/))

This is intended behavior when the lineup tracking functionality is used in order to avoid wrong game data when SBO and LT try to start a box trip at about the same time, which is quite annoying to fix. There is an option in the settings to disable LT functionality which will return the buttons.

#### Missing Jam list ([Post by Ioan Wigmore on April 1](https://www.facebook.com/groups/derbyscoreboard/posts/4929261383822261/))

I managed to reproduce this by using "Start New Game" when the prior game had 0 jams. Reloading the screen consistently fixed the problem for me.
Since 5.0.0 forces a reload whenever a new game is started, the problem should not occur there.

#### Keybindings not disabled on other tabs ([Post by Carina Gerry on March 16](https://www.facebook.com/groups/derbyscoreboard/posts/4886098571471876/))

This bug is fixed in 5.0.0. (It was present since 4.1.1 - I'm surprised it wasn't noticed earlier.)

**Comment by JeneralPain** [comment]
Done and posted into FB.

**Comment by JeneralPain** [comment]
FROM FB Comments
Question re: WFTDA compliant offset, it says it can be disabled, does this just disable the offset dialogue or does it allow editing of older jams?

**Comment by frank-weinberg** [comment]
Editing older jams is always possible and the dialogue is always available.
The rule controls if editing older jams automatically adds an OS offset or not.
(I'll see if I can make the wording in the Wiki clearer.)

**Comment by JeneralPain** [comment]
Another bug/question:
I may have found a bug/issue with the V5.0 "Download ScoreBoard JSON" options :
I can only succed to download the "All-Data".
If i try to download "All-Teams", "All Rulesets" "All Games" or "Selected Element" (after having selected something) nothing happen 😕...

**Comment by frank-weinberg** [comment]
I have identified the source of this bug and a fix will be in 5.0.1.
(ETA for that version: In 1-3 weeks. I just want to wait a bit if any other issues come up so we don't get too many releases in short succession.)

**Comment by JeneralPain** [comment]
Question: Okay, this may be a dumb question, but when does the statsbook get built? I ended a game prematurely and when I click on "download statsbook", I keep getting a "failed" no file and when I go to the File management area, I do not see a game file under xlsx area. Is it because I have to complete a full game for the file to be built?

**Comment by frank-weinberg** [comment]
From the [Change notes in the wiki](https://github.com/rollerderby/scoreboard/wiki/Changes-in-Version-5#igrf-tab):

* The statsbook file will only be generated on manual updates and only if a blank WFTDA statsbook has been set up.
  * In order to generate statsbooks you have to download a blank copy of the January 2019 version of the WFTDA statsbook (US letter and A4 both work) and tell CRG where to find it in the settings tab/page.
    * If you put the statsbook file in the base folder of your CRG installation you can simply enter the filename in the setting. If it is in a subfolder you have to give a relative path (without leading / or \).
  * Generating a statsbook will take some time (possibly well over a minute depending on the amount of data and your computer's speed). The "Last Updated" field will be updated after generation is complete so you can use this to check if it's done.

(Context: a manual update is when the "Update" button near the top of the IGRF tab is clicked.)
