### ISSUE TITLE
Announce v5.0.2

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#507]
[CRG 5.0.2](https://github.com/rollerderby/scoreboard/releases/tag/v5.0.2) has been released and contains a fix for a possible data corruption bug. This should be announced in the Facebook group.

**Comment by JeneralPain** [comment]
Noted, will do as soon as I’m able

**Comment by frank-weinberg** [comment]
Updated: We are at 5.0.2 now. Turns out the underlying bug from that oscillating "Time to Derby" clock was potentially rather serious.

**Comment by bullseye555** [comment]
5.0.2 announced to FB Group

I don't have rights to close this - @JeneralPain or @frank-weinberg  can you please close #507
