### ISSUE TITLE
5.0.3 released

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#510]
[CRG 5.0.3](https://github.com/rollerderby/scoreboard/releases/tag/v5.0.3) has been released. This should be announced in the Facebook group.

**Comment by JeneralPain** [comment]
This has already been done when I saw the build hit my inbox.

We've had a couple of people report in previous editions that the "Time to Derby" was jumping around whilst counting down, I can't pull the video off FB easily and as I know the source posting person, I've emailed them asking for the video so you can see the madness as it happens!

**Comment by frank-weinberg** [comment]
> This has already been done when I saw the build hit my inbox.

Thank you.

> We've had a couple of people report in previous editions that the "Time to Derby" was jumping around whilst counting down

That one has been fixed in 5.0.2.

**Comment by JeneralPain** [comment]
Thanks frank <3 your work
