### ISSUE TITLE
Bug report - edited trip not updating score

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#512]
Posting report from the Scoreboard Facebook group that reports updating a trip in the previous jam was not reflecting on the score. Scoreboard was being run on Linux Ubuntu, with CRG 5.0.03
I was unable to replicate on a Windows based machine (updating a trip from the previous jam updated the score as expected) 

I requested JSONs, and received the following comment & link 

> It happened over a couple of games today so I've put the 3 json files here: 
https://drive.google.com/drive/folders/1PUrvdiz9e9lL4eQVjz8PuH1z0G16UbVL?usp=sharing

Could someone look into this and advise, please?

**Comment by frank-weinberg** [comment]
I've just pushed 5.0.4 which should fix this issue. In essence I had checked for "last two minutes of period" OR "last period" instead of "last two minutes of period" AND "last period" to apply the stricter version of the rule.

Regarding the comment that this should be optional: It can be turned off in the ruleset (Score-> WftdaLateChangeRule).

**Comment by bullseye555** [comment]
Thanks Frank

Confirming the Rule Setting should be set to DISABLED, and that will allow
scores to be altered regardless of how far back the score is being changed?

**Comment by frank-weinberg** [comment]
Yes, setting to "Disabled" will disable OS Offsets and instead apply all changes to the total score. (And make the game non-regulation.)

**Comment by bullseye555** [comment]
O.o

I have NO idea why that only posted 20 mins ago, pretty sure I replied by email to that on the day you patched it....

**Comment by bullseye555** [comment]
Just had a thought on this. Before I raise a Feature Request - how hard would it be to, when WftdaLateChangeRule = _Enabled_, grey out (no loss of functionality, but just gives that visual representation) where can/can't be changed to actually alter the score)
EG: 
![image](https://user-images.githubusercontent.com/28804763/202432307-09f35777-6404-447f-838a-f78067757bf1.png)
So any changes here in the grey would result in an Score Offset (J1 of P2 has completed in this case, so J5P1 can't be altered)

**Comment by frank-weinberg** [comment]
It would be doable but I think doing this would be too intrusive and more confusing than helpful.

**Comment by bullseye555** [comment]
Noted - binning the idea
