### ISSUE TITLE
[BUG] Downloaded statsbook is missing Pivot-Turned-Jammer in Score and Lineups sheets

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#518]
Attached JSON (provided by Tha Doctah via the Facebook group) is not outputting the Pivot-turned-Jammer in the Score and Lineup sheets,  
[crg-dataset-2022-07-17_190831.json.txt](https://github.com/rollerderby/scoreboard/files/9130769/crg-dataset-2022-07-17_190831.json.txt)

I exported and received the same result (xlsx that I generated attached)
[STATS-2022-07-16_RedStickRollerDerby_vs_BlackRoseRollers_1.xlsx](https://github.com/rollerderby/scoreboard/files/9130770/STATS-2022-07-16_RedStickRollerDerby_vs_BlackRoseRollers_1.xlsx)

The _Sheets_ page shows the data correctly, but it's not outputting
![image](https://user-images.githubusercontent.com/28804763/179479971-28df94a4-6dfe-40cd-81d2-2b8d076ffc65.png)
![image](https://user-images.githubusercontent.com/28804763/179480058-d48f9326-5a94-4b0c-98d6-659ce9388be2.png)

~Bullseye

**Comment by frank-weinberg** [comment]
I found the bug in the code. Fix will be in the next release. (This bug is significant enough to warrant a release before the end of the month but there is one other thing I want to look into before putting it together.)

**Comment by bullseye555** [comment]
Thanks for the update, @frank-weinberg
