### ISSUE TITLE
[Feature Request] Reset and/or Copy existing games

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#529]
Initially raised on the FB group as a different issue (issue still to be verified, will then be raised as a different issue), the TL;dr:
League HNSO imported multiple games into CRG for a day/weekend. The imported game was loaded. They then face issues while operator(s) are assigning hotkeys, but accidentally starting games. It was identified that it the 'Undo Start Game' wasn't utilised before the first 'jam' finished (or the issue was attempted to be resolved in another fashion) that there was no way to re-start the game at it's original 'game not yet started' status - the only way to resolve this would have been to delete the imported game and then re-import it

The discussion and suggestion then became two fold

1. Have the ability to _Reset_ a loaded game such that any _game-data_ (Lineups, Score, Game-Time etc) were removed - eg: I want to be able to return the game to it's state that it was in right before the _Start Jam_ button was pressed to start Jam 1 of Period 1
2. Have the ability to select an existing game and _copy_ the game (Teams data, Officials Data) to a new game but with no _game-data_ - eg: If I have a scrim that happened last week between home teams, and the exact same scrim is going to be repeated this week, I want to be able to copy the previous game so I can just copy & have the game ready to go

**Comment by frank-weinberg** [comment]
1 can already be done. I was about to add it to the wiki but noticed it is already there: https://github.com/rollerderby/scoreboard/wiki/Scoreboard-Operation#unstarting-a-periodgame

2 seems like a reasonable feature to have independent of the issue that triggered this. But there are several edge cases that need to be considered, making it a bit more involved to implement and I can't predict when I'll get around to doing that.

**Comment by bullseye555** [comment]
Thanks @frank-weinberg - I think it would be useful to have a _one-stop-shop_ that did all of the **Unstart Period/Game** , but understand there may be a bit of work involved to handle things that are edge-case scenarios. 

Happy to close out point 1, and I'll pass on the wiki information

Re: point 2, it is a _nice to have_ feature, not a bug - so happy to wait on this one
