### ISSUE TITLE
Move penalty definitions into a runtime-loaded file

### ISSUE THREAD

**Issue by official-sounding** [rollerderby/scoreboard#53]
This issue tracks leftover work from #24 and #45/#52.  I am planning on working on this, but just wanted to give it visibility.

Rather than having penalty information hard-coded into ScoreBoardJSONListener, there should be a separate file that contains penalty definition information, like codes, verbal cues, etc.  This file should load when the scoreboard starts up, so that if/when verbal cues change, the file can be updated by operators without waiting for and testing a new release.

I also sort of want to rework the way penalties data is loaded into the PT sheet, but may leave it as a part of the WebSocket firehose for now.

**Comment by brian-brazil** [comment]
I believe @frank-weinberg was talking about moving this to a ruleset, which would make more sense.

**Comment by frank-weinberg** [comment]
The suggestion was not mine, but I'm in favor of it.

**Comment by brian-brazil** [comment]
It sounded like something you'd propose ;)

**Comment by official-sounding** [comment]
do you think the actual penalty codes should be in a ruleset? Or should the ruleset point to a file where the penalty codes are defined? I think the second option makes a lot of sense, but I am having trouble conceiving how the first option would fit into the ruleset editor as currently constructed.

**Comment by frank-weinberg** [comment]
With the ruleset editor as it stands now, only a seperate file is possible. This may change in future versions, in which case I would use that option.

**Comment by brian-brazil** [comment]
Could we encode it as a string value? Something like `A=High Block,B=Back Block` etc. I don't think it's a good UX to have lots of little config files lying around.

**Comment by official-sounding** [comment]
I've made a pull request for this that references a json file using the ruleset editor, and loads that json directly into the pt/pt-color pages using ajax instead of WS.
