### ISSUE TITLE
[Issue] Twitter functionality - Login issue

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#530]
Originally raised in FB Group, I have been able to recreate

When opening Twitter Controls and selectin _Login_, receiving the below error message

> Error: Twitter Exception for OAUTH_REQUEST_TOKEN: 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following). <?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
![image](https://user-images.githubusercontent.com/28804763/187341908-5ee18329-2ff5-4cc1-b0d9-a55ebe7cd93f.png)

Going to the Twitter link, it talks about restricting updates/posting limits etc, but not why there'd be an OAUTH token rejection

**Comment by JeneralPain** [comment]
I’ll need to update the oauth token and the URL

**Comment by bullseye555** [comment]
More information: Log from CRG

403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).
<?xml version='1.0' encoding='UTF-8'?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>

Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=445faac0 or
	http://www.google.co.jp/search?q=9b033aa7
TwitterException{exceptionCode=[445faac0-9b033aa7], statusCode=403, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}
        at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
        at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
        at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
        at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:115)
        at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:92)
        at twitter4j.TwitterBaseImpl.getOAuthRequestToken(TwitterBaseImpl.java:296)
        at twitter4j.AsyncTwitterImpl$152.invoke(AsyncTwitterImpl.java:2716)
        at twitter4j.AsyncTwitterImpl$AsyncTask.run(AsyncTwitterImpl.java:2973)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by frank-weinberg** [comment]
@bullseye555  Does Login with 4.1.4 still work?

**Comment by bullseye555** [comment]
@frank-weinberg - no, receive the same error with 4.1.4

![image](https://user-images.githubusercontent.com/28804763/188138568-77a93fc8-ffe6-4eec-9ebb-061654ae2cae.png)

**Comment by JeneralPain** [comment]
Will fix

Sorry it’s been a busy week and last night I was on the beers with the CTO of cloudflare and Hurricane Electric.

**Comment by JeneralPain** [comment]
Sorry I meant to do this but totally forgot.

I can update the Twitter API settings for the newer way, are we wanting this or are you wanting to completely deprecate it? As it appears the OP wants Twitter, others (including developers) are pushing for a removal.

**Comment by bullseye555** [comment]
If Twitter will still support it, we should leave it in - but I thought
Twitter was beginning to charge for API connections?

**Comment by JeneralPain** [comment]
GET /2/tweets/:id
900 requests / 15 mins
PER USER
300 requests / 15 mins
PER APP
no
GET /2/tweets
900 requests / 15 mins
PER USER
300 requests / 15 mins
PER APP
no

**Comment by JeneralPain** [comment]
Nah no charge, unless someone is pushing more than 300-900 connections per 15 minutes

**Comment by JeneralPain** [comment]
![image](https://user-images.githubusercontent.com/37295812/216800354-b3b2b69e-b43e-4cfd-ac5f-ef84e6d9c744.png)

**Comment by JeneralPain** [comment]
So basically I have granted all the above, if everyone has their own "IP RANGE" this is where it gets tricky because I'd have to add more CURI/RURL.

**Comment by bullseye555** [comment]
Closed as cancelled. See #567
