### ISSUE TITLE
Announce 5.0.7 on Facebook

### ISSUE THREAD

**Issue by frank-weinberg** [rollerderby/scoreboard#537]
Version [5.0.7](https://github.com/rollerderby/scoreboard/releases/tag/v5.0.7) has been released.

**Comment by bullseye555** [comment]
Announced

Can @frank-weinberg or @JeneralPain please close this? I don't have access to close issues that aren't my own

**Comment by frank-weinberg** [comment]
Thank you

**Comment by bullseye555** [comment]
@frank-weinberg - passing on general feedback that the users are loving the new features - the ability to upload a statsbook to import a game, and the ability to then export after the game is finished (especially with the ePLT functionality) makes creating a statsbook a breeze

(Personally, we had 3 games exported and IGRF distributed to the 3 leagues that participated in the mini-tourney yesterday and the validation & input of Official Reviews in a under an hour for all 3)

**Comment by bullseye555** [comment]
@frank-weinberg - Passing on further feedback. Keleigh was asked by Broadcast to pass on their thanks - they saw the new overlay (specifically) and other new features while at Five Nations Showcase held in the UK last month

I'm not sure if anyone else worked on the overlay, so would appreciate if you could tag anyone that did so they see the recognition
