### ISSUE TITLE
Mac App won't run in High Sierra (10.13)

### ISSUE THREAD

**Issue by chlojolo** [rollerderby/scoreboard#54]
The Mac app for the scoreboard is a Platypus wrapper around a shell script. This shell script relies on using a relative path to locate the unzipped directory, assuming that the `jar` file is in `../lib/crg-scoreboard.jar`. 

Because the scoreboard is an unsigned app, High Sierra "translocates" the app's contents to a random directory before running it as a security measure. This means that the shell script has no way to discover where the `jar` file is, and the app fails silently. 

**Workaround**:
1. Open the unzipped directory in the Finder.
2. Drag the `scoreboard-Mac.app` to the `Applications` directory via the Finder (`mv` will not work).
3. Drag the app back to the unzipped directory
4. Now the application will launch. `¯\_(ツ)_/¯`

The Mac way to solve this problem is to bundle all the needed files into the app itself. It would be pretty easy to do this with Platypus, but the scoreboard writes to some of these directories, so we'd need to know which ones. We could then write them to `~/Library` or something like that, even just using symlinks. In general it looks like it might be a good idea to separate out places that might get written to, and put them in a configurable location.

The Platypus wrapper could also be updated to prompt the user to find the `jar` file, or maybe `start.html` as proxy for the unzip folder.

At the very least, the app should probably generate a sensible error dialog with the workaround.

Finally, it looks like High Sierra doesn't resolve `localhost` as a DNS name, which causes `start.html` not to work. It would be pretty easy to ship a Mac-specific `start.html` with an updated Platypus wrapper.

**Comment by yetzt** [comment]
hint: high sierra might resolve localhost to `::1`, which is ipv6, which the scoreboard doesn't support.

**Comment by chlojolo** [comment]
No, on my Mac it was definitely not even resolving. I can’t say it’s not something idiosyncratic about my config though. I’ve never been so up on the MacOS network information layer.

**Comment by JeneralPain** [comment]
Given the release of Mojave 10.14 is this still a problem?

**Comment by tomforster** [comment]
Just tried to run it on Mojave, the .app file doesn't seem to work at all, but the executable inside the app container works ok - I don't really know much about bundling for macos but I'd guess theres something in the .plist it doesn't like. Also running from the jar directly on the command line works ok.

**Comment by brian-brazil** [comment]
We should probably drop the app, and switch to scoreboard-Linux for Mac users.

**Comment by yetzt** [comment]
i never use the app-wrapper, i've written my own shellscript, without `/usr/libexec/java_home` and `--gui`

**Comment by JeneralPain** [comment]
This has been addressed in #383 due to the way apple handles non "App Store" apps and will be fixed in the new version.
