### ISSUE TITLE
[FEATURE REQUEST] Return the Box button to SBO Panel

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#540]
There's been an explicit request for the Jammer / Pivot BOX button to be returned to the SBO Panel (along with some not so explicit ones in the past)

Current request is that it can be optional (ie, enabled/disabled via an option, with it being disabled by default)

**Comment by frank-weinberg** [comment]
Settings -> Disable "CRG Tracks Lineups".

(It's been this way since 4.1 - before that they were always visible.)

**Comment by bullseye555** [comment]
Ah-ha

Thanks!!
