### ISSUE TITLE
[FEATURE REQUEST] Broadcast overlay scale customisation

### ISSUE THREAD

**Issue by keleighshepherd** [rollerderby/scoreboard#542]
This one is mostly inspired by watching the Crime City Back-on-Track Euro Cup 22's broadcast on our TV, the overlay elements are unreadable from the sofa. I know I could go into the .css and edit things manually to be scaled bigger, but could this be incorporated into the scoreboard settings page as a quality of life feature?

**Comment by frank-weinberg** [comment]
We were actually discussing this same feature while watching the same stream in the local officials lounge. Will look into it.

**Comment by frank-weinberg** [comment]
This will be in 5.0.10
