### ISSUE TITLE
Ability to manually set "time to derby" while displaying prior scores

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#544]
In order to give the ability to show a "time to derby" while still displaying the scores for a prior game, without doing weird things to the stats, would it make sense to add a "period 4?"  The state would never be entered automatically, but the operator could manually move from "game final" to "time to derby" as the clock display, while still displaying the scores for the last game.

As a related part of the same issue, there was some discussion on the FB group of the overlay defaulting to a 60 minute countdown at the end of a game, which would be nice to either be able to configure or disable.

**Comment by frank-weinberg** [comment]
As the bug in the overlay shows, there is already a clock running during unofficial/final score. So the easiest way to get this feature is to use this clock. It already can do most of the things needed:
- It can be adjusted with the intermission clock control on the operator screen
- The initial time can be configured in the ruleset. (The last value in Intermission -> Durations)
- If "Final score" should be replaced by some other text that can be done in the settings.

So what is needed is
- A "Show clock during final score" setting (controlled by a button in end of period controls) - set per game with default off, so it has to be activated for each game.
- Make the main display show the clock when this is active
- Make the overlay hide the clock when it is not active (i.e. fix the bug that currently causes it to be displayed)
- Maybe add an option to customize the text. (I'd leave it at "Final Score" by default.)
- Document the usage in the wiki.

I might actually be able to do most of that right away.

**Comment by frank-weinberg** [comment]
Ok, it took a bit longer than anticipated but it's done and will be in 5.0.10 (no ETA yet).

**Comment by AdamSmasherDerby** [comment]
Thanks!
