### ISSUE TITLE
[FEATURE REQUEST] - Exclude specific keys from being used as Hotkeys in SBO

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#547]
We've had a feature request come through the FB Group to _stop SBOs using the spacebar as a hotkey_

My thought would be, if possible, to exclude the spacebar and any special function keys - escape, the _F_ row, printscreen, etc

If it's not possible to exclude keys, then can we add a pop-up that when someone clicks on _Edit Key Control_ (to turn it **ON**) that advises against the use of the spacebar and special function keys as they may cause errors

**Comment by frank-weinberg** [comment]
Space will be disabled as a hotkey in 5.0.10 (which I don't expect to have time to release before December).
Function keys already don't work as hotkeys.

**Comment by frank-weinberg** [comment]
And fun observation in testing: During key assignment the "Edit Key Controls" button is likely the last button pressed. So trying to assign space will cause the browser to press that button again, leaving key assignment mode as if to punish the user for trying.
