### ISSUE TITLE
[FEATURE REQUEST] - Update logic in IGRF Export for population of Skaters

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#551]
This is a two-in-one request, but they both relate to IGRF export functions

Request 1:
When rosters of >20 are submitted for games/tournaments (of which the 21st onwards skater would need to be manually populated into CRG, unless imported through JSON), apply the following logic instead of the current Top 20 Skaters
References to Bench Staff below includes the Bench Alt Captain

1. When <= 20, no change to existing logic (I'd originally suggested to the FB request that this would include Bench Staff, but I note that Bench Staff entries in CRG are already excluded)
2. When >20, exclude any entries where the flag is _Not Skating_ in Derby Numerical order until there are 20 entries
  -- eg: if there's a list of 25, 3 of which are Bench Staff, and there are 4 marked as _Not Skating_ there would be 2 of the _Not Skating_ entries removed. 25 - 3 - 2 = 20
  -- If there are insufficient _Not Skating_ entries to reduce the number of entries to 20 or below, select the top 20 remaining skaters in Derby Numerical order
  -- If there are **no** _Not Skating_ entries, select the top 20 in Derby Numerical order

Request 2:
When a skater marked as _Captain_ is Fouled Out or Expelled, do no use their entry to populate the _Captain_ in the IGRF export
Instead, use the following, in order of priority
1. If 1 skater is marked as _Alt Captain__, use them; else
2. If multiple skaters are marked as _Alt Captain_, use the first in Derby Numerical order
3. If no other skater is marked as _Captain_ or _Alt Captain_ leave the _Captain_ field on the IGRF blank

**Comment by frank-weinberg** [comment]
Ad 1: What use case does it have to keep a non-skater in the game data but not exporting them as such on the IGRF?

Ad 2: No. A fouled out or expelled Captain may still sign the IGRF. Instead of applying some wild heuristics we export the data that the user entered. It's easy enough to mark someone else as Captain if you want a different name to appear in that place.

**Comment by bullseye555** [comment]
For point 1: this is more about ensuring that that Skating skaters are reflected on the IGRF. what happens when there are more than 20 skaters listed in the Game Data? - only the top 20 get exported, regardless of their status as a skater

For point 2: we've always operated on the basis that the fouled out captain can't sign the IGRF and that it has to be the skating captain at the end of the game. If this is not the correct application (which, after a brief hunt I couldn't find anything ib the rules of statsbook manual that confirmed _either_ way), then this request can be ignored

**Comment by frank-weinberg** [comment]
Ad 1: Yes. What if there are more than 20 marked as skating? Should we start to run stats to figure out who should be exported? "Not Skating" but in the data means that the skater should be exported and marked as per the manual. People that did not skate and should not be listed on the IGRF are either Bench staff or they have nothing to do with the game in which case they can just be removed.

**Comment by bullseye555** [comment]
Agree, Bench Staff are already excluded from the export which is why I didn't mention them in the logic

For more than 20 skaters, I covered that in the original logic.
If there are more than 20 Skaters that fall in the 'Captain', 'Alt Captain', or 'Skater' category, then use the current logic which is to only export the first 20 in Derby Numerical Order

I considered checking stats to see if any could excluded as they didn't have any game time, but just because a skater doesn't have any game time doesn't mean they weren't part of the game so is not a guaranteed way to exclude them. (I also excluded it as an option due to how hard it would likely be to implement) 

In the ideal world, there's never any teams of more than 20 skaters listed, but tournaments can (and do) accept rosters of more than 20 and still enforce the 15 playing rule - excluding 'Non Skating' players is the most logical way to ensure the correct skaters are exported to the Statsbook

(games that legitimately have more than 20 skating in the game are unlikely to generate a Statsbook anyway)

**Comment by frank-weinberg** [comment]
> excluding 'Non Skating' players is the most logical way to ensure the correct skaters are exported to the Statsbook

No. The user setting up the data they way they want it exported is the most logical way to ensure the correct data is exported. Just remove the skaters that are not supposed to be on the IGRF.

**Comment by bullseye555** [comment]
> No. The user setting up the data they way they want it exported is the most logical way to ensure the correct data is exported. Just remove the skaters that are not supposed to be on the IGRF.

GIGO

The aim of the request is to remove some of the 'garbage' that was input so Operators/Head Officials etc get the most out of the software

Additionally, you've contradicted yourself here (at least, the way I'm reading it)
![image](https://user-images.githubusercontent.com/28804763/202816662-a200d290-4bbd-4424-ac9a-620695576a3e.png)

Reviewing the IGRF Manual, my interpretation is that _Not Skating_ entries **should** be on the IGRF where possible, but don't **HAVE** to be
![image](https://user-images.githubusercontent.com/28804763/202817570-87741fee-eeac-4bee-ab7d-670c15824258.png)


Would a the following implementation of the original request be simpler?
1. <=20 Skating-type entries (Non Skating, Captain, Alt Captain, Skating) - No change in existing logic
2. >20 Skating-type entries - Exclude all _Non Skating_ entries

This still covers the request made on the FB page, and comes back to the point of ensuring skaters who actually skated are on the IGRF

**Comment by frank-weinberg** [comment]
> The aim of the request is to remove some of the 'garbage' that was input so Operators/Head Officials etc get the most out of the software

The aim of this request is for the software to ignore what the user asked for because you assume to know better what they wanted. I hate it when software does that. And even worse, there is not even a straightforward way to tell it to take the request literally. That's like an autocorrect that's immediately reapplied when you undo it.

> you've contradicted yourself here

How? If you mark a skater as non-skating, they are put on the IGRF. If they are not supposed to be on the IGRF, remove them instead. What's contradictory about that?

**Comment by bullseye555** [comment]
>you've contradicted yourself here
>How? If you mark a skater as non-skating, they are put on the IGRF. If they are not supposed to be on the IGRF, remove them instead. What's contradictory about that?
My interpretation was that Non Skaters are not supposed to be in the IGRF 

So ultimately, _your_ recommendation is that when there is a roster of more than 20 skaters, we just populate the first 20 regardless of if the skater actually skated or not?
Would this not cause possible confusion when submitting the IGRF to WFTDA? [Yes - I grant that in 95% of scenarios Sanctioned games are run by officials who will have an IGRF that only has the 15 rostered skaters because either that's all the team submitted, or the relevant head official has removed some] Or to the leagues that are reviewing the exported IGRF post game? "Oh - Skater 9999 played, but they're not on the IGRF? But they're on the LT/SK pages but they're marked as Red? What does that mean? And why is skater 013 on the IGRF when they didn't play?" [again, there will be a large range where 013 would have just been removed from the Gamedata as a skater in the first place, but this isn't every scenario]

>The aim of this request is for the software to ignore what the user asked for because you assume to know better what they wanted. I hate it when software does that. And even worse, there is not even a straightforward way to tell it to take the request literally. That's like an autocorrect that's immediately reapplied when you undo it.
Could we do a setting [within the IGRF page], where the options are "Export All Skaters" [Default, current logic - Top 20 regardless of Skating/Not Skating status], "Export only Active Skaters" [Skating skaters only], "Export Skaters to fill IGRF" [Using the logic requested above]

I'm trying to reach a middle ground here, where the request from the users can be implemented in a way that is practical

**Comment by JeneralPain** [comment]
I think what is important here, a team during a multiday tournament prior to the event (even the first whistle), will submit a crew of 20-25 people, but they may only select 15 to play in any one game. So we need to be adaptable to change(s) in a roster. Why "remove the whole person" when we can use the feature to set it to "non skating" which then removes them from the IGRF.

The point here is, why have a feature to select "captain". "non skating", if we're not even going to use the feature to its full capability.

**Comment by frank-weinberg** [comment]
> Would this not cause possible confusion when submitting the IGRF to WFTDA?

No. For a sanctioned game listing anybody who is not on the Charter invalidates the IGRF/statsbook. And a charter is limited to 20 skaters. That's why there are exactly 20 rows. [And around Europe people are trained to always list the full charter with non-skating people marked as described in the manual.]

>  [again, there will be a large range where 013 would have just been removed from the Gamedata as a skater in the first place, but this isn't every scenario]

You still have not given a single scenario where it is useful to keep a skater in the game data that did not play and is not supposed to be listed anywhere.

>  Why "remove the whole person" when we can use the feature to set it to "non skating" which then removes them from the IGRF.

Because the non-skating flag means: "Don't show this skater on in-game screens but list them on the IGRF."

If there is really that much need for a flag that means "don't show this skater anywhere, ever" it could be added. But I want to see a scenario where such a skater can't just be removed completely.

**Comment by bullseye555** [comment]
Closing because there is a clear bias against the request and it won't be completed.

**Comment by bullseye555** [comment]
Closing because there is a clear bias against the request and it won't be completed.

**Comment by bullseye555** [comment]
Closing because there is a clear bias against the request and it won't be completed.

**Comment by bullseye555** [comment]
@frank-weinberg or @JeneralPain - please close this as _Close as not planned_

it won't let me do it

![image](https://user-images.githubusercontent.com/28804763/202848325-b3a800ab-a659-4a8f-a1a3-1ee831946e3d.png)
