### ISSUE TITLE
[FEATURE REQUEST] - Official Review Entry screen

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#552]
Creation of an OR Entry screen

My thoughts on design/function:
- Screen is accessible from the Index Page, under the _Inputs_ box
- When opening page, requires official name to be entered
   -- Similar to Feature Request in #550 , this should not accept a _blank_ entry, and should update into IGRF if the official doesn't already exist (suggest default Role as _Non-Skating Alternate_ )
- Page would display the official name at the top of the screen (again, same as #550) , with header rows but no others (similar to PT/LT/PLT when there are no skaters entered)
![image](https://user-images.githubusercontent.com/28804763/202426336-bedf8982-dfe5-4918-8dbb-71dfaf9691da.png)
- Operates similar to PT/LT/PLT/SK screens, in that when an OR type Timeout begins on the SBO, it creates the "row" - columns 1 to 4 containing **Team/Jam Number/Period Clock/Length of Review**; Column 5 for **Details**, Column 6 for **Result**, Column 7 for **Keep Review**
- Uses CRG Data to populate the _Team_ [Team that called the OR, this should be a drop-down to alter the team if the SBO selects the wrong team], _Jam Number_ [Current Jam Number], _Period Clock_ [What the Period Clock was at when the OR time out was started], _Length of Review_ [Length of OR Timeout - this would count up while still in OR, and then remain static after the OR clock stops ; or is blank until the OR clock stops], and _Keep Review_ [Uses Retained flag from SBO, but can toggle the Retained status, in the same way _SP_ functions in the LT/PLT screens - _Retained_ being flagged as kept would be green ]
![image](https://user-images.githubusercontent.com/28804763/202424649-f56eb8e7-daf3-4188-94f6-551b8628b16b.png)
- **Details** and **Result** are both tap-to-edit fields that open a popup containing the text field for entry (text box should auto-expand vertically, the same way the text boxes in GitHub expand when text is longer than the default textbox size; ideally the popup never expands past the screen size, so that the "close" option is available without having to scroll the whole screen
![image](https://user-images.githubusercontent.com/28804763/202428193-c5a95ab7-3133-4947-aa78-aa1d5d8512ca.png)
![image](https://user-images.githubusercontent.com/28804763/202428385-751a7fc5-088b-4ebd-92b9-9dd8715de688.png)
![image](https://user-images.githubusercontent.com/28804763/202428449-9cd0039f-5d38-4b26-9cba-489bf30a2e5e.png)

**Comment by frank-weinberg** [comment]
For sanctioned games ORs have to be  submitted as a scan/photo of the filled sheet. They do not have to be entered into the statsbook (and around here they usually aren't).
Thus I believe the situations where entering them digitally is more convenient than just filling out the paperwork are not common enough to warrant the effort of implementing such a screen.

If someone else feels different, I'm open to including a contributed screen.

**Comment by bullseye555** [comment]
As I'm not part of a WFTDA league, I've never had to submit paperwork for sanction before.

OR paperwork is generally transcribed into the statsbook down here when it's distributed post game (noting that Aus doesn't have very many sanctioned games, so this is a more common practice), so having somewhere to enter them directly for non Sanctioned game play would be useful
