### ISSUE TITLE
[BUG REPORT] - Unable to paste team into Custom Team

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#553]
This was raised by Wheels Bohr in the FB group, and I've been able to reproduce on Windows 11 & Chrome

When attempting to paste a team from Excel (or similar), if the team is _Custom Team_, CRG won't accept the paste - however if changing to a preloaded team (such as the existing _Black_ or _White_ teams) it pastes with no issue

I've identified this **only** occurs when _Start an adhoc game_ is used and one [doesn't make a difference if it's **Team 1** or **Team 2**] or both of the teams are _New Team_
![image](https://user-images.githubusercontent.com/28804763/202886521-ae793832-b02b-40ad-8fde-172856cd0010.png)

I've also confirmed that if, while in the _Teams_ tab, the team drop-down is changed from _Custom Team_ to any existing team and then reverted to _Custom Team_ the paste functionality works without issue

**Comment by frank-weinberg** [comment]
Will look into as I find time. (And this gets higher priority than any feature request.)
