### ISSUE TITLE
[FEATURE REQUEST] - Hint for Missing Blank Statsbook

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#555]
Hi,
I ran into an issue with a prepared game-statsbook file lately with a fresh and clean CRG installation.
I hadn't put the blank stats.xlsx into the root folder and tried to import a prepared game in the [Games / Teams / Rulesets] Tab via the import Statsbook dialog. Importing it there didn't do anything. 

It took me some time to find out that I had to copy the blank statsbook into the root folder and put the name of the file in the setting section.

After doing this the imported game showed up in the game Data tab.

So maybe it would be nice to have a sort of error message or hint message when trying to import a game without having specified the blank stats file before. Also having a import file dialog like in the Games Tab would be nice instead of only having the input field in the settings-section

Maybe it's also something wich could be checked when using the Scoreboard the first time. For example an dialog that ask to import a blank stats file. This could be dismissed if not wanted and maybe the decision remembered.

Thanks for all the work!
REFlex

**Comment by frank-weinberg** [comment]
Importing does not require a blank statsbook. Something else must have gone wrong there.

**Comment by bullseye555** [comment]
@reflexdd  - it does sometimes take a minute or two for the IGRF to process in (I learnt this the hard way one day - I imported the same file 5 times before it appeared in the Games section, which resulted in Officials and Players listed 5 times... That was a fun time removing the duplicates (quituplates?)

**Comment by reflexdd** [comment]
Ahh... ok I see the same behavior here now. Ok so then some indication would be nice to have for this situation. And with this imported game the Stats file could also be written or does it need the blank statsbook?

**Comment by bullseye555** [comment]
I'll let Frank advise on the indication of upload, but yes - you need the blank statsbook to be able to export

**Comment by reflexdd** [comment]
also the indication for the missing blank statsbook would be nice to have because people might think they imported the statsbook already and expect to get a statsbook from this after the game.

**Comment by frank-weinberg** [comment]
Indication for missing blank statsbook is there since 5.0.7.
Spinner while import/export is in progress will be in 5.0.10.
