### ISSUE TITLE
Order issue of jams in overlay points per jam

### ISSUE THREAD

**Issue by tikismoke** [rollerderby/scoreboard#556]
Looks like jam order is not correctly displayed in overlay point per jam view.
Using last version V 5.0.9, jam order in overlay looks like it's order like player number :
jam 1, jam10, jam11, jam2, jam3.
Instead of jam 1 to 9 then 10.

Also is it possible to display directly the jam number IE on the separation line.

Thank's :)

**Comment by aoanla** [comment]
Yeah, on a quick check of the overlay code js, the "jam" field for that view has its "data-sort" field set to the jam number unmodified - and the javascript that sorts things like that is explicitly a string sort (so "10" sorts before "2"). 

https://github.com/rollerderby/scoreboard/blob/dev/html/views/overlay/index.js  [at the top for the sort function]

This might be solved by just changing the data-sort attribute to use left-zero-padded integers?

**Comment by aoanla** [comment]
PR https://github.com/rollerderby/scoreboard/pull/559 should fix this, if Speedy agrees?
