### ISSUE TITLE
[BUG REPORT] NaN in SK sheet after a jam deletion

### ISSUE THREAD

**Issue by Togimaro** [rollerderby/scoreboard#558]
During a game yesterday we came across a weird issue where a line in the SK sheet appeared as NaN (cf screenshot).
I wasn't SBO on this game so I don't have a clear repro step unfortunately (all I know is that a previous trip was wrongfully deleted during a jam with a SP), I have a backup file (linked below), but when I load it back into CRG the issue is not present...
The issue appears during the Current game (`82807b10-d55b-450c-8b58-49afb944dcdf`), 1st Period, Jam 14 for the Team 1. From the looks of it, `ScoreBoard.CurrentGame.Period(1).Jam(14).TeamJam(1)` is suspiciously missing and I don't know how it can be the case and if it is related to the issue.

Version: 5.0.9 (latest)

Backup file: https://drive.google.com/file/d/1Ldv8fch9Thz1Kio4pEoAVTW1f1UK1PLf

(Sorry for the bad screenshot, it was quite a rush and I thought the backup could be used to reproduce the issue...)
![Screenshot of the issue](https://user-images.githubusercontent.com/10451936/205651650-9e6c891c-3398-43e4-8d65-cfcdda33948d.jpg)

**Comment by frank-weinberg** [comment]
That red dot makes me think the bug may have to do with the OS offset code. Do you happen to know if the trip was deleted after the end of Jam 15?

I'll have a deeper look into this as I find time. Unfortunately that might only be a few weeks from now.

**Comment by bullseye555** [comment]
@frank-weinberg - I had a quick look and can advise the following:

1. Loaded the JSON, which started the game midway through the halftime intermission
2. Jam 14 for team 1 is showing as **0** jam points and **0** period points
![image](https://user-images.githubusercontent.com/28804763/205863328-d9833ace-12ea-4d6b-b7de-d0cd506fd77f.png)
3. The JSON is missing the entire dataset for Team 1 for Jam 14 [eg: there is no _ScoreBoard.CurrentGame.Period(1).Jam(14).TeamJam(**1**)_
![image](https://user-images.githubusercontent.com/28804763/205863585-0b0de293-233d-4b87-b16f-68bae9b002df.png)
4. I'm unable to start a new game - I submit the request, but do not get any option to _Go to Current Game_
https://user-images.githubusercontent.com/28804763/205864217-489464a0-6535-422c-9f87-48171f5f7239.mp4
5. Noted a large list of errors in the Java window (the File errors I expected...)
[javaerrors.txt](https://github.com/rollerderby/scoreboard/files/10164432/javaerrors.txt)
6. After removing gamedata, AutoSaves, and restarting CRG I was able to create a new game
7. Unable to recreate issue using your suggestion of removing trips to trigger an OS Offset - CRG behaves as expected

**Comment by Togimaro** [comment]
> That red dot makes me think the bug may have to do with the OS offset code. Do you happen to know if the trip was deleted after the end of Jam 15?
> 
> I'll have a deeper look into this as I find time. Unfortunately that might only be a few weeks from now.

I watched the replay of the game and apparently it wasn't just a trip deletion but a jam deletion:
- The jam 15 was started but called-off immediately by the official for delay of game
- The SBO wanted to delete the jam 15 but deleted the jam 14 and the 20 points attached to it somehow (I don't know if it's user or software error)
- He didn't see the issue right away and a new jam 15 was launched
- I think he tried to reinsert a jam 14 with the missing points and triggered the issue but I'm not really sure on this
- OTO at the end of jam 15, I took the photo at this moment

**Comment by frank-weinberg** [comment]
Thanks for that description @Togimaro . Together with the data file it allowed me to reproduce the issue: If on deleting a Jam with a Star Pass the TeamJam with the SP is deleted second, the deletion will crash and leave a semi-deleted Jam behind, causing the symptoms you saw.

Given that 
a) there may be other issues lurking that trigger when deleting a Jam with some combination of data
b) I can't think of any scenario where you'd want to delete a Jam that has either points or a SP
I'll address this by disallowing the deletion of such Jams. Even without the bug that deletion would have interfered with the game significantly. And if anybody ever comes across a scenario where they do need to delete such a Jam, they can remove points and/or SP first and delete the Jam afterwards.
