### ISSUE TITLE
Bug? - Lead jammer still flashes on stream overlay after lost lead

### ISSUE THREAD

**Issue by AmyFeralFouler** [rollerderby/scoreboard#564]
It appears that lead is not removed from the stream overlay when a jammer gets a penalty and loses lead.  Several examples can be found in this replay of a RCR game.

Specific example at 34:39 mark of this video:
https://youtu.be/IPKztAq-2Kk?t=2081

![image](https://user-images.githubusercontent.com/63978266/215345948-9b34495c-4cc5-43ab-982f-4a01a10fa236.png)

CRG version: 5.0.9

**Comment by frank-weinberg** [comment]
Indeed a bug. Fix will be in 5.0.10, which should be out soon.
