### ISSUE TITLE
FEATURE DEPRICATION? TWITTER 

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#567]
With Twitter introducing a cost for API access, will this impact the Twitter functionality? And if so, should removal of the feature be considered?

**Comment by frank-weinberg** [comment]
Given that we have a "Twitter login is broken" ticket that's open since August (#530), I guess this will not impact functionality right now.
But if fixing the feature now requires payment then removal is probably the way to go.

**Comment by bullseye555** [comment]
Agree - Happy to close #530 and remove the twitter functionality all together

**Comment by The--Captain** [comment]
Agreed.  It was fun while it lasted, but no way anyone is going to pay Phony Stark for the priv

**Comment by JeneralPain** [comment]
Twitter Login isn't broken, and I've got access to the backend.

Would need more details on "what is broken" ?

**Comment by frank-weinberg** [comment]
If Twitter functionality is working, please close this ticket and #530.
If it isn't working due to the API being closed, close #530 and turn this into an explicit task to remove the functionality.
If it isn't working due to #530 only, close this ticket.

**Comment by xrobau** [comment]
I own the rollerder.by domain - I think the best idea is to just give up on twitter and I can spin up a Mastodon instance there that can be used.

**Comment by bullseye555** [comment]
@JeneralPain 
![image](https://user-images.githubusercontent.com/28804763/226160952-e11d715a-4103-4f9f-997f-ed5a0fda63ae.png)
Twitter themselves have said they won't support it for free any longer, and all reports I've seen say that the minimum tier cost is going to be $100/month (I'm assuming USD, too)

But this contradicts what they currently have on the API Portal, which in itself is a contradiction (in once sentence it's _Free_ and in another part the cost is _TBD_
![image](https://user-images.githubusercontent.com/28804763/226161071-f56c96a3-3873-478d-a859-4825aa30dbde.png)

In regards to #530 @frank-weinberg , if immediate question for me is what version of the Twitter API based on? 
If it's not v2 (and not easy to convert to v2) then we ditch Twitter functionality
If it's not v2 but easy to convert or is already v2, then I think we need to wait until Twitter announces what their _Essential_ level access will be (Free or Paid) - once we have the answer to this, we can proceed with depreciation (if paid) or change to v2 (if free)

@xrobau would it be worthwhile seeing what the interest is in having that available on Mastadon and possibly having an integration anyway? And what about people that don't have an account on rollerder.by but on a different server, would they still be able to take advantage of the API to post to their own accounts?

**Comment by frank-weinberg** [comment]
The library we are using is v1.1 only and hardwired to twitter. Finding and migrating to a different library is more effort than seems worthwhile to me given that almost nobody appears to be using this feature. But if somebody else wants to put in the effort to migrate to Twitter v2 or Mastodon, I won't block integration.

**Comment by JeneralPain** [comment]
Yeah, I think you're right here Frank.

tbh the uplift for the benefit is too high.

I don't know anyone who uses the Twitter function, that said, it doesn't
mean its not used.

**Comment by bullseye555** [comment]
Concur.

I'll close #530 and this depreciation can proceed.

Future integrations to Twitter v2 or other platforms can be a new request as the demand arises
