### ISSUE TITLE
Announcer view

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#569]
As an announcer for bouts, I would like a read-only view so that I can properly announce team rosters and also as a reference for in-game announcements.

**Comment by frank-weinberg** [comment]
Can you be more specific as to what information you would want on such a screen? Do you maybe even have an idea of how it should/could look?

**Comment by atkinsonm** [comment]
A basic version would look similar to the teams view in the scoreboard operator tab (screenshot), but read only. It would source from the same game data.

A read-only version of this exact tab available on its own view path (e.g. localhost:8000/views/roster). It could be names the roster view and available for anyone who wants to look up the skaters/numbers/positions, but my use case would be for the announcer.

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/3342243/218331481-aa729ad8-3557-4e5e-9686-bce67f83c9dd.png">

I can work on a mockup as a custom screen.

**Comment by frank-weinberg** [comment]
I think I get the idea.

> I can work on a mockup as a custom screen.

If you can provide code (ideally as a PR), I'll happily include it or use it as a starting point.
Otherwise Ill see when I have time to do it myself.
