### ISSUE TITLE
Increasing lag by the end of the game.

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#57]
Multiple WFTDA tournaments have reported that the clocks have been lagging to a greater and greater degree over the course of a game.  By the end of the second half, lag can accumulate up to as much as several seconds.  This is obviously a critical issue for a piece of timing software.  I'll attach reports below from several tournaments.

It appears that throwing CPU speed at the problem is presently the only thing that improves the situation.

### Udder Chaos

Running CRG on an i5 laptop, scoreboard operator is on the same computer.  This computer is dedicated to CRG - it has nothing else installed (running Win 10).

The overlay computer and the scoreboard projection computer are both remote and show lag.

Also have 4 computers showing the electronic whiteboard.  

Restarting CRG before each game, clearing the chrome cache at the same time as the restart.

The CRG scoreboard is lagging.
It doesn't lose time on the game clock, but it doesn't start the lineup clock until after it finishes lagging.

This is adding from 2-11 seconds to lineup times.

-

First half nearly over with CRG on Linux Mint, issue is still present. What we are seeing that is the most concerning is that after a jam ends, it takes progressively longer for the lineup clock to start. We've been keeping track, and it's between 45 second and 2 minutes of game time that is run off the clock that shouldn't be - this could definitely have an effect on the outcome of a game. 

Previous game we tried only loading in the two teams we were using, no change in the behavior.

-

The last game on Windows and this game on Linux both lost 45 seconds of game time due to the lineup clock not starting - so Mint definitely isn't the magic bullet.

-

For our first game today we used a Linux Mint live USB to boot a core i7 box with 24 gb ram (retail price US$1899 for this machine). Things were pretty good until the 20 to 25 minute mark of the second half, where we started losing about 2 seconds after each jam for 75% of jams. 

Still not great, but at least we're not losing 2 minutes a game.

Also have projector, overlay, and operators computers all running separately (plus the 3 whiteboards).

-

One more note, on the i7 box we are seeing CPU usage spike to ~60% as a jam ends, when the lineup clock is supposed to start (on the core2 duo we tried first it would spike to 90%). After the CPU usage drops back down, the clocks are good.

### Euroclash

Setup: CRG 3.9.3a running on Linux Mint 18.3, i7 8gb ram laptop, connected by ethernet to the private network, and to the projector. There are digital whiteboard displays in both team benches, the penalty box, THOs table, and announcer table.

Issues:
 - I had similar issues with the digital whiteboards as Jon reported at the Big O, spaces on the display where penalties weren't; penalties disappearing; and something happened to the system whilst I was on a break, that "fixed itself" and no one will give me specifics about!
 - Lag: the lag curve was constant throughout the day, starting out unnoticeable and exponentially getting more laggy towards the middle of the second period where it seems to level out at around 2 seconds of lag. THOs and crew heads happy that this is an acceptable amount of lag.
 ○ Steps taken to deal with the lag included going to the JSON scoreboard display which has a bug where banner ads aren't being displayed (no change); and restarting the entire scoreboard server machine before the final game of the day (big change). I am planning on including this in the order of operations before starting a new game (current procedure being at the end of the game to kill the app, restart it and then use "Start New Game")

From personal testing the load is on the cpu, not necessarily the ram capacity (but more cannot hurt!)

**Comment by JeneralPain** [comment]
The penalty data is already a known issue under #47

**Comment by JeneralPain** [comment]
Reading this report and looking at the issues, what we are now seeing is CRG being used more and more heavily. 

So we look at this from a perspective of:
SCOREBOARD CONTROLLER > Operated by SBO
|
> multiple penalty displays
|
> Penalty input from an tablet* device
|
> scoreboard display head

EDIT: Further discussion discounts my USBv2 theory.

I might need to pull out my C2D and see if I can try and replicate this in greater detail.

**Comment by JeneralPain** [comment]
I guess the whole "Start new game by reboot" really adds a lot of unnecessary time, especially resetting up the display heads etc... so this is **URGENT**

**Comment by JeneralPain** [comment]
Team, we're really close to a build with this fixed in it. :) Please bear with us.

**Comment by brian-brazil** [comment]
This can be closed with #59
