### ISSUE TITLE
Overlay marker for lead jammer

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#572]
The overlay view does not show who is the lead jammer. I would like a similar function like the main scoreboard which flashes the name of the lead jammer in a different color. I thought it used to but it does not seem to now. Not sure if this is a bug or a feature request.

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/3342243/218593253-b35883e1-ba81-4df3-bbfd-2b589ba606e5.png">

In screenshot, note that jammer "test" is lead in the operator panel and flashing red on the main scoreboard, but has no indication of lead in the overlay.

**Comment by JeneralPain** [comment]
On the one you’re using, it’s indicated by the star.Sent from my iPhoneOn 14 Feb 2023, at 9:58 am, Michael Atkinson ***@***.***> wrote:﻿
The overlay view does not show who is the lead jammer. I would like a similar function like the main scoreboard which flashes the name of the lead jammer in a different color. I thought it used to but it does not seem to.

In screenshot, note that jammer "test" is lead in the operator panel and flashing red on the main scoreboard, but has no indication of lead in the overlay.

**Comment by reflexdd** [comment]
True, in the simple version it’s only the star on the left side indicating lead.
If you have switched on EPLT, than the behavior is like on the scoreboard.

**Comment by frank-weinberg** [comment]
Just checked with 5.0.10 - If I activate lineups in the overlay, there is no indicator on the left and the Lead Jammer flashes, if I deactivate lineups (as you have) there is an indicator on the left and no flashing. That should probably be made consistent.

**Comment by atkinsonm** [comment]
Oh I see, the star is next to the team name. That's good enough for me. Maybe I had different settings at one time or the behavior was different in v4. Good to close IMO but feel free to keep open if you want to change the behavior.
