### ISSUE TITLE
[FEATURE REQUEST] - Migration functionality

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#574]
I have a powershell script that I've written that will move all the images, AutoSave files, statsbooks, custom penalties/rulessets, etc from a previous version of CRG (eg 5.0.9) and place it in a destination folder (which will be the new version, eg 5.0.10)

But while the logo's etc auto "import", I'm finding that even though CRG is loading the most recent autosave from the previous version, nothing that needs importing (eg from a JSON) is being carried over.

What I'd like is an option on the _Data / Teams / Rulesets_ page where you can select the CRG Parent folder (EG: **D:\CRG\CRG5.0.9** - where scoreboard-Windows.exe is) and have it import the following:

1. Folder: html\images
2. Folder: html\custom (where it's not part of the base "custom" set)
3. Files: *.xlsx (ideally maintaining folder trees) [assumes user has a blank statsbook loaded somewhere, and has exported previous games as a Statsbook]
  -- This also, ideally, includes pre-populating the Blank Statsbook field with the same value as that in the source version
4. Files: *.json (excluding any core CRG JSONs, again ideally maintaining folder trees) [assumes user has exported previous games or other data as a JSON]
5. Data: Import _Games_, _Teams_, _Rulesets_ etc {essentially, perform the _Download All Data_ on the source version, and then upload that into the new scoreboard

If this was easier to have both scoreboards running, and to perform the migration, you connect the "new" scoreboard at (for example) port 8001 to the "old" scoreboard at (for example) 8000 that would be ok too - open to suggestions on how best to complete something like this [the idea is that it saves users time in have to "reconfigure" everything each time there's a version change]

**Comment by frank-weinberg** [comment]
I just stumbled over your sentence

> even though CRG is loading the most recent autosave from the previous version, nothing that needs importing (eg from a JSON) is being carried over.

and am confused. Are you saying that games, teams, rulesets, operator settings, etc are not showing up in the new version despite the autosave which contains them being loaded without error? That would be very surprising.

**Comment by bullseye555** [comment]
Thanks @frank-weinberg - apologies I never got back to you on the above, I wanted to do some testing before responding (to validate) and Life was just a tad busy the last few days (I was going to do it today and get back to you... )

**Comment by bullseye555** [comment]
@frank-weinberg - just confirming if this should be able to be started on a different port **and** set the import folder? 
Ignoring the fact this is trying to start on the default port of 8000, I'm getting the below errors 
 
![image](https://user-images.githubusercontent.com/28804763/229333389-b0648fee-6e75-47d1-a2a5-041394310153.png)

I've tested and confirmed alternative ports don't work either, and removing the **--import** option starts CRG at the port set and vice-versa where **--port** is removed, it will process the import

If this is expected functionality, that's all good - just wanting to confirm

**Comment by frank-weinberg** [comment]
Does it work for other combinations of two command line parameters, e.g. "--host=localhost --port=8000"? This looks like something involved has trouble with multiple arguments being specified. And the FullyQualifiedErrorId points at Powershell.

**Comment by bullseye555** [comment]
Looks to be how it's triggered from powershell

CMD works fine
![image](https://user-images.githubusercontent.com/28804763/229381473-2783130d-4b97-4f55-88a3-d401f7f7b9f2.png)

Running in powershell as **.\scoreboard-Windows.exe --port=8002 --host=localhost** works without issue, but using **start scoreboard-Windows.exe  --port=8002 --host=localhost**
![image](https://user-images.githubusercontent.com/28804763/229381623-01299ad6-530a-4ea4-84c4-f5069f39f63d.png)

Happy to close this off (not that it was opened... lol)
