### ISSUE TITLE
Suggestion to give a hint for Color Labels

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#576]
Hi,

lately I've seen more and more, that people are struggling when setting up Teamcolors. From my impression it's not clear to them that "Foreground" means Font-Color or Object-Color. 

Is see that finding a better description for this is not that easy, but maybe we could give Users some kind of hint when hovering over Foreground / Background etc.

Any thoughts on this?

**Comment by JeneralPain** [comment]
Where are these colors being applied? 

Are you wanting them on the publicly visible scoreboard we'd throw on a projector or elsewhere?

**Comment by reflexdd** [comment]
These colors are applied either in the Scoreboard Control-Section/Teams, Game-Date/Team-Section or in the Overlay-Admin-Section.

<img width="911" alt="screen1" src="https://user-images.githubusercontent.com/58275718/224298709-7884f3e8-8277-46d9-8397-81962611dbb7.png">

I find the wording Foreground difficult, when mostly people are trying to change the Font Color.

<img width="656" alt="screen2" src="https://user-images.githubusercontent.com/58275718/224299056-90053397-e606-41df-a5f3-49ff145d9477.png">

I hope it get's now more clear what i mean :)

**Comment by JeneralPain** [comment]
Yep I'm with you now, I might have a tinker tomorrow during some downtime
or possibly through the next few nights when I'm bored at work.
