### ISSUE TITLE
[Feature Request] Import Button for Blank Statsbook File

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#578]
I don't know if this technically works with the scoreboard/programming Structure but could we give people the opportunity to import a blank statsbook file via a simple import button. This sheet would then be copied in the root-Folder of the scoreboard.

I know that the explanation on how to import a blank statsbook is now described in the wiki, but maybe we could improve this or give people at least a hint in the Settings-page on what to do there.

**Comment by atkinsonm** [comment]
Seems reasonable to me. It would just provide a nicer user experience to import a file versus typing the relative path and manually placing it there.

I'd even consider a step further; if I don't have a blank statsbook, grab it from the WFTDA site (for example) for me.

**Comment by bullseye555** [comment]
My only argument against just automatically grabbing one from WFTDA is that some of us use the A4 template, and not the Letter one

**Comment by atkinsonm** [comment]
Fair point. A UI for the upload seems straightforward and non-conflicting though.
