### ISSUE TITLE
JRDA jam continuation rule glitch

### ISSUE THREAD

**Issue by MischiefManagerNSO** [rollerderby/scoreboard#579]
There is a small but important glitch to the new update that allows for the new JRDA rule that allows a jam to continue. I noticed this weekend that when continuation was used, it continued the jam time correctly, but added to the jam number. For example, jam 14 was called for injury and then continues with 1:34 left. When the clock restarted, it showed jam 15 with 1:34 left.

**Comment by bullseye555** [comment]
@MischiefManagerNSO - This isn't a bug, this is expected behaviour

Please see the thread in #563 - specifically here https://github.com/rollerderby/scoreboard/issues/563#issuecomment-1382862274 and the comment immediately after it

**Comment by frank-weinberg** [comment]
This is also documented on the wiki and in the release notes as something that's very difficult to fix and will thus unfortunately not change soon.
