### ISSUE TITLE
[FEATURE REQUEST] - Include button to Download Operator settings only

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#580]
As per comments made in the FB Group, there is a functionality request to include a Download Operators button

**Comment by bullseye555** [comment]
@frank-weinberg - it's been raised (and confirmed) that just clicking on the Download button for the item-level only opens the JSON in a new window. 

This is a change in behaviour - the 2x _Download_ buttons at the top (_Download Selected_ and _Download All_) both function as expected, but the item-level 

Screenshot: _Download All_ working as expected
![image](https://user-images.githubusercontent.com/28804763/229333973-cabc9b99-c7d9-413b-87a6-3fe22eeec0d7.png)

![image](https://user-images.githubusercontent.com/28804763/229334013-ea81c2dd-0b4f-4181-80b1-9fe826cffc03.png)
Clicking on _Download_ opens the hyperlink in the same window
![image](https://user-images.githubusercontent.com/28804763/229334055-1f436a37-4cbd-4702-a396-9ed822f291ec.png)


There is a workaround, which is to right-click and selected _Save Link As_, but as above the current behaviour doesn't match with the expected behaviour (I know it was working as expected when I did the Operator download - so maybe something part of #583 ? )

**Comment by frank-weinberg** [comment]
There is a flag you can add to a hyperlink so the linked content is saved by default. I just forgot to add that to the single file download buttons. Will be fixed in the next release.
