### ISSUE TITLE
[BUG REPORT] - Auto End Team Timeouts end Official Reviews too

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#586]
Reported on Facebook by Wheels. Bug found by Busta at BOTAS

When setting _Auto End Team Timeouts_ = TRUE this also ends Official Reviews after 1 min

I've validated this on 5.0.10 and also confirmed this does NOT occur with OTO's

**Comment by frank-weinberg** [comment]
Oops.
So apparently nobody ever used this feature until this weekend.
Should be an easy fix at least.
