### ISSUE TITLE
:bug: Scoreboard froze during game 10 of Clover Cup

### ISSUE THREAD

**Issue by UKillLele** [rollerderby/scoreboard#602]
It may also be relevant to note that the scoreboard froze at the Y'AllStars tournament as well but I don't have details on that issue.

Reported by Roslambo at Dallas Derby Devils:

During the final game on Saturday (April 1, 2023, day 2/3 of the tournament), with 2:25 left in the 2nd period, all of the clocks froze and CRG was not taking inputs from the scoreboard operator. 
* CPU was at 100% usage per Task Manager
* used CRG 5.0.11 and Microsoft Edge
* ran a remote proxy for Quad Media

**Comment by JeneralPain** [comment]
Can I ask, did you keep a copy of the folder (entire scoreboard)? If yes, can you zip it up and upload it here please?This is an isolated report so we’ll need to know:- what happened around this time?(Timeouts? Scores? Lead? Called jam?)- were you running full line up and penalty electric tracking?- what was the purpose of the proxy? ThanksJeneral Pain Sent from my iPhoneOn 11 Apr 2023, at 8:22 am, Anna Mayer ***@***.***> wrote:﻿
It may also be relevant to note that the scoreboard froze at the Y'AllStars tournament as well but I don't have details on that issue.
Reported by Roslambo at Dallas Derby Devils:
During the final game on Saturday (April 1, 2023, day 2/3 of the tournament), with 2:25 left in the 2nd period, all of the clocks froze and CRG was not taking inputs from the scoreboard operator.

CPU was at 100% usage per Task Manager
used CRG 5.0.11 and Microsoft Edge
ran a remote proxy for Quad Media

**Comment by UKillLele** [comment]
I've requested that info from Roslambo and will add it when I receive it.

**Comment by frank-weinberg** [comment]
The requested data has now been added to #606 - closing this ticket to keep the information in one place..
