### ISSUE TITLE
[FEATURE][LINK-603]no trip score displayed on overhead display

### ISSUE THREAD

**Issue by WishboneBreaker** [rollerderby/scoreboard#604]
Request for an option to remove the trip score display for the overhead scoreboard display 

The reason is if one is fixing time on the fly for instance because a JR has communicated a score change from the previous jam (say another 4 points) and the new jam is already started, one could just add or subtract to the current jam but then the display will display inaccurate information. That the current trip would be displayed as 8 -- which is wrong. The option ahead of time to hide the display of lap scores would prevent inaccurate info displayed and/or the TOs needed to not just resolve it but also explain to the teams why the other team got 8 points on the first trip.

Any option to edit/undo the score needs to not prevent the other functions of live jam reporting. Pop ups and dialog boxes that prevent me from stopping a jam if suddenly a jam stops while I'm trying to fix a late score from a JR disrupts game flow and causes the displayed clock to not match the JT... Causing more game flow stoppage.

**Comment by frank-weinberg** [comment]
This sounds like working around the symptoms of a different problem - that it is too cumbersome to fix the points in the correct place right away. Since we might be addressing the underlying problem in the other ticket, I'd put this one on hold for now.

**Comment by WishboneBreaker** [comment]
Thank you. I feel like the feedback I'm bringing you is being given some amazing ideas. 

It's ok to delete/ edit issues 603 and 604 and combine them if that makes things easiest to prioritize, etc. under a different umbrella, but after reading the ideas in 603, I want to communicate that there is a desire I guess to make score changes hot key editable without changing the current jam display. I don't know if that clarification changes your thought on whether 603 and 604 fall under the same umbrella.

Thank you for listening. It's so appreciated. And of course thank you for the thought you've already put into this.
