### ISSUE TITLE
Sorting/color-coding skaters

### ISSUE THREAD

**Issue by WishboneBreaker** [rollerderby/scoreboard#605]
An option to color code the skaters or sort them would be nice. As in, I can color the assumed jammers of the roster in yellow and the assumed pivots in blue, let's say, so I can easily pick them out of a list of 15. Or, a way to drag and drop sort them so I can move all the jammers to the left, let's say, and put all the pivots on the right of the list. If that makes sense. Basically so you can easily find your favorites, so to speak.

**Comment by JeneralPain** [comment]
Wishbonebreaker:Could you give context to where this color coding would be used?Sent from my iPhoneOn 16 Apr 2023, at 6:43 am, WishboneBreaker ***@***.***> wrote:﻿
An option to color code the skaters or sort them would be nice. As in, I can color the assumed jammers of the roster in yellow and the assumed pivots in blue, let's say, so I can easily pick them out of a list of 15. Or, a way to drag and drop sort them so I can move all the jammers to the left, let's say, and put all the pivots on the right of the list. If that makes sense. Basically so you can easily find your favorites, so to speak.

**Comment by frank-weinberg** [comment]
I understand the request and see why that would be a useful feature. I'm thinking about how to best implement it.

What might be helpful as a workaround for the time being is assigning hotkeys to the Jammer/Pivot buttons you want to have highlighted. Even if you don't intend to use the keys, the hotkey indicator should make the buttons stand out a bit by making them wider.

Regarding the final solution:

1. I'd say colors would be a lot easier to implement than sorting. 
2. I had been wondering if this would be better configured on the operator tab or the teams tab (and accordingly stored as operator setting or with team data). I'm currently leaning towards the teams tab as the operator interface is already so full. Plus storing this as team data opens up the option of using it for the (P)LT interface as well.
3. I'm unsure if there should be a predefined set of colors to choose from or if we should give users a color picker. - Obviously the latter gives more flexibility but it also introduces the pitfall of people shooting themselves in the foot by selecting colors that are too close to the "currently selected" highlight color. And repeatedly selecting the same color with a color picker can be tricky.

**Comment by WishboneBreaker** [comment]
> What might be helpful as a workaround for the time being is assigning hotkeys

Great interim idea, I'll pass it along.

> 
> Regarding the final solution:
> 2. 

For color, teams tab sounds logical. It's where we're putting in their name, etc., anyways. Drag and drop on the operator display would potentially cause sorting errors, so I could see that being less ideal. I had imagined something like a custom sort order in the team tab that reflected on the operator tab, but I think color coding would be more effective to highlight the skater numbers you know you're using most

> 3. 

I like the picker, but maybe there's a "recently used" tray along with it?

**Comment by WishboneBreaker** [comment]
Proposed alternative/additional functioning (suggested by another). Have it also be more of a "used this game" function option where if you've used a jersey number as jammer in the current game, it automatically colors it your chosen color. (And the pivots used automatically get turned to the pivot highlight color)

Like, you'd set up the color ahead of time on the teams pane. And maybe at that point you could toggle it on for the two people you know are jammers. Then during game play, other numbers you click to assign as jammer automatically get the highlight color applied. 

When this was suggested, I agreed it would add an excellent addition to the idea. Thanks

**Comment by reflexdd** [comment]
﻿If you put colors on the operator tab you could think about 1. pre-assigning jammers if known2. assign them automatically during the game by counting the jams  a skater skated as jammer. This could be helpful for games you don’t know the regular jammer rotation. Maybe also with gradient steps for quantify jammers who are skating mir jams as jammer then others. Am 16.04.2023 um 12:47 schrieb WishboneBreaker ***@***.***>:﻿

What might be helpful as a workaround for the time being is assigning hotkeys

Great interim idea, I'll pass it along.

Regarding the final solution:
2.

For color, teams tab sounds logical. It's where we're putting in their name, etc., anyways. Drag and drop on the operator display would potentially cause sorting errors, so I could see that being less ideal. I had imagined something like a custom sort order in the team tab that reflected on the operator tab, but I think color coding would be more effective to highlight the skater numbers you know you're using most





I like the picker, but maybe there's a "recently used" tray along with it?

**Comment by frank-weinberg** [comment]
Merging all ideas together (aside from the gradients - that feels like too much effort for too little gain) I propose the following design:

- We define skater groups "Jammers", "Pivots", and "Skater_Color_1" to "Skater_Color_5". These groups can be assigned colors through the existing colors dialog on the teams tab/screen.
- Each skater can be manually assigned to one of these groups or left unassigned.
- If a skater that is not assigned to a group yet is fielded as Jammer or Pivot, they are added to the respective group.
- On the operator screen in the Jammer resp. Pivot selection the members of the corresponding group are highlighted, all other skaters are left at the base color.
   - The "currently active" green highlight trumps the group color.
- On the (P)LT screens all skaters are highlighted according to their group. The current green is used for skaters not in a group or groups not assigned a color.
- On the PT screen the active Jammer and Pivot are marked in the respective group color (if set) instead of a slightly different shade of green.
- On the roster screen there is a color marker in each skater's row.

Thoughts?

**Comment by WishboneBreaker** [comment]
I think the bullets regarding the operator and teams panels are great.

I don't use the P/LT screens enough to have a fully experienced opinion on those. Having the color coding spread to those sounds like what I'd want myself. But, I've probably only done 6 games personally where I am using the P/LT panel.

**Comment by frank-weinberg** [comment]
Ok, doing the full feature as described above turns out to be more involved than I initially expected. But I can get the core of it done quite easily:

- Each skater has a color flag that's initially empty. If they are fielded as Jammer or Pivot it gets set to that value (overwriting a prior assignment)
- On the operator screen skaters with a jammer/pivot color flag get highlighted in a hard coded color in the corresponding selector

You can still preset the flag for skaters by cycling through them ahead of the game.

**Comment by WishboneBreaker** [comment]
Is there a default action for star passes? As in, does someone previously fielded as the pivot but is now the jammer, would their flag automatically turn jammer? Or would they remain as a pivot color, since that was their original fielded position?

**Comment by frank-weinberg** [comment]
They would remain Pivot.

**Comment by frank-weinberg** [comment]
I have to backtrack slightly - the cycling through doesn't work in the current iteration of the code - the color only sticks when the jam starts. But that also means an accidental misclick doesn't immediately mess up the colors, which might be a worthwhile trade off. This is how it looks:

![Screenshot_20230509_210013](https://github.com/rollerderby/scoreboard/assets/34135287/256612c1-9c62-40cf-8272-f7635b2b4137)

**Comment by WishboneBreaker** [comment]
> I have to backtrack slightly - the cycling through doesn't work in the current iteration of the code - the color only sticks when the jam starts. But that also means an accidental misclick doesn't immediately mess up the colors, which might be a worthwhile trade off. This is how it looks:

I think sticking on jam start is the way it should go.

by "hard coded" for the color, do you mean it's going to be always yellow (for instance) for everyone? If yes, I suggest a different color that's further in value from white. And/or... maybe "unhighlighted" buttons are actually the colored ones (again, some color different than light yellow) and once the skater has been assigned as jammer/pivot, then it would appear white.

**Comment by frank-weinberg** [comment]
> by "hard coded" for the color, do you mean it's going to be always yellow (for instance) for everyone?

Yes

> If yes, I suggest a different color that's further in value from white.

The difficult part is striking the balance between sticking out enough to be helpful when selecting jammers/pivots while not sticking out so much that it's distracting at other times. And since people will be focusing on this area anyways during selection, I'm trying to err towards the sticking out less side. But I'll play around a bit more.

(Using non-white as the highlight makes more sense to me in terms of the general UI logic.)

**Comment by WishboneBreaker** [comment]
I think even light/med grey or blue or peach would be easier on people than a florescent yellow. Would you like me to suggest some hex codes?

**Comment by frank-weinberg** [comment]
Options:
- a darker yellow
![Screenshot_20230509_212025](https://github.com/rollerderby/scoreboard/assets/34135287/2a0fe132-0be7-47ec-944e-d500c1580631)
- WFTDA pink
![Screenshot_20230509_211904](https://github.com/rollerderby/scoreboard/assets/34135287/06690ef7-c928-4b01-92e8-517d860fd775)
- dark grey
![Screenshot_20230509_212334](https://github.com/rollerderby/scoreboard/assets/34135287/871f25d9-7c39-44ed-8776-360699b1edf5)

I like that last one. But if you give hex codes, I can try those as well.

**Comment by WishboneBreaker** [comment]
the gray with white numbers is fabulous.

**Comment by frank-weinberg** [comment]
Great. So this will be the v2023 operator screen (in expert mode):

![Screenshot_20230509_212947](https://github.com/rollerderby/scoreboard/assets/34135287/04c205a6-d5ba-43f4-89a9-bee09a630838)

**Comment by WishboneBreaker** [comment]
Outstanding

**Comment by WishboneBreaker** [comment]
I'd love to try out how the adjustment score buttons work. Sorry for the newbie request, but can you point me to where I can download the file? Scotchy can probably help me compile it or whatever it is we'd need to do to install and test.

Is that possible?

**Comment by frank-weinberg** [comment]
If you can compile the source code (or get it compiled) then you can use https://github.com/rollerderby/scoreboard/archive/refs/heads/dev.zip

Otherwise I hope to have a release candidate ready later this week. (Just have to update a number of Wiki pages.)

**Comment by WishboneBreaker** [comment]
Thanks. I do believe Scotchy can compile it for me. I'm too impatient to wait, if I can convince him.
