### ISSUE TITLE
BUG - 5.0.11 Freezing

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#606]
@WishboneBreaker , @JeneralPain - starting the thread over here from #603 

> Gosh, i'm not even sure what the issue is. There were two meltdowns due to scoreboard at Clover Cup. The second one resulted in a 25 minute timeout. Not due to operator error, I'm told.
> 
> An organizer of the Y'all Stars event told me a similar thing happened there.
> 
> Then at BOTAS "Here’s my best try at this: My experience from BOTAS was that the longest time out happened when the cached scoreboard auto save things maxed out the hard drive? Then the concurrent overlay and broadcast stuff slowed things down a touch more."
> 
> What I'm hearing is it seems to be a memory cache thing.
> 
> Sorry to reply on this thread, I'm unsure how to start a new one. Details beyond what I've listed could be obtained if you're interested. I'd just have to reach out to those folks for any additional details they have that you think might be useful
> 
> *I mean, I'm not sure how to break apart one thread for another. Or even if it's something you're interested in

@WishboneBreaker - if you could get the AutoSave files, that would be helpful. As both Jen and I are Australian based, we don't have contacts in the US to get that information. Even better would be a full ZIP of the CRG folder that was being used

I'm curious to see how big the files where, and what was in them, to cause that issue. I've got an instance that runs 24/7 has 2 or 3 weekends worth of games, and the files are only ~15mb each

**Comment by WishboneBreaker** [comment]
> I'm curious to see how big the files where, and what was in them, to cause that issue. I've got an instance that runs 24/7 has 2 or 3 weekends worth of games, and the files are only ~15mb each

Are you streaming and/or running an overlay 24/7? I had been thinking myself (with no evidence of why it would matter to the memory) that that was the commonality from events where it froze and events where it didn't.

It may take some time to obtain the files you requested, if they exist. But while I track it down, I'll ask folks to save those files if they have a crash in the future.

Thanks for helping me start a new issue using the old thread. It was very helpful.

**Comment by JeneralPain** [comment]
Yeah if you can zip the whole scoreboard directory and dump it on a google drive or something.I can give a space to use as well.Jen Sent from my iPhoneOn 17 Apr 2023, at 1:45 pm, WishboneBreaker ***@***.***> wrote:﻿

I'm curious to see how big the files where, and what was in them, to cause that issue. I've got an instance that runs 24/7 has 2 or 3 weekends worth of games, and the files are only ~15mb each

Are you streaming and/or running an overlay 24/7? I had been thinking myself (with no evidence of why it would matter to the memory) that that was the commonality from events where it froze and events where it didn't.
It may take some time to obtain the files you requested, if they exist. But while I track it down, I'll ask folks to save those files if they have a crash.
Thanks for helping me start a new issue using the old thread.

**Comment by bullseye555** [comment]
No - not running an overlay 24/7, but that's should only be extracting from CRG and not writing to it, so it _shouldn't_ impact the file size

**Comment by JeneralPain** [comment]
So thinking about this, the overlays and the displays (like scoreboard on
projector) are just web socket sessions. Once the session ends or times
out, the socket is killed and deleted.
So if its holding those, its holding the websocket for whatever reason.

I'd really need the logs or details.

Jen

**Comment by WishboneBreaker** [comment]
@JeneralPain did you follow up with anyone in this thread? https://www.facebook.com/groups/derbyscoreboard/permalink/6020270408054681/?mibextid=rS40aB7S9Ucbxw6v

Folks from BOTAS, Y'all Stars, and Clover Cup all commented in that thread.

**Comment by JeneralPain** [comment]
Good call WishboneBreaker, I've replied to that one.

I hadn't seen Facebook yet today, been busy.

**Comment by WishboneBreaker** [comment]
Yes, and I didn't want to ask the same people you have if you had existing off-line discussions with specific people already. Thought I'd coordinate. Figured that would make the most sense, I guess.

**Comment by JeneralPain** [comment]
Nah not yet, I remember seeing someone talking about a crash and had asked
but then I'd gotten busy with my ankle break recovery and new job so I
thought I'd forgotten.

**Comment by WishboneBreaker** [comment]
This and #602 are probably the same thing.

**Comment by frank-weinberg** [comment]
> This and https://github.com/rollerderby/scoreboard/issues/602 are probably the same thing.

I'm not sure "this" is even a single thing. I'd be happy if they all were the hard disk being full due to CRG autosave backups. That would have an obvious fix. But my guess is there's another gremlin somewhere that will be hard to find because nobody has any clue what triggers it.

**Comment by WishboneBreaker** [comment]
This is a link to the CRG files from the Clover Cup event where they reported issues (in case this file hasn't made it to you all via another path):

https://drive.google.com/file/d/1i_r1Jm2KcEUI-qzeloxJF6THBwJA_Pdv/view?fbclid=IwAR3VyFdwHdqgdX3T2hAfArrzMi2YULRuLCHxYmBVda25VYIeaBMJHZWR3fc
 
 Here's the comments:
 

>  (date and time of incident was on 4/1/2023 at approx. 9:50pm local Dallas time)
> During the Twister City vs Dallas game with 2:25 left in the 2nd period, all of the clocks froze and CRG was not taking scoring inputs from the scoreboard operator. The officials took a timeout to try and sort out. It seems when the scoreboard operator tried to stop the time for the timeout, it didn't take that input either, because by the time we rebooted and opened the scoreboard to try and resume the game, the period clock had expired. 
> In order to finish the game, we used a backup laptop and ran a barebones game for the final couple of jams.

Another description that she thinks was already provided on Facebook. Copied here again, for completion:

> During the final game on Saturday, with 2:25 left in the 2nd period, all of the clocks froze and CRG was not taking inputs from the scoreboard operator. Someone opened the task manager and the CPU was showing as being utilized fully at 100%! And it was staying at 100%, not fluctuating at all. It is possible that the RAM was also being used to its full capacity but no one really remembers. 
> If it matters, there were at least 9 completed games in the CRG folders by this time. 
> 
> We were using 5.0.11 version of CRG scoreboard and Microsoft Edge browser. Also running on the laptop was Java (I have asked which version, but don’t know yet) and a remote proxy for Quad Media. In true Windows fashion, there may have been a handful of background processes and updates happening too.

**Comment by frank-weinberg** [comment]
Thanks for forwarding this. The descriptions help narrowing the search a bit. I'll see if the data in the attachment helps further.

**Comment by frank-weinberg** [comment]
I have found and watched the recorded stream from the game in question. There was very visible and worsening lag on the stream overly in the minutes before the freeze. This points to the problem resulting from resource exhaustion (I'd say RAM is the most likely resource) with the freezes happening as a result of this.

**Comment by JeneralPain** [comment]
Do we know the details of what was used to power the scoreboard at Clover?
It's not terribly resource heavy, but if the system is already starved of
resources, it adds complexity.

**Comment by WishboneBreaker** [comment]
Do you mean "power" as in the literal battery/electric supply? Or do you mean some kind of computer stat?

**Comment by JeneralPain** [comment]
Ahhh apologies Wishbone, I meant like what was the scoreboard running on.
Like a Raspberry Pi, ChromeBook, Laptop etc?
Like what sort of grunt did it have (ie: CPU, RAM in GB, Disk in GB/TB)
sort of thing.

**Comment by WishboneBreaker** [comment]
Thanks, I will ask them for those if they have them (I believe they will)

**Comment by JeneralPain** [comment]
Thank you muchly.

tbh most laptops these days will handle it just fine. But I do know,
donated freebies from friends/family tend to be chugalicious and when
something goes wrong, it just eats what little resources it has left and
then, sad times occur.
But I do get it because, beggars cant be choosers these days when derby
(Even in Aus) gets very little love in terms of grants, money, advertising
sort of stuff.

**Comment by WishboneBreaker** [comment]
This is the specs for my own Surface, which we'll be using at this weekend's Miami Valley OPE!n. (These aren't the stats from the Clover Cup we're discussing above). Is there any concern with this set up I plan to use this weekend? Do you need other info about the system to know if you think it'd be sufficient or if it's too slow?

Processor	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
Installed RAM	16.0 GB (15.6 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Home
Version	22H2

**Comment by frank-weinberg** [comment]
This system should have plenty of reserves in terms of both CPU and memory.


I noticed one more detail that might be relevant:
The autosave from Clover Cup shows that there was a DerbyStats wsproxy running on the coreboard computer. Presumably to provide the overlay for the stream. 
If my assumption about the source of the problem being memory exhaustion is correct, then it could be either CRG or wsproxy (or the combination of both) as likely candidates for what is gradually using more and more memory. With  the current state of knowledge, I would recommend to stop and restart both regularly over the course of the day, e.g. every other game. This should reduce the risk of problems at little cost. And it would be a good idea to spread this recommendation to other tournaments happening this weekend. (Just make it clear that this is based on a semi-educated guess and might turn out to not help.)

(At the weekend I'm at a tournament myself and will try to mimic the Clover Cup setup, monitoring memory and CPU usage over the course of the day. Hopefully this will give further insight into the source of the problem.)

**Comment by JeneralPain** [comment]
That should be just fine! Sent from my iPhoneOn 25 Apr 2023, at 7:37 am, frank-weinberg ***@***.***> wrote:﻿
This system should have plenty of reserves in terms of both CPU and memory.
I noticed one more detail that might be relevant:
The autosave from Clover Cup shows that there was a DerbyStats wsproxy running on the coreboard computer. Presumably to provide the overlay for the stream.
If my assumption about the source of the problem being memory exhaustion is correct, then it could be either CRG or wsproxy (or the combination of both) as likely candidates for what is gradually using more and more memory. With  the current state of knowledge, I would recommend to stop and restart both regularly over the course of the day, e.g. every other game. This should reduce the risk of problems at little cost. And it would be a good idea to spread this recommendation to other tournaments happening this weekend. (Just make it clear that this is based on a semi-educated guess and might turn out to not help.)
(At the weekend I'm at a tournament myself and will try to mimic the Clover Cup setup, monitoring memory and CPU usage over the course of the day. Hopefully this will give further insight into the source of the problem.)

**Comment by WishboneBreaker** [comment]
https://imgur.com/a/iUzSNjw

Three screenshots of the system info from the computer used for Clover Cup.

**Comment by frank-weinberg** [comment]
Thank you. That does help significantly.

The system was running Windows 11 on 4GB of RAM. That is the bare minimum required for this version of windows. (It will refuse to install with anything less.) Add in the browser with 3 tabs open (Operator, Display, Penalties as per the autosave) and you are already at 95% memory usage before CRG and wsproxy are started.

So, yes, memory exhaustion is very likely the problem but not necessarily due to a bug in one of the programs used but due to the system running so close to the limit from the start that the normal growth due to accumulated game data couldn't be handled.

Note that the same laptop would have been fine to run CRG 5 + wsproxy with Windows 10 or Linux.

(I will still check memory and CPU usage of CRG and wsproxy this weekend in order to see if there is something worth looking into in either of them. But my expectation changed significantly after seeing these numbers.)

**Comment by JeneralPain** [comment]
I'm with frank on this one as well, 4GB + System processes + Chrome + everything else, it would have been struggle city before even launching CRG. 

I think the desktop I use as a "server" so its headless and without anyone touching it, runs 8GB with Linux on it.

**Comment by jlsanman** [comment]
I am the one who had the issues at Y'AllStars.  If you need another instance to examine, I still have my version of 5.0.10 that I used at Y'AllStars untouched from the event.  The computer that crashed was my laptop that has Windows 11 and 8 GB of RAM and also was running wsproxy.  The crash occurred at the very start of the morning after we had started up the computer to begin the new day.  I am looking in the instance now and the Backup folder located in the config/autosave area is still holding at 1.34 GB.

**Comment by frank-weinberg** [comment]
Well, that's incompatible with every theory I've had so far - 8GB should be plenty and if it crashed at the start of the day that's not due to any program growing in size while it's running. 

The size of the backup folder is not a direct indication of runtime size as that folder gets a new set of autosave files added to it every time the software starts.

What were the exact symptoms at Y'AllStars? A freeze right after starting up or with a few minutes delay? If the latter, could there have been lag before the freeze? If the former, were the browser windows already running when CRG started?

**Comment by jlsanman** [comment]
I was the SBO for that game.  It crashed at the end of halftime as it was transitioning from halftime to display the the clocks again.  It would not accept any inputs. I did not notice any lag during the first half.

**Comment by frank-weinberg** [comment]
Did it crash or just freeze? (I.e. was the Java window still there and if so was there any output beyond what you usually get at startup?) And what was needed to get back up? Did a restart of the backend suffice or did you have to do more?

**Comment by jlsanman** [comment]
I would go more with froze.  We could not input anything on the laptop or tablets.  I had another computer going so we switched over to the other computer and a colleague shut down the laptop.  Thinking it might have over heated, we let it cool off for couple games and brought it back up.  When we brought it back up, we were able to get the first half downloaded, and out of fear, we just loaded a clean instance on the laptop and ran that clean instance for the last two games of the day.

**Comment by JeneralPain** [comment]
I'm at Statewide Stampede in Victoria and we had the following occur:
v5.0.11
Win10
8gb ram

At the start of the game, SBO would click "jam start" and the respective clocks would show green but would not count. The overlay and the public scoreboard said
P1 30:00
J0 2:00

They would enter the score, but it did not update the sheets either. 

I was eventually asked to intervene and found that the scoreboard would not restart until I renamed "autosave" to "autosave.old". So at half time in about 15min I will get a full copy of the scoreboard folder and upload it to Google or OneDrive and share the link for all to have a nosy park and see if we can collaboratively figure it all out.

**Comment by JeneralPain** [comment]
Copy of scoreboard is here:
https://drive.google.com/drive/folders/1Taoz4N6m-TLNMo4uZ6bHm8FMVN00xDYf?usp=sharing

**Comment by frank-weinberg** [comment]
FOUND IT!

v2023-rc with the fix will be out as soon as I got the wiki updated to the UI changes.

**Comment by bullseye555** [comment]
Great work, Frank!!
