### ISSUE TITLE
[FEATURE] Logging from Java Window (And states) to log file

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#611]
Can we create a simple log file for the output of java window?
That way we have better diagnostics and can ask people when creating a problem to upload the log file somewhere?

As the scoreboard jar file when you restart, In the issue #606 I was asked to intervene when it froze and they could not restore, but I lost valuable data as they'd already chosen to restart. But if we're constantly writing to a simple log file on java errors, then we have a stronger chance of identifying potential faults.

Or even creating a "scoreboard-logged.exe" which then has the java switch built in to write the log as telling "non tech people" who do and are strong SBOs to use -log <logfile.exe> when booting scoreboard, is not a feasible option.

**Comment by frank-weinberg** [comment]
I will look into this and if it's not too much effort I'll add it for v2023.
(I don't think second exe is an option - if anything it's a log file that's always written.)

**Comment by JeneralPain** [comment]
Yeah, maybe just a simple txt file for the log so we can try to figure out stuff.
