### ISSUE TITLE
Jam number display at start of period 2

### ISSUE THREAD

**Issue by WishboneBreaker** [rollerderby/scoreboard#619]
When one comes into period 1 from time to derby, the display shows period 1 jam 0.

When one comes into period 2 from intermission, the display shows period 2 jam 25 [or whatever the last numbered jam of P1 was]. This caused confusion more than once at the Miami Valley OPE!n a couple weeks ago. Jam timers, HRs, benches... all at points expressed concern the SBOs had done something wrong and delayed proceeding with the new period until the HNSOs could reassure folks.

Can period 2 also go in with showing jam 0? Or maybe both can start with "Jam -"?

Or can in both cases maybe show no jam clock / jam number? 

![period1](https://github.com/rollerderby/scoreboard/assets/130868045/2bab6c59-4b10-4051-8fd8-e0a2ad5da6aa)
![period2](https://github.com/rollerderby/scoreboard/assets/130868045/f8548c95-345d-4aea-be5a-cb4b11d15cce)

**Comment by frank-weinberg** [comment]
We did have an override that showed Jam 0 even though the number was different internally. But that caused breakage in the data files, so we had to remove it.

But I will have another look and see if there is a way to sort this without such side effects. (Will probably not be easy, so may take some time.)

**Comment by WishboneBreaker** [comment]
Talking with Scotchy (Chair of WFTDA Officiating Application), he mentioned a sort of "dream/ideal" state for this would be that it doesn't even show that "30:00 | 2:00" screen until the jam actually starts for the 2nd half. That there'd be an intermediate state/screen between the halftime countdown and the jam start. Like "End of halftime" being displayed (and the sponsor logos could be playing -- which the sponsors would love to see). Or "start of period 2." Or, maybe it only shows the 30 minute clock, centered perhaps? Or it just stays on "Intermission 0" from the previous screen.

Just offering some alternate behaviors suggested by the person who writes the officiating standards. I realize none of these may be easier than the original suggestion.

**Comment by frank-weinberg** [comment]
I've also thought along these lines. The only thing that makes me reluctant about doing this is that it would be a UI change right after we said we'll keep the UI stable.

But given that it fixes a bug that I don't see a good other way of fixing, we might be able to get away with using the lineup/timeout layout with [30:00] [P2] [ ] [ Coming up ] [ ]

**Comment by WishboneBreaker** [comment]
I like "coming up." that is one way to interfere least with the current established flow.
