### ISSUE TITLE
Edit Key Control --> Click --> Spacebar fails silently

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#621]
Spacebar is not a valid key control for reasons I do not fully understand; accordingly, if someone attempts to "set" it as a key control, the interface should provide this information to the user so they don't end up in a cycle of click, space, switch, attempt, fail, etc. -- the issue here is to tell the user if/when they try to set "spacebar" as a key control, that it is invalid.

**Comment by admdikramr** [comment]
This is not just about spacebar; the user should be warned about any invalid key.

Example error text: "ERROR: You can only use letters, numbers, and punctuation for hotkeys. Spacebar, return, modifier keys, and function keys cannot be used."

**Comment by bullseye555** [comment]
I'll let Frank add comments on the warning, but spacebar has been removed
as while this is a great 'smash here to start/stop jam', Web browsers have
a funny way of handling it

If another button has previously been clicked, the 'focus' is now on that
button - and using the spacebar (without changing the focus to somewhere
else, or clicking into the background so it doesn't have a focus) says to
the browser "click the button that is currently in focus". Not only does
the focus button get activated, but also the shortcut - so you could add 4
points to a team AND end the jam; or go into a Timeout; etc

**Comment by JeneralPain** [comment]
Space to help fill the gap here Muffin will be treated by the browser based
on whatever was clicked last.

So lets say your SBO clicked +1 to up the score by 1 point at the
conclusion of a jam.

The browser now "recognises that" as the last thing clicked and therefore
any "space or enter" press will give you those outcomes again.

This is why space and enter are not acceptable hot keys as it can lead to
errors.

**Comment by admdikramr** [comment]
I understand more or less WHY this is the case -- this issue is about how the "edit key controls" system fails silently.

When I click "edit key controls" and then click "start jam," start jam is focused. If I hit space, at that time, I should get an error telling me that "space" is not valid.

**Comment by frank-weinberg** [comment]
When you click "edit key controls" and then click "start jam" you start a jam. You should only hover over the buttons. If you do that there is also feedback that space is uncooperative - it will re-press "edit key controls", disabling edit mode.

I don't see a straightforward way to give a notification when space is pressed. But I can at least add it to the explanatory text you get when in edit mode. (And change the language about buttons being disabled - only key controls are. I wouldn't even know how to disable clicks without adding extra code to every single button.)

**Comment by admdikramr** [comment]
That sounds sufficient thank you!
