### ISSUE TITLE
"Delete Jam" fails silently when the jam has points in it

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#622]
Scoreboard control view --> click jam number --> scroll back to find the offending jam --> "delete jam"

If there are no points in the jam, this works as expected. But if there are points in the jam, the jam does not delete. The issue is that the "delete" button fails silently. Upon attempting to delete a jam with points in it, the UI should tell the user that they cannot delete the jam because it has points in it.

**Comment by frank-weinberg** [comment]
![Screenshot_20230515_085728](https://github.com/rollerderby/scoreboard/assets/34135287/cfe7e16b-f576-477a-a5c5-b4c96e294ee8)

This is how it's supposed to look. I find it very obvious that all but the last of the delete buttons are disabled. Does it look different for you? (If so, which Browser + OS are you using?) Or is this not as obvious to others as it is to me? (If so, what would be?)

**Comment by WishboneBreaker** [comment]
Me replicating Muffin's situation, but using the pencil edit icon. If I go to edit a jam from 2+ jams ago, I get the "remove jam #" option. If I hit that, it seems like the edit pencil unchecks itself and the jam returns to the not-currently-editing mode.

Though in my opinion, I would not prefer a popup that says "cannot delete jam" because of the whole "popups prevent me from using my hotkeys" issue. So if a red warning text or something appears? or the button press for an un-delete-able jam turns the button red maybe? So you at least know yes, you hit the button but the software won't let you do that function? Or maybe the "remove jam #" button is grayed out in that case?

**Comment by frank-weinberg** [comment]
I'm aware that the inline button currently doesn't indicate that it's not doing anything and I plan to change that. It'll most likely end up with the same behavior as the button in the popup (i.e. grayed out unless this ticket leads to a change).

**Comment by admdikramr** [comment]
Greyed out with hover text explaining why it's greyed out? The main issue of this ticket is understanding how to rectify the situation. Philosophically if someone wants to delete the jam they probably have a good reason for it.

**Comment by frank-weinberg** [comment]
![Screenshot_20230518_132643](https://github.com/rollerderby/scoreboard/assets/34135287/468ab6d0-2cf8-4a95-b1a0-6b58877be03b)
This was easier to do than a hover text and should be at least as clear.

**Comment by WishboneBreaker** [comment]
What does the "insert before" button do? If I click it for jam 2, does it apply those points to jam 1 and then delete jam 2?

**Comment by frank-weinberg** [comment]
It inserts a new jam before Jam 2.

**Comment by WishboneBreaker** [comment]
oh i see. this isn't a new popup. it's the old one with the delete button different. i'm thinking too hard about it.

if i get it right, muffin's point about the jams though is that the user should be able to delete jam 2 if they want to, but they can't. 

i think the idea would be to actually HAVE the delete button always there, but if they do press it for a jam with points the software responds with "this jam has points. do you really want to delete? If yes, which of these options are you choosing? (1) add these points trips/points to the end of previous jam [keeps the overall score the same, but changes jam number] (2) add these points to the following jam before the first scoring trip [keeps overall score the same, but changes jam number] (3) delete these points completely [DOESNT change the score, but adds an offset note if the jam being deleted is outside of the ruleset allowable timeframe, and changes jam number] (4) stash these points and I'll deal with them later [keeps overall score the same and changes the jam number]

I mean, I realize that's too many words to actually implement. But @admdikramr is that the kind of behavior that you would expect when trying to delete a jam with points?

**Comment by WishboneBreaker** [comment]
I guess there should be a (3a) and (3b) one for if the change is within the allowable rule (so jam AND points AND jam# are all deleted) and one for a jam outside of the allowable time

**Comment by admdikramr** [comment]
Issue #622 is ONLY about a useless button, which I can click repeatedly and it keeps doing nothing and saying nothing. The fix addresses this issue. The "Delete" vs "Has Points" column, with a "Delete" header, is self-explanatory in my opinion.
