### ISSUE TITLE
[FEATURE REQUEST] Support spacebar as a key control.

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#624]
Spacebar has been the preferred key control for "start jam" for many people for many years. Spacebar was supported in prior versions of CRG (through 3.x), but support was recently cut; v2023.0 is not backwards compatible in this way. This lack of backwards compatibility means that any NSO who upgrades from a prior version that supported space to the new version, could be unexpectedly learning a new key process while also running the scoreboard.

In many games, an NSO is not aware of their role in a game until game time. Often this is due to a "switch" of availability due to illness or a no-show. Backwards compatibility for CRG means that someone who has used a prior version of CRG should be able to operate the current version without additional practice for the purpose of fulfilling Rule 1.4, Game Information (period clock, jam clock, score). Forcing someone to switch ingrained keys at the moment can result in errors.

Example: I personally practiced a whole game using an old version (3.x) on Thursday, using spacebar to start the jam. On Saturday (two days later), I could not use spacebar. The resulting last-minute swap resulted in several small errors in which the wrong button was pushed. I was able to recover from most of them but two of them were noted by other NSOs and one required an official timeout to resolve.

It is understood that supporting spacebar is technically difficult and may not be achievable without an inordinate amount of effort; however, it is important to keep this as a feature request for the above reasons.

**Comment by JeneralPain** [comment]
Muffin,

It's not that the space bar is difficult, it requires specific custom code
that stops the browser interpreting it as the "last thing pressed".

This completely goes against the way both browsers and operating systems
work.

I will investigate if this can be done, but I don't see it on the horizon
any time soon because the effort for the reward is just too little (given
the small user base).

**Comment by WishboneBreaker** [comment]
If the feature can't be added, how hard would it be to have a popup or something when you're in key edit mode that says "space bar results in unexpected results" or something? I know I myself used to use the spacebar when I was a new to the scoreboard. I can see why people wouldn't understand to avoid it, especially if they were used to using it for 10 years. 

If I go into right now and try to set space as a hotkey, it just kinda boots me out of the tab without explanation. It says to not use "esc". Maybe in the least this warning should say "spacebar"

**Comment by admdikramr** [comment]
Totally understand what you are saying, I just wanted to flag it as an issue (perhaps not one we can resolve) due to the cavalcade of errors it caused during yesterday's game. So no pressure, but i wanted to note the request. :)

**Comment by frank-weinberg** [comment]
If someone can tell me how to reliably avoid space activating what to most users feels like a random button, I'll happily bring it back (and switch my own keyboard layout to use it for timeouts). Until then the downsides outweigh the benefits.

**Comment by spikenheimer** [comment]
idk if this works still or in which browsers etc but this page implies a way to deactivate default key actions (at least for scroll)
https://thewebdev.info/2021/07/30/how-to-prevent-the-pressing-of-the-space-bar-from-scrolling-the-page-with-javascript/

**Comment by frank-weinberg** [comment]
This does work. It took a bit of fiddling to get it to not block too much but I found a way. Thank you.

**Comment by admdikramr** [comment]
Huge thanks for this one!
