### ISSUE TITLE
[Feature Request] Totals view in Sheets Tabs for IGRF Totals

### ISSUE THREAD

**Issue by spikenheimer** [rollerderby/scoreboard#625]
Would be great to have an additional Sheets pulldown in the places you have Sheets tab (SBO / Games Edit) with a Total Counts view for Penalty Counts and Scores showing period counts as well as totals for both teams.

Specific usage case is for filling in the signature page of the IGRF with Penalty Counts and Scores by Period by Team - so having it both in SBO view in the event the game is still active in CRG as well as in Games Editing mode in the event the game is not the current game.

Simple view of two Tables (one per team) with columns:  Penalties / Score
and rows: Period 1, Period 2, Total

while its used for the IGRF, i feel it shouldnt be on the same tab as the _current_ IGRF tab as thats for data entering all the things that the IGRF wants, and this is just totals for that page...

**Comment by frank-weinberg** [comment]
That's a great idea to include such a table. I'm not sure if the sheets tab is the best place for it, but having it somewhere is definitely useful.

**Comment by spikenheimer** [comment]
i figured that was the most logical place since its available both when the game is current and more importantly when its not current (think tournament situation where it would be difficult if not prohibited to load an old game as current...
short of a separate app applied against downloaded game data file this felt most appropriate?

**Comment by frank-weinberg** [comment]
I have now put it on the IGRF tab as the expulsions which must also be copied onto the physical IGRF are already there.
