### ISSUE TITLE
[FEATURE REQUEST] Add toggle option for automatic clock stoppage at jam end in last 30 seconds of period/game

### ISSUE THREAD

**Issue by adamcz89** [rollerderby/scoreboard#626]
SCENARIO: A jam ends with 5 seconds remaining on the period clock and both jammers scoring in the pack. Both teams have timeouts remaining. The score is tight, and before the points from the final scoring pass go up on the scoreboard, the period clock hits 0:00. The points then go up; one team celebrates as the other team wishes they had called a timeout.
Both teams had the opportunity to call a timeout when the jam ended to force an additional jam, but neither team knew if they wanted to stop the clock until they saw who was actually winning.
This isn't unfathomable. **You can see this very scenario happen right here:**
https://youtu.be/JqnRgroZC1g?t=4596

Roller derby is presumably one of the only sports (if not the only sport) in which there is a clock and teams don't know what the actual score is immediately at the conclusion of any play. In order to counter this, I want the rules to ultimately be changed to call for the **period clock to automatically stop if a jam ends with under 30 seconds on the clock**. The 30-second lineup would not start, either. The idea would be once the scoreboard operator has ensured all score entry has been finalized, they would then hit a button that would start both the period clock and the 30-second lineup clock. If someone then wanted to use a team timeout, they could do so with complete information. If no timeout happened, the game would end once the period clock hit zero.

You may think I'm doing this backward by requesting it here before the rules are changed, but having the functionality already there will make it a lot easier to get any movement on the rules change side. It can be added as an option (defaulted to off) that leagues could use in unsanctioned play if they wanted.

**Comment by frank-weinberg** [comment]
You don't need a CRG change.
You don't need a rules change.
You can get your desired outcome by adding a procedure that asks officials to take an OTO in the scenario you describe. This has the added advantage that it can be limited to games where the hidden points can actually change the leader.

**Comment by JeneralPain** [comment]
There already is a button in the top.Timeout before period end Sent from my iPhoneOn 17 May 2023, at 5:19 am, frank-weinberg ***@***.***> wrote:﻿
Closed #626 as completed.
