### ISSUE TITLE
[Bug] Entering a "0" trip after a jam has ended with NI still selected does not cause a change in state

### ISSUE THREAD

**Issue by ScotchyNSO** [rollerderby/scoreboard#628]
If a jam ends with the "NI" box still checked, entering a "0" point trip (via the per-trip 0 button/hotkey) does not cause any change in the state of the scoreboard and virtual paperwork. It does not uncheck NI, even though a scoring trip has been affirmatively input, and it does not record a 0-point scoring trip for in the second trip box. If NI is manually unchecked, the 0 button performs as expected for entering a 0 point second trip.

This runs counter to the expected behavior set up by entering any other points value while NI is selected. If I press the 4-point trip button, or the +1 point button, the scoreboard correctly infers that the Initial Trip has been completed and unchecks the NI box (though it leaves an angry red comment scolding me for not manually adding an extra keypress, which is a QOL issue that I don't understand the rationale for). As such, expected behavior is that pressing a 0-point trip button while NI is selected would deselect NI and add a 0-point trip in the second trip box, while leaving the "points added without add trip" comment that normally gets left.

Bonus expected behavior would be to remove that warning from all points values, as I don't understand why it's necessary except to passive-aggressively encourage a SBO workflow that differs from the SK workflow (in which the NI box is only relevant after the jam is concluded) in order to maintain an accurate live state of a statistic that is not displayed on the scoreboard itself.

**Comment by frank-weinberg** [comment]
>  that is not displayed on the scoreboard itself.

It is displayed on the main display by inverting the jam points during initial.

> a SBO workflow that differs from the SK workflow

Around here all somewhat experienced SKs mark the start of a scoring trip by putting a dot in the corresponding box. The Add trip on the scoreboard is the equivalent of that (it even puts a dot in the paperwork) with the QOL addition that in many cases the software can infer it from other inputs, saving you the key press in those cases.


Either way, I will make 0 behave consistently with the other speed score buttons.

**Comment by WishboneBreaker** [comment]
But they don't write an X and then erase it when the initial trip is complete.

**Comment by frank-weinberg** [comment]
True. But the fact that those Xs are displayed is merely a visual thing, not a workflow thing. And as the live indicators in the operator area have NI lit up during initial (which I cant change without breaking some people's workflow) the indicator on the SK paperwork can only be consistent with either that or the current state of the SKs sheet. I picked consistency within the screen.
