### ISSUE TITLE
[Feature Request] Include team names in statsbook export file name

### ISSUE THREAD

**Issue by ScotchyNSO** [rollerderby/scoreboard#629]
Coming fresh from getting confirmation from Bones, since leagues may have multiple ranked charters now, Statsbook naming formats should be updated to include the team name in order to differentiate multiple rosters when submitting to sanctioning. When the team name is entered for a game, can the statsbook be exported to a "STATS-YYYY-MM-DD_HostLeagueTeamName_vs_VisitorLeagueTeamName" syntax?

**Comment by frank-weinberg** [comment]
This can be done in existing versions by setting "Team Name for Files" to "Full Name" on the settings tab/screen.
I can change the default in the next version but people who migrate their data will have to edit the setting manually.

**Comment by ScotchyNSO** [comment]
Sounds good. I didn't know the setting existed in the first place, good to know! (and it'll make my exports for the rest of my tournament games that much smoother)

**Comment by frank-weinberg** [comment]
Be aware that the name is frozen once the first json or xlsx file is written. So if those games already happened, changing the setting will probably have no effect for them as the json is constantly updated during the game.
