### ISSUE TITLE
[FEATURE REQUEST] - Include QR Code for URL

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#637]
The suggestion was made on the Facebook group to have a QR Code for mobile devices (such as those that'll be used for ePLT) to be able to scan and easily connect to the correct scoreboard
The suggestion was to place it somewhere in this box (which I agree with)
![image](https://github.com/rollerderby/scoreboard/assets/28804763/1fb70062-d277-472b-9143-4a024b2fa95c)

However my thought, as you can tell by the number of different IP's available for this instance running on my server (which sits on 4 different networks, soon to be a 5th...) is how do you display the QR code for the correct IP (EG: My main network runs on 172.24.10.0/24, what happens if that's the QR Code, but someone is actually connected on 172.24.50.0/24 which has firewall rules to not allow the two subnets to talk to each other)

My thought on that is that either the URL becomes a hyperlink that when selected, then displays the QR Code for that URL, or a radio button next to the URL to select it
The first option is more simply to implement, but would possibly require some other CSS to highlight that URL as the one that is currently being displayed in the QR Code; as where the second option would require more changes but may be more intuitive to the user
There may of course be another option, happy to go with whatever you think is best to implement

**Comment by JeneralPain** [comment]
So just to clarify here:
Your different IPs here are related to things like VM stub networks and the
like.
And your fe80:0:0 is due to a broken implementation of IPv6 on your network

The QR code being a hyperlink isn't a difficult thing to implement.

That said, your second comment "about firewall rules", is outside the scope
of CRG and cant really be addressed by the CRG development team et al.

**Comment by bullseye555** [comment]
Yeah, was not expecting the CRG team to deal with my firewall rules

And the 192.168 address is a VM in this instance - the 172.24.10 and
172.24.50 addresses are different VLANs.

I'm thinking of a specific scenario where CRG may be hosted on a central
server, where the server is accessible on different subnets and each subnet
is a different Track (and has its own WiFi SSID) - so when you login to CRG
it will show both subnets, but it's only available from 1 of them

**Comment by frank-weinberg** [comment]
We should display the first v4 address as QR code by default as that will be the correct one in a majority of cases. And when the scoreboard is on multiple networks there is hopefully someone around who knows which IP to use for which device.
Displaying all of them at once would be confusing and also take up too much screen space.
Switching QR code by clicking the URL is unintuitive - if I click a URL I expect to be switching the page in my browser.
Radio buttons sound like a more reasonable UI, but one we don't use anywhere else in CRG as far as I am aware.

**Comment by bullseye555** [comment]
Agree with all of the above - happy to have the first V4 defaulted
To fit with CRG UI, could there be a drop down under the QR Code to have
the option to select other IP addresses? I realise they're an edge case,
but if possible it would be good to have that option there to eliminate an
negative feedback on being unable to select the correct IP

**Comment by JeneralPain** [comment]
tbh v4 is going to be the key here.

most of it will be 10.10.10.0/24 for example.

**Comment by frank-weinberg** [comment]
Also renamed the box while I was at it.
![Screenshot_20230528_145319](https://github.com/rollerderby/scoreboard/assets/34135287/9312b958-d06b-4cb3-a617-9e6896d32240)

**Comment by bullseye555** [comment]
Looks great, thanks Frank
