### ISSUE TITLE
[BUG REPORT] IGRF Period / Game Totals showing 2x Period 1 rows

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#639]
Attached JSON as TXT (because Git doesn't like JSON?)
[STATS-2023-03-11_DiamondFiretails_vs_PivotCityRanges.json.txt](https://github.com/rollerderby/scoreboard/files/11610809/STATS-2023-03-11_DiamondFiretails_vs_PivotCityRanges.json.txt)

This is a file from a game earlier in the year that used 5.0.11 - I imported it to check something for a Facebook question, and noticed that it was duplicating the Period 1 row on the IGRF page
![image](https://github.com/rollerderby/scoreboard/assets/28804763/8472f570-172d-44d5-99ee-65e05e9b6481)
When looking at the _Sheets_, they're all correctly showing a single Period 1

I tried another game from the same day, and it imported without an issue, so not sure if this is isolated to the file (Which has not been edited), or if it's a possible wider issue (or caused due to an Operator error...)

**Comment by frank-weinberg** [comment]
This is just a display issue with this table. The row is created twice if the order of some entries in the data is different than I anticipated it to be. Fix will be in 2023.2.

**Comment by bullseye555** [comment]
I figured if it was an actual bug and not caused due to operator error it
would be a simple fix.

Thanks for the prompt action on this, Frank
