### ISSUE TITLE
MAC USERS: Create "mac-launcher.command" file

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#641]
For Mac users who aren't as "CLI strong" as others, there is a methodology to create a launcher that will run by double clicking in Finder.

It's simply to create a mirror of the "scoreboard.sh" file as "scoreboard-mac.command" which then instructs the Mac OS this is a "launcher" and will launch the script for the end-user.

I will do this pull in the coming days.

**Comment by JeneralPain** [comment]
Source of "how-to"
https://stackoverflow.com/questions/3016337/mac-os-x-run-shell-script-from-the-desktop-gui

**Comment by frank-weinberg** [comment]
I'll do this now as I have to release 2023.2 with the clock bugfix.
