### ISSUE TITLE
[FEATURE REQUEST] Officials Pronouns for Announcer Screen

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#644]
Following on from #427 - the request has now been made to have this also available for officials, please

**Comment by frank-weinberg** [comment]
Officials are usually asked their pronouns with the explicit or implicit purpose of them being used by the derby people at the event. As discussed in #427 broadcasting pronouns given in such a context to the world can be problematic, e.g. when someone is out as trans within the community but not to (parts of) their family. - We only added skater pronouns after WFTDA added them to the publicly available charters.

Also we currently have no place where we display officials beyond the input screen for the IGRF data which most people are not using.

**Comment by bullseye555** [comment]
> ... the input screen for the IGRF data which most people are not using.

It's being used quite regularly over here (in that the general scenario is the IGRF is created with officials and teams, and then uploaded - so the Officials are imported from the IGRF data)

>As discussed in #427  broadcasting pronouns given in such a context to the world can be problematic, e.g. when someone is out as trans within the community but not to (parts of) their family. - We only added skater pronouns after WFTDA added them to the publicly available charters.

This is uncommon from my experience, but understand that my experience does not equal what others experience. Acknowledged, and will close this as _Not Planned_ until WFTDA adds pronouns to Officials
