### ISSUE TITLE
Operator screen team editor cuts off on smaller resolutions without providing a scrollbar

### ISSUE THREAD

**Issue by Capt-Brunch** [rollerderby/scoreboard#646]
On the operator controls team entry tab (`/nso/sbo` with Teams selected), once the window width of the browser is less than about 1474px, the display stops scaling and begins being cut off. If the window width drops below about 1360px, the "Remove" buttons are wholly inaccessible for the team on the right. No scrollbar appears in this scenario to provide access to these controls, they're simply inaccessible.

Would request that a horizontal scrollbar not be suppressed on the operator panel for scenarios in which the full width of the content does not fit in the available display resolution.

**Comment by JeneralPain** [comment]
Could you share the spec of the browser/details for me so I can try to mimick the display and see if I can figure out if its a simple CSS problem or something else?

**Comment by bullseye555** [comment]
Use one of our league tablets, Jen - we have the same problem, I just
hadn't gotten to logging it yet

**Comment by JeneralPain** [comment]
@bullseye555 : lets dig into this one Friday night for Speedy/Frank so it's less effort him to solve.

Thanks @Capt-Brunch for the details.

**Comment by Capt-Brunch** [comment]
Sorry for the slow response - work's been a lot. If you haven't already, it can be replicated by simply changing the size of your browser window on any device until it's less than 1474px across, regardless of actual full screen size. We specifically discovered this on a laptop running Chromium on Ubuntu with a screen resolution of 1366x768.

Aaaand then I clicked the wrong button, sorry for the accidental close.

**Comment by webdingens** [comment]
Needs a

```css
#tabsDiv>#TeamsTab {
    overflow-x: auto;
}
```

**Comment by frank-weinberg** [comment]
Thanks for the fix. I will put it in the next release (whenever I get around to making one).
