### ISSUE TITLE
Start and Stop Jam Clock ambiguous with Start and Stop Jam

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#647]
We had a game in which a scoreboard operator, who had moderate experience with prior versions, was using 2023 for the first time. After seven or eight official timeouts to correct scoreboard problems (which were not due to the implementation) we discovered that the user error in question was that the SBO was clicking "start" by the jam clock, rather than clicking "start jam."

However, there are limited reasons to want to start or stop jam clock when it is not running. This can lead to behavior not allowed by the ruleset, such as a jam clock running while the period clock is not. I can only think of one use case for this -- correcting the jam clock time in response to the JT, for example, pausing the clock for a few moments if it started early. For that use case we might consider the words "pause" and "unpause" to reduce ambiguity.

I can't think of a reason to have a jam clock run when a jam is not running, as the display would show lineup time and the jam clock would reset to zero when a jam was started. So we might also consider having "pause/unpause" be the same button ("pause" works if the jam clock is running, and if you click it, it turns into "unpause"). Full control of the jam clock should still be available by clicking on the timestamp.

As an alternative, some text near or on hover of the buttons could also help, but that would likely just be "clutter" for the 99% of NSOs who are aware of the functionality.

I will also note that, although this has not changed since earlier versions, a longtime NSO who may have known this in the past either forgot it, or did not know it because they had been using the correct buttons in the past. A compounding issue was a rather small laptop screen so all controls were not showing simultaneously. But, if every NSO needs to learn this, that's still at least one negative learning experience we could avoid.

Adding this for your consideration.

**Comment by bullseye555** [comment]
My immediate comment to this is that the *Start Stop* buttons for each of
the clocks are hidden by default. You have to choose the  *Show Start Stop
Buttons* button at the top of the screen before they'll actually show

[image: image.png]

**Comment by JeneralPain** [comment]
Correct, by default the “start / stop” buttons for each time clock are hidden by default.So the operator has to take steps to un-hide them Sent from my iPhoneOn 27 Jun 2023, at 14:30, bullseye555 ***@***.***> wrote:﻿
My immediate comment to this is that the *Start Stop* buttons for each of

the clocks are hidden by default. You have to choose the  *Show Start Stop

Buttons* button at the top of the screen before they'll actually show



[image: image.png]

**Comment by frank-weinberg** [comment]
Having the buttons hidden by default was put in exactly to reduce the risk of this happening.

I did think about removing the option to show these buttons and only have them available in the popups. But the scenario you described is one where you wouldn't want to block off all other controls while you adjust the jam clock. And who knows when the next governing body comes up with a weird rule or procedure that needs manual starting/stopping of individual clocks to handle until a new version is ready that properly supports it.

Pause/Unpause doesn't convince me either. But I could see a single button with a text like "Run Clock" that turns green as the clock runs.

**Comment by atkinsonm** [comment]
If I ever have to adjust the jam or period clock to match the JT, I use the "set" screen, which also has increment/decrement options. IMO there's no use for stop/start on individual clocks.
