### ISSUE TITLE
Un-stopping a jam can result in loss of clock sync

### ISSUE THREAD

**Issue by Capt-Brunch** [rollerderby/scoreboard#648]
## Issue

If you stop and then un-stop a jam between seconds, it is possible for the clocks to become unsynced, even if "Sync clocks" is enabled. If this happens, clocks are unsynced for the rest of the game. 

## Replication

To replicate, begin a jam, several seconds later end that jam, attempting to time it between seconds. Several seconds after that, un-end the jam, also between seconds, and note that the clocks are now unsynced. Ending the jam and starting a new one does not resolve this.

This is definitely timing-dependent and can take a couple tries to hit the correct timing to cause the issue, as seen in the video of the issue replication. I have managed to force this on the first un-stop of a jam, however, so I don't believe it's specific to a repeated un-stopping.

Attaching a video of the issue for reference. (As gif for size reasons.)

![unstop_jam_loss_of_sync](https://github.com/rollerderby/scoreboard/assets/1940202/e0972cdf-be22-4dbf-b507-3d545d5d9279)

### Server

- CRG 2023.2
- Running in Docker
- Alpine Linux 3.17
-  OpenJDK 11

### Client

- Windows 11 22H2 (22621.1848)
- Chrome 114.0.5735.199

**Comment by frank-weinberg** [comment]
Thanks for the detailed report.
This might take a bit of effort to fully understand and figure out how to fix and I am currently low on time. So no promises as to when a fix will be available.

**Comment by frank-weinberg** [comment]
I did not fully understand the issue but after my first "maybe that'll help" change I was no longer able to reproduce it. So I'll add that change to 2023.3 and hope it actually fixes it. If it doesn't please reopen.
