### ISSUE TITLE
Score sheet in scoreboard doesn't show which team a timeout was charged to

### ISSUE THREAD

**Issue by goldenapples** [rollerderby/scoreboard#652]
Recently at a tournament I was looking back over the game data to fill out the parts of the statsbook that didn't export conveniently from the scoreboard. (JRDA statsbooks require marking how many timeouts and official reviews were used by each team in each period.)

The "Sheets" section of the scoreboard would be a great place to get that information from, but I found a bug where the Timeout line for both teams' scores sheets just says "Team TO Other team".

![image](https://github.com/rollerderby/scoreboard/assets/665992/0b3774a0-3832-45da-ab02-6da52b5dd645)

**Comment by frank-weinberg** [comment]
As a workaround until the fix is released, you can click edit and open the dropdown. There are two entries "Team TO other team".  If the upper one is selected, it's the left team's TO, the lower one is for the right team. (And for OR you can see which side has a "Retained" button.)
