### ISSUE TITLE
Minor Ruleset Change does not create a usable download file

### ISSUE THREAD

**Issue by spikenheimer** [rollerderby/scoreboard#655]
Made a minor change to Ruleset (Intermission time 10 vs 15) and the downloaded ruleset file does not contain any usable data for import.  attaching json file as txt and screen shot of ruleset editor

[crg-ruleset-HaND-2023.json.txt](https://github.com/rollerderby/scoreboard/files/12285539/crg-ruleset-HaND-2023.json.txt)

<img width="1421" alt="Screenshot 2023-08-07 at 5 12 02 PM" src="https://github.com/rollerderby/scoreboard/assets/8379652/6d7606a5-6e38-4269-82c9-05e91c27cda9">

**Comment by frank-weinberg** [comment]
Fix will be in the next release. If you need the functionality immediately and know how to edit a js file, you can fix your copy by editing line 317 of `html/components/data-tab.js` - instead of `path=ScoreBoard.Game(` it should be `path=ScoreBoard.Rulesets.Ruleset(`.
