### ISSUE TITLE
Filter non-skaters from roster view

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#657]
In the roster view, we currently show all team members. It would be nice if we could filter out "not skating" members to make fit easier for users.

**Comment by atkinsonm** [comment]
I realized I may not be understanding the intention of the "not skating" flag correctly and that's why I'm seeing the behavior I am. #658 is related to that issue, but I would add here that the "not skating" label might be confusing to officials/announcers/others who don't understand that "not skating" is meant to designate alternates.

**Comment by frank-weinberg** [comment]
"Not skating" means exactly that. These skaters not being filtered from the Roster view is just an oversight.
