### ISSUE TITLE
[FEATURE REQUEST] - Autoset colors

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#665]
Now that we have the ability to enter colors via IRGF, it would be nice to be able to automatically update the operator and scoreboard displays to match.  Obviously we can't anticipate every possible weird-ass color someone might enter, and we should still allow users the full customization options they have now.

But if the IGRF says "blue" and "red," it would be nice to have a one-button method to have the operator and scoreboard screens jump to a basic blue and red that are reasonably visible on the average projector setup.

In a similar vein, it might be nice if the selector had quick-set buttons for primary colors, but since that's a third party widget, I'm not sure how easy that would be to change. (Credit to Reed d'Rulz for the suggestion)

**Comment by frank-weinberg** [comment]
I did consider adding something like that when I initially added the uniform color but consciously decided not to:

1) Based on my experience the only colors that are reasonably visible on the average projector setup are white on black or black on white (or combinations very close to that).

2) There are situations where the only feature of the colors you can distinguish is the brightness. If you then have, say, a light green and a dark blue on the scoreboard but a dark green and a light blue on the track, the scoreboard becomes actively misleading.

3) The people that already use the color feature are split between using the foreground, background, or glow for the team color, so a single button won't do.

4) Changing either foreground or background color may necessitate changing the other as well. Combined with 3) you can get ambiguous - is the white background identifying the white team or is the black text identifying the black team?

5) This will almost certainly open the gates for "Can we also add color X?" and "Can color Y be a different shade?" requests.

So overall too much hassle for the gain.

(Note that operator and P/LT screens already use the uniform color as team name by default, already bringing a significant part of the advantage this change is supposed to bring for those positions. (And that works for any weird-ass color someone might enter.))

And as you suspect, changing the selector is not a realistic thing.
