### ISSUE TITLE
Update IGRF Command does not result in any output or exportable Statsbook

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#668]
We have found that ONE GAME out of an tournament weekend so far, you cannot update the IGRF and then export it. All other games are okay, they just simply don't load or do anything. We exported the JSON and imported it to another clean install, replicated the fault. So it's almost like the JSON got broken somewhere.

[Link to JSON](https://drive.google.com/file/d/1pjWwtnctbLKoDTHIuNcnirSywj_CcV15/view?usp=sharing)

**Comment by bullseye555** [comment]
I also get this Java Error when trying to Update the game JSON from @JeneralPain 
![image](https://github.com/rollerderby/scoreboard/assets/28804763/46fdec7f-18b6-42ad-b6b6-b62b49566c3f)

**Comment by JeneralPain** [comment]
We found this.

Was: `%d %G %1 vs. %2 (%s: %S)`
Now: `%d %G %1 vs %2 (%s: %S)`

Export still unhappy but all others seem to be flying along now.

Will leave this open as a potential FEATURE to have inappropriate characters blocked in the filename field.

As we've had instances where someone had 25/09/2023 for the date so file was interpreted as /folder/25/09/23/ and thus failed to export.

**Comment by frank-weinberg** [comment]
That format string has no effect on the file name.

And I can't find a way to input a date in this format through the UI. Only way I can see that could get in is importing a malformed statsbook. -> Gonna filter malformed dates on import.

The problem with the file that can't be exported is that in period 2 there is a zombie timeout (ID e5edbefb-dd0c-4136-91e4-fc6ca7575ec6) that has all fields set to initial values. No idea how that got there, but after deleting it from the JSON manually, I am able to export.
