### ISSUE TITLE
Feature Request: Clear Team of Skaters

### ISSUE THREAD

**Issue by spikenheimer** [rollerderby/scoreboard#670]
as i sit here updating rosters for home teams with a slew of updates, i find it tedious to manually hit remove / tab over to yes for each skater in the roster (i'm just copypasta-ing the whole team back in from a spreadsheet the captains sent) i realize it would be great to be able to just remove all skaters at once.  for sure it probably needs at least 1 maybe 2 confirmation screens but it would be nice.

i'm sure its less trivial to do this than the UI implies but just a thought for a low priority feature enhancement.

**Comment by frank-weinberg** [comment]
Would it be an option to
- create new team
- copy over team info
- delete old team?

**Comment by spikenheimer** [comment]
yeah i think it’s all the various bits of team ‘metadata’ aka icon, alt names and colors that sometimes i miss something. while it’s probably an easier thing to do it’s perilous bc if i forget one thing … compared to just deleting each skater. 
idk 🤷🏻‍♂️ just a thought

**Comment by spikenheimer** [comment]
didn’t mean to close. fat fingered on the phone

**Comment by spikenheimer** [comment]
i realized that part of this is / was i had pre-created the games and it was game week and the rosters were coming in.  and changing.  and the changes were being delivered as whole lists again vs delta changes.  
one other thought i did have was to solve my previous concern about all the metadata was exporting the team json file and deleting all the skater lines out of the json.  but that would still require some finagling of the teams while editing the game.

**Comment by atkinsonm** [comment]
@spikenheimer I took a pass at creating a remove all skaters button. I'd appreciate your feedback on #681 to see if this is the type of thing you were looking for.
