### ISSUE TITLE
[BUG REPORT] - Lineup Time with invalid time

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#676]
Had this raised on the FB group last week and forgot to raise it

![image](https://github.com/rollerderby/scoreboard/assets/28804763/8b4d722c-467a-46b8-81d8-7d2a94c19efd)
JSON & Logs were requested and the following comment was provided

This was in 2023.4, and since undo was used ultimately correct it, I believe the values would have been removed from the logs.
I think part of the mystery is caused by a bug in the time formatting bug. I’m assuming it looks something like:

> minuteString = String(floor(time / 60))
> seconds = time % 60
> secondString = String(seconds)
> If seconds < 10 {� secondString = “0” + secondString
> }
> return minuteString + “:” + secondString

So if time = -1, then floor(time/60) = -1, time % 60 = -1, and since seconds < 10, then a leading zero is added
What I speculate happened is that my finger slipped when starting a jam, causing the stop key to also be hit at approximately the same time. When I saw that the jam hadn’t started I hit start a second time - at that point, the jam didn’t start - everything appeared dead (including the period clock).
At the end of the jam, one of the teams ironically asked for a time out (while we were asking for one from the score table), I hit undo (which was labeled “No Action”), and then a second time (which was also labeled “No Action”) at which point the period clock moved at approximately 5x speed to be and started moving like normal.
It is as if some of the code that handles hitting “stop jam” while the jam isn’t running got confused with the pending “start jam” and put it in an unexpected state.

**Comment by frank-weinberg** [comment]
The formatting is something like the submitter suspects. Just a formatting glitch in the frontend when clock sync causes the time to go a few ms below 0. Would have gone away very quickly without the other issue. (So a bug but not a high priority one.)

And that other issue is an instance of the double clock button behaviour addressed in 2023.5.

**Comment by bullseye555** [comment]
Thanks Frank - suspected this would be an easy(ish) but low priority fix
