### ISSUE TITLE
Count Down in both time out and intermission stating 1440 minutes

### ISSUE THREAD

**Issue by SKuNKW0RXx** [rollerderby/scoreboard#677]
When setting time out (TO) and intermission (IM) times in the rules then selecting count down, the display shows 1440 minutes instead of the time in the rules. When selecting count up, the correct time is used when the clock hits the max time.

This may effect other timers as well, but I only observed it in these instances during our game on Sunday, 3 December.

![Count down](https://github.com/rollerderby/scoreboard/assets/871071/e02f295a-3690-4860-a3b9-3821842dc807)

**Comment by frank-weinberg** [comment]
For timeouts the time in the rules only applies to team timeouts. But the clock applies to all types of timeout. So we can't just set the max time to the time of a team timeout as that would cause the clock to potentially run out on official timeouts or reviews. 
Setting the timeout clock to count down just is not very useful and primarily there so it doesn't need special handling in the code.

The intermission clock should go to the expected time when the intermission starts. Before the game the max time is set to a high value, so it's easy to manually set up Time to Derby.
