### ISSUE TITLE
[FEATURE REQUEST] Team view

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#683]
A roster display and a penalty whiteboard display already exist. However, these both show data for both teams. It could be nice to have a "team display" that shows roster and penalty information for skaters from a single team in one view. This could, for example, give bench staff the ability to see read-only information about their skaters.

Relates to #541

**Comment by frank-weinberg** [comment]
The penalty whiteboard display is already used for this purpose. In what way would a single team version add value in your opinion? Based on how hardware whiteboards were used in the past, I don't see a reason to limit bench staff to only their team's info.

**Comment by atkinsonm** [comment]
My intention wouldn't be to limit their view. On the contrary I thought a single-team view might be more hardware-flexible for bench staff with limited screen real estate i.e. smartphones and small tablets.

But after consulting Facebook it seems like what exists already is good enough between the penalty whiteboard, roster display, and jamstats. I'll close as unplanned.
