### ISSUE TITLE
GitHub discussions

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#684]
Can a repository maintainer enable the discussions feature for this repository? https://docs.github.com/en/discussions/quickstart

I think it'd be useful for non-issue discussions, for example a place for contributors to introduce themselves (my GitHub persona doesn't really reflect my derby persona, so if I met any of you at a tournament I'd probably not know) or for other longer-form discussions that aren't always suitable for single-threaded GitHub comments.

**Comment by geoff-quinby** [comment]
Was there any update to this?

I'm looking for ways to sync up with contributors and I'm not sure where to look. I'm probably just not looking in the right place 😅

**Comment by atkinsonm** [comment]
@frank-weinberg are you a repository maintainer/admin or do you know who is?

**Comment by JeneralPain** [comment]
I may have forgotten to keep on top of this.Sent from my iPhoneOn 12 Mar 2024, at 00:53, Michael Atkinson ***@***.***> wrote:﻿
@frank-weinberg are you a repository maintainer/admin or do you know who is?

**Comment by geoff-quinby** [comment]
In the meantime, is there a different place where discussions are happening?

**Comment by goldenapples** [comment]
Following, as I'd like to keep up with any discussions that happen and find opportunities to contribute.

**Comment by JeneralPain** [comment]
Not really.The core writing developer does not use Facebook. We do have a slack server but I haven’t been able to get him on it (though I haven’t exactly tried hard on it). Sent from my iPhoneOn 16 Mar 2024, at 04:04, Nathaniel Taintor ***@***.***> wrote:﻿
Following, as I'd like to keep up with any discussions that happen and find opportunities to contribute.

**Comment by atkinsonm** [comment]
How does one get access to the Slack server? 👀

**Comment by geoff-quinby** [comment]
> How does one get access to the Slack server? 👀

Would also love to be a part of this, if I can.

**Comment by JeneralPain** [comment]
https://join.slack.com/t/crgscoreboard/shared_invite/zt-2f5jez0g6-WyNiNb9K5sWFOYzpr2dilg

**Comment by annamontare-edu** [comment]
@JeneralPain  is the slack still active?

**Comment by bullseye555** [comment]
Yep - not a lot going on, but it's there

**Comment by annamontare-edu** [comment]
Could I get an invite?

**Comment by bullseye555** [comment]
Use this link :D

https://join.slack.com/t/crgscoreboard/shared_invite/zt-2la2nccb6-GjQP5ZnDO~d8an87xE5djQ

**Comment by atkinsonm** [comment]
Closing since between GitHub issues, Slack, and Facebook it seems like there are plenty of suitable ways to hold discussions
