### ISSUE TITLE
Investigate failure of Google Docs/Drive edited stats book.

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#688]
** Description of fault/bug **
When you import Statsbooks that were edited in Google Drive/Docs they fail to import.

**To Reproduce**
Import one you exported from Google Drive/Docs

**Expected behavior**
They should import without error.

**Screenshots**
None

**Version:**
The version of the scoreboard you were running 2023.5

**If this issue occurred on a computer, please complete the following information:**
Affects all users on all system types.

**If this issue occurred on a smartphone, tablet, or other device, please complete the following information:**
NA

**Additional context**
NA

**Comment by frank-weinberg** [comment]
I don't consider this a bug in CRG, as we do not officially support statsbooks that have run through random converters.

**Comment by goldenapples** [comment]
When I'm running the scoreboard for JRDA games where the statsbook file is a Google Sheets file by default, importing prepared statsbooks works fine. Is the bug you're reporting specific to statsbooks that originate in Excel, but are edited in Google Sheets?

**Comment by JeneralPain** [comment]
Closing as deeper dive required - Time slipped away and with multiple revisions and releases by the group since then, I will need to re-investigate fully before this becomes a truely viable bug.
