### ISSUE TITLE
[BUG] Start mid-game functionality does not set some values correctly

### ISSUE THREAD

**Issue by goldenapples** [rollerderby/scoreboard#693]
**Describe the bug**
In the current release version, attempting to start a game mid-game does not currently handle some of the input values:
* "Period" - the game will be started in period 1, even if 2 is selected here.
* "Timeouts Taken" and "Reviews Taken" - no timeouts or official reviews will be created, even if a non-zero value is selected for these fields.
* "Prior Jam" - although the label says "prior jam", the scoreboard will actually be started with this value as the _next_ jam.

**To Reproduce**
1. Click the 'Start New Game' button in the tab bar, then click "Start Mid-Game" in the modal to show the form.
2. Set Period to 2.
3. Set "Prior Jam" to 10.
4. Set 1 timeout taken for each team.
5. Start the game

![image](https://github.com/rollerderby/scoreboard/assets/665992/af599094-07c9-41e4-b16f-148d4c3a8197)

**Expected behavior**
I would expect this to start the game in period 2, jam 11, with each team having 2 timeouts remaining. Instead, it starts the game in period 1, jam 10, and each time has all three timeouts available.

![image](https://github.com/rollerderby/scoreboard/assets/665992/252101a5-b5e0-44f2-893a-f6eb5b3e9234)

**Version:**
v2023.5

**NOTE:** This behavior was working at one point. Running a git bisect, it looks like something in #630 broke some of the start midgame functionality.

**Comment by frank-weinberg** [comment]
Thanks for the pointer to the PR - looking at what that changed there, I think I know what causes the bug.
