### ISSUE TITLE
Separate Alternate Names functionality between Penalty Whiteboard Screen and PLT Screen

### ISSUE THREAD

**Issue by jlsanman** [rollerderby/scoreboard#694]
At events where I have a monitor behind the penalty box displaying the Penalty Whiteboard Display, box officials have asked if I could change the names of the teams listed at the top from the team names to the team colors. When I do that, it also changes the names at the top of the PLT screens as well.  The same goes with PLTs asking for alternate names and the change confusing the box with a PWB display. 

Can it be possible to separate the alternate name function of PWB from PLT?  That way PLT is not affected by a name change that is requested by those viewing PWB and visa versa.

**Comment by atkinsonm** [comment]
Just so I'm following, are the PLTs requesting an alternate name that's different from the team name and different from the colors the PB is requesting (three names total)?

**Comment by jlsanman** [comment]
For example, say the PLTs want the colors at the top of their screen, but the PB want to keep the team names.  Right now, if you go in to the alternate name area, the option "whiteboard (Penalty Whiteboard)" is connected to the PLT screens and the PWB display screen.  So, if I change it for the PLTs, it also changes it for PWB. 

Maybe the only thing that needs to happen is that a type called "Penalty Lineup" be added so that you can provide an alternate name just to the PLT screen.

**Comment by frank-weinberg** [comment]
That would be a bug. PLT should not be using the "whiteboard" alternate name but the "operator" one.

**Comment by jlsanman** [comment]
Okay, but what if PLT still wants a different set of names from what the SBO wants? Why can't PLT have the option of having alternate names that they want?

**Comment by frank-weinberg** [comment]
The historic reason is that this was most commonly used to enter the uniform color. And separating the alt names would have meant entering the colors twice in that common use case.
Now the reason is that before today nobody made a case that it would be worth the effort.
But I have now added "plt" and "box" alternate names to v2025.

**Comment by jlsanman** [comment]
Thanks.  I appreciate all of the hard work you and the others do.
