### ISSUE TITLE
Caps Lock warning

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#697]
This comes from the Facebook group

**Is your feature request related to a problem? Please describe.**
No problem with CRG

**Describe the solution you'd like**
For there to be a warning on the screen indicating that the Caps Lock key is enabled (and thus, hot-keys may not function as expected)

**Describe alternatives you've considered**
N/A

**Additional context**
There have been a couple of suggestions on the initial post suggestion where to have this
One is: 
![image](https://github.com/rollerderby/scoreboard/assets/28804763/8cf97c56-62e2-4f00-88af-97c76349bc8d)

The other is to have it up next to operator name (this request was to also have it configurable, but there has only been one request to have it configurable)

**Comment by frank-weinberg** [comment]
How about next to the tabs?

![image](https://github.com/rollerderby/scoreboard/assets/34135287/371c63d7-2cba-4757-bbf2-ee9432a2a6e0)

(This screenshot is from 2023.6 - closing as done years ago)

**Comment by bullseye555** [comment]
Thanks for the prompt response @frank-weinberg - have never noticed this before (probably because I've never had Caps Lock on before...)
