### ISSUE TITLE
Interactive Overlay (2017 Version)

### ISSUE THREAD

**Issue by jaredquinn** [rollerderby/scoreboard#7]
Complete new DDTV 2017 "interactive" overlay with Roster & Penalty support.

The overlay has been redesigned and re-coded for better display on broadcast devices (supporting HD/720 & FullHD/1080), configurable sizing, fonts and positioning with more flexible and forgiving CSS than the 2015 version.

![image](https://cloud.githubusercontent.com/assets/151566/25783254/68601d66-339c-11e7-9094-b8218c5b4fd4.png)

**Comment by brian-brazil** [comment]
This is superceded.
