### ISSUE TITLE
[BUG] Groundhog Day

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#704]
Reported via Facebook from Amy Feral Fouler - replication hasn't yet been attempted

**Describe the bug**
CRG repeats a jam. In the example given, P2J6 repeats itself 

Footage here
https://www.youtube.com/live/2Sy7uns5xHo?si=3W37FgF1Bkllim2I (start at 3:32:05 to see the end of the first J6, line up time, and start of next J6) 

**Version:**
 2023.5

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: [e.g. Windows 11, Mac 14.2.1]

Unknown. Have requested and will advise once received

Logs & JSON files have also been requested

**Comment by frank-weinberg** [comment]
Watching the footage I notice that the first Jam 6 is started 5 seconds late on the scoreboard. Any chance we can get info on what went on there? I'm wondering if there was some kind of malfunction and the SBO then started the Jam using the Start button on the Jam clock instead of the Start Jam button. That could explain the double Jam 6.

**Comment by bullseye555** [comment]
I've asked for more details and will pass on when received

**Comment by bullseye555** [comment]
No malfunction

SBO was running the score desk solo and was distracted by a late blocker trying to get on track and being returned to bench by the HR. No funky business, just a late start to the jam

Other info

> For the Groundhog day Jam - how did that display on the ePLT/Scorekeeper screens? Was there anything done to alter it, or was it just left as-is and what's in the JSON is what was on the screen(s) ?

ePLT behaved as normal, I was PLT for one of the teams and I didn't even notice the duplicate jam number. I was allowed to put lineups in as normal. On the feed you can see that they are a different lineup from the previous jam. The output from the game data retained the original J6 lineup and score but not the 2nd J6 lineup and score.

>Device details

Amy believes it was running Windows 11 and the most current Java

>Log and JSON files

Amy notes: the game files seem to have reverted to "prepared" state, there is no data for that game. It shows 2 periods but only 1 jam with no data in period 2
[GRD Game 6-1-2024 crg.log](https://github.com/user-attachments/files/15527332/GRD.Game.6-1-2024.crg.log)
[STATS-2024-06-01_GorgeRollerDerbyAllStars_vs_CherryCityRollerDerby8WheelAssassins_2.json](https://github.com/user-attachments/files/15527333/STATS-2024-06-01_GorgeRollerDerbyAllStars_vs_CherryCityRollerDerby8WheelAssassins_2.json)

**Comment by frank-weinberg** [comment]
The first Exception in that log shows why starting the timeout failed: The preceding Jam (the second J6) had not been added to the period. But after hours of digging through the code and watching the whole period up to the incident, I still have no idea how the hell that could have happened.

At least this is more insight than I have had for prior incidents where the internal state got garbaged. I'll get back to this when I have more time.

**Comment by frank-weinberg** [comment]
Steps to reproduce:

1. Start a Jam
2. Before the JSON update from the jam start has reached the tablet make a lineup change
3. End the jam and start another one. That one will have the same number as the one from step 1 (this bug)
4. After that jam start a timeout

BOOM (#705, #709, European Regionals game 8)


(Fix is coming)

**Comment by bullseye555** [comment]
😮😮 Great detective work, Speedy!!

**Comment by bullseye555** [comment]
@frank-weinberg I mentioned the steps for this bug (and advice to not have PLT making updates in the 2-3 seconds either side of Jam Start to ensure sync), and Sam Skipsey mentioned that one of they times they saw the **P2 Upcoming** bug they were _NOT_ using ePLT at the time

To quote
> no lineup changes were made in the PLT tablets at all for that game (they were, briefly, for a previous game, before that game started, to check PLT was working & they were connected).

**Comment by frank-weinberg** [comment]
The same race condition can also be triggered by other updates. This one was just the first one I found. The fix should cover them all.
