### ISSUE TITLE
[BUG] Setting Color not working - v2025-beta1

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#706]
Adding a Color via the team tabs is not working correctly.

**To Reproduce**
1. Go to Teams Tab
2. Click on Colors
3. add e.g operator
4. it adds undefined instead of the operator tag

**Version:**
The version of the scoreboard you were running  v2025-beta1

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Mac 14.5
 - safari 17.5, firefox 126.0.1
<img width="841" alt="Bildschirmfoto 2024-06-03 um 13 32 17" src="https://github.com/rollerderby/scoreboard/assets/58275718/196f0819-89c3-4e11-bdc3-33bd3c3c2165">

**Comment by frank-weinberg** [comment]
Thanks for reporting, will be fixed in next release.
If you want to implement the fix on your copy before that, change `children` to `find` in line 273 of `html/components/team-editor/index.js`
