### ISSUE TITLE
[Feature Request] Import/Export SBO Settings

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#708]
**Is your feature request related to a problem? Please describe.**

As an SBO who travels to different leagues and often uses the host team's provided equipment, I want to export my hotkeys and be able to import them to the scoreboard running on a different machine so I can save a few minutes during SBO setup.

**Describe the solution you'd like**

Export hotkeys to a file, transport somehow e.g. on a flash drive, import to another instance of the scoreboard

**Describe alternatives you've considered**

Redoing hotkeys by hand every time

**Additional context**

**Comment by bullseye555** [comment]
@atkinsonm 

This is already possible from the _Games / Teams / Rulesets_ screen

![image](https://github.com/rollerderby/scoreboard/assets/28804763/2f59a8b3-19db-4e1d-a236-bafdfe4afc56)


_Download_ the specific operator, and then you can upload it as a JSON to the host's device

**Comment by atkinsonm** [comment]
Ah thanks. I had a feeling it was
