### ISSUE TITLE
 V2025-Beta1 - Support Portrait orientation in JT Mobile Control

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#713]
**Describe the bug**
When rotating from Landscape to Portrait, the buttons on the JT control don't scale/reposition correctly

**To Reproduce**
1. Open the JT Controls on a mobile device
2. Orientate to Portrait mode
3. See the issue
4. Orientate to Landscape mode
5. See resolution

**Expected behavior**
When in portrait mode, the buttons scale or reposition as appropriate for a the screen size

**Screenshots**
Landscape:
![Screenshot_20240617-144419](https://github.com/rollerderby/scoreboard/assets/28804763/1da62768-535a-4681-a593-ac23d713a224)

Portrait:
![Screenshot_20240617-144416](https://github.com/rollerderby/scoreboard/assets/28804763/1d2e4fdf-8065-4311-aaf4-54c4c48c3e40)

**Version:** 2025-beta1

**If this issue occurred on a smartphone, tablet, or other device, please complete the following information:**
 - Device: Pixel 8a
 - OS: Android 14 (Build UD2A.240505.001]
 - Browser: Chrome
 - Version: 126.0.6478.71

**Comment by frank-weinberg** [comment]
This is a conscious limitation as I couldn't come up with a good layout that works in portrait mode. Suggestions welcome.

**Comment by bullseye555** [comment]
Noted - I'll have a think and mock something up

**Comment by reflexdd** [comment]
I made some Mockup Screens. In some cases this would mean that we would have to switch from the buttons we have now from the SBO-Panel. 

I think the most important thing is to have the Start/ Stop Button at the same place when you holding the phone and therfore they should also be a bit bigger then the rest. We could also hide buttons which don't have a function in a particular state.

<img width="1125" alt="01-Jam-Start@2x" src="https://github.com/user-attachments/assets/0a391de4-5e05-4d95-814a-faee62fd39ec">
<img width="1125" alt="02-Jam-Started@2x" src="https://github.com/user-attachments/assets/7ed61bdf-4fb4-4e31-bdab-6eed2521516c">
<img width="1125" alt="03-Jam-Timeout@2x" src="https://github.com/user-attachments/assets/79c8b5b3-2100-4c53-a9db-da38ac7535f7">
<img width="1125" alt="04-Undo-Jam-Started@2x" src="https://github.com/user-attachments/assets/650df79d-c234-4405-824b-69fc05ca9c1a">

**Comment by frank-weinberg** [comment]
I don't think the "Start Jam" button is as important since you always know ahead of time that you need to press it. It should be large enough to consistently be hit without looking, but it can be in a place where you have to pre-position your finger ahead of time.

"Stop Jam" and "Timeout" are the buttons that you may need to press as a reaction to other people blowing their whistle, so these need to be in a consistent position that is easy to find and hit consistently. Which to me means they have to be big and placed in corners.

I'd also avoid moving things around as much as possible and would rather have all clock buttons visible at all times (except for the manual toggle for the Undo button).

So going with your basic layout it'd be "Timeout" and "Stop Jam" in the bottom corners in some order, "Start Jam" above, "Undo" above that, then timeout types and clocks.

And then I'm wondering if we should keep everything in position when the screen rotates in order to avoid people getting caught off guard by autorotate. (If that can be done with reasonable effort.)

**Comment by reflexdd** [comment]
Portrait Mode works good from what I see. What JT might get confused is the count of Lineup and Timeout in their screen. From the regular Scoreboard view JTs are used to see the current/actual Jam number. Now we have the number of Lineups/Timeouts in total shown. This might be confusing people. Any thoughts on this?

**Comment by bullseye555** [comment]
I'd be inclined to say it should reflect what a JT is used to seeing, as this would make an easier transition for JT's moving to eJT (rather than SBO's moving to eJT)

Also - the portrait mode seems to be doing weird things on my Pixel 8. When in Portrait, part of the controls are off the edge, and the grey background only covers half the screen
![Screenshot_20240721-194203](https://github.com/user-attachments/assets/f3f94f7c-7b50-495f-8b7c-b6898aad1a65)
![Screenshot_20240721-194152](https://github.com/user-attachments/assets/d83a527e-0a97-4d72-ac06-27ad06808ac3)

On a tablet (Samsung Galaxy Tab S5e) the controls are all there, but the background again only has half the screen

![Screenshot_20240721-194623_Chrome](https://github.com/user-attachments/assets/26a51be8-4b83-431b-a14b-bb085fe68137)
![Screenshot_20240721-194633_Chrome](https://github.com/user-attachments/assets/5fc84462-9c5b-4ab1-a2fa-493db93163d5)

**Comment by reflexdd** [comment]
this looks like you haven't downloaded the three changed JT files. The screens look different now.

**Comment by reflexdd** [comment]
they should look like 
<img width="655" alt="JT-1" src="https://github.com/user-attachments/assets/2dd556ee-1686-44e9-8b0a-05dccf662f7c">
<img width="1862" alt="JT-2" src="https://github.com/user-attachments/assets/2913aa3d-b77b-4358-a48e-66ce3f4630f8">

**Comment by bullseye555** [comment]
Thanks @reflexdd - I thought they were part of the current dev branch. My bad!

**Comment by bullseye555** [comment]
Got em - on review of how it looks, I'm happy with how it's displaying
Jam 5 of Period 2 is correctly showing, it's the Timeout and Lineup counts that are an incremental count - I think from a change management perspective, this is easy enough to explain and don't think any further changes need to go in

What I did find was that on occasion (I wasn't able to consistently reproduce it) was that the layout would flash-change (usually less than half a second), but sometimes it would stick like this
![Screenshot_20240721-204539](https://github.com/user-attachments/assets/149818bb-6bfb-498a-93a2-7bc1b85d79ed)
But another clock action (start/stop/timeout/undo etc)  or a page refresh would resolve it
