### ISSUE TITLE
Color-vision deficiency accessible skin

### ISSUE THREAD

**Issue by awsxdr** [rollerderby/scoreboard#718]
As a scoreboard user with color-vision deficiency, I find that the new skin in the beta makes buttons and some pieces of text difficult to see. The old skin was generally high contrast and very clear.

I would appreciate an option to either revert to the old color scheme or to a new high-contrast color scheme. I worry that without this the scoreboard software will be hard for certain officials to use, especially if they're not already familiar with the software.

*Examples*

The green borders aren't immediately obvious and require active looking for
![image](https://github.com/rollerderby/scoreboard/assets/13380602/e31bf9e2-842b-49af-9671-3813df2bb661)

I only noticed this tick when looking very closely for these examples
![image](https://github.com/rollerderby/scoreboard/assets/13380602/1f46e94e-bd2a-44bd-b66e-f10d3c54c289)

The text on this button is very difficult to see (I think it was the same in the old skin, to be fair)
![image](https://github.com/rollerderby/scoreboard/assets/13380602/78207456-7335-4e12-9413-6fda98f89028)

This text is all readable (for me) but would be easier with more contrast
![image](https://github.com/rollerderby/scoreboard/assets/13380602/18f4f60d-b0df-497a-835f-acecf6a2ba90)

**Comment by frank-weinberg** [comment]
Thank you for this input. This is an area where my knowledge is very shallow and thus I appreciate input that helps me improve things.

And while adding the option to have different themes is something I hope to introduce in the not-too-far future (but probably not for the release of v2025), I believe that the default theme should be as accessible as it can be without major compromises.

So I tried to make adjustments based on the examples you gave:

![image](https://github.com/rollerderby/scoreboard/assets/34135287/705d0c1e-2136-48e5-b259-ec31a74cadb8)
![image](https://github.com/rollerderby/scoreboard/assets/34135287/63a488b8-4433-40d0-bd40-abaa9f09e60f)
![image](https://github.com/rollerderby/scoreboard/assets/34135287/e7733a43-c685-4d9b-8f7b-f4fd18df2f46)
![image](https://github.com/rollerderby/scoreboard/assets/34135287/2f49f3a7-98b8-484e-b80e-a280fae3eea8)

(In general with these adjustments all text should be black, white, or very occasionally red on white.)

The one example I don't think I'm able to improve are the green borders: Having them in an immediate state between default button design and fully green was the only way we found that had a high enough chance of being understood as meaning "This was selected earlier but it is not selected now." And if I have to err between the marking not being noticed at all and there being confusion as to which skater is currently selected, the latter would be a bigger problem by far. So I'll err on the side of the border standing out less.

But if you have a suggestion for this one or notice any other examples, please bring them up.

Addendum: If you know how to edit the files, you can copy the changes from the linked pull request into your local copy of CRG 2025-beta and reload your browser to use them right away. No compile or anything required.

**Comment by awsxdr** [comment]
Thanks for the quick response 🙂

Accessibility is hard and the unfortunate thing is that a fix that works for me could make it worse for others. The changes above do make things a lot clearer for me, though, and I think they should work for most people. I'll pull your branch and check them out.

Your comment about making the intent of the borders obvious is definitely fair and I'm sure I'll adapt to them.

I've made some changes to `common.css` myself which work for me and I'll probably just apply that to the software for now when I can. The general guidelines I used were to not use gradients, to use white text on darker backgrounds, and to have all backgrounds be either dark or light - nothing in the middle.

The result looks like this:
![image](https://github.com/rollerderby/scoreboard/assets/13380602/bf3a624a-4d87-4762-bbf5-f4c5fa0d7ba7)

**Comment by frank-weinberg** [comment]
Interesting. I did look at a light background like this but was worried that the buttons would not stand out enough with it.

Removing gradients obviously helps with making the labels more readable but it does make the buttons less buttony and quite bland. I guess this is exactly the kind of thing where a per screen-instance option (or theme selection) would be very useful.

And I'm happy to see that adjusting the looks of the screens seems to be reasonably accessible with the new architecture.
