### ISSUE TITLE
[BUG] 2025_beta2: Scoreboard Load-Screen fades from all screens to Scoreboard

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#724]
**Describe the bug**
When opening the Scorboard-Screen the Screen fades from all Screenpages (Scoreboard, Image, Penalty Whiteboard) to the pre-defined View. With the default Setting it fades form the US flag, Penalty View and Scoreboard to the Scoreboard View.

**To Reproduce**
1. Go to Main Page
2. Click on Main Scoreboard

**Expected behavior**
Fade in from black to the selected View

**Screenshots**
![load-Screen-01](https://github.com/rollerderby/scoreboard/assets/58275718/f65d3727-5aa4-4edb-b4d7-be58d34e2abe)
![load-Screen-02](https://github.com/rollerderby/scoreboard/assets/58275718/08c1663c-c1f0-4240-853d-af073c3a257e)

**Version:**
2025_beta2

**Additional context**
thats not an urgent bug but maybe a nice-to have adjustment

**Comment by frank-weinberg** [comment]
That US flag can't be the current defaults - CRG doesn't even include a US flag since version 5. But I see the general behaviour.
