### ISSUE TITLE
Add Color Information to Penaltybox Timer Screen

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#728]
**Is your feature request related to a problem? Please describe.**
Imagine you have  two skaters with the same number in each team and each of them is reporting to the box.
At the moment you don't have a visual information which skater can be released first.
<img width="1094" alt="screen-pbt" src="https://github.com/rollerderby/scoreboard/assets/58275718/64f8c1c7-bd54-4eb9-be92-e74d6e70400f">

**Describe the solution you'd like**
Add a Color information to the skater number. e.g. Number with teamcolor Background
![screen-PBT-colored](https://github.com/rollerderby/scoreboard/assets/58275718/60e15a77-ae71-41d2-8edd-1bc9d0f3d504)

**Describe alternatives you've considered**
add the color as word somewhere in front of the Number

**Comment by frank-weinberg** [comment]
Did you enter uniform colors? For me it looks like this:
![Screenshot_20240702_190400](https://github.com/rollerderby/scoreboard/assets/34135287/58f5137d-193c-4e02-a44a-01bba95ef8b0)
(Allowing colors in addition is still a good idea.)

**Comment by reflexdd** [comment]
ah you are right. I didn't figured out that this has to be set. 
But maybe a color supported background could even support people who need a more visualized information.

**Comment by frank-weinberg** [comment]
It should use AlternateName(box), UniformColor, TeamName in this order of priority. So presumably one of the early ones is set to an empty string in your case.
