### ISSUE TITLE
[BUG] Older browsers not working

### ISSUE THREAD

**Issue by blauwblaatje** [rollerderby/scoreboard#731]
**Describe the bug**
We are using older iPads, they have been functioning fine for ePLT with v2023. However, with the frontend update of v2025 it's not working anymore. It looks like the Option Editor is not function as it should. It just stays how you see it on the screenshot. I cannot press a button and the Option Editor stays at the front. 

**To Reproduce**
Open any input method and the option editor is completely on the screen.

**Expected behavior**
Being able to use ePLT ;) 

**Screenshots**
Sorry for the photo of the screen, I had a hard time creating a screenshot with the tablet :) 
![IMG20240706164048-3](https://github.com/rollerderby/scoreboard/assets/23704602/73da54c6-54bc-463d-b1af-8c45998abdef)

**Version:**
2025beta2

**If this issue occurred on a smartphone, tablet, or other device, please complete the following information:**
- iPad 3rd Generation
- OS 9.3.6
- Safari 9
Unfortunately I can't upgrade Safari or install a newer browser. :(  

**Additional context**
I completely understand if older browsers aren't supported anymore.
It would be a shame as old tablets are still fine for such a thing and I don't want to create eWaste.

**Comment by frank-weinberg** [comment]
I do not have any iOS devices available. Let alone old ones. Thus I am unable to debug this issue.
If anyone has the necessary resources to figure out what function is not working, I may be able to come up with a way to work around the limitations. If someone can even provide a fix, I'll happily merge it. But without support, I don't see a way I can do anything here.

**Comment by JeneralPain** [comment]
Whilst I agree and support "eWaste prevention", we've discovered the iPads we have with the same problem. We couldn't even install Chrome or Firefox because the iOS version was too far behind.

I tried to cheat and see if I could hide it behind an NGINX Reverse proxy, but it also failed.

It isn't easy to support older hardware because they have so many security inadequacies, so they are being phased out by the vendors in question.

**Comment by blauwblaatje** [comment]
I agree with @JeneralPain that it's not easy to keep everything working for older tablets, especially when there's no new (safe) software anymore.  

My $0.02 is that even though I would really like to find out what the issue is (but I have no idea how to debug it on a tablet...)  it's perfectly fine to decide that older versions aren't supported anymore.  

Maybe we should crowdsource a software/hardware compatibility list?

**Comment by frank-weinberg** [comment]
That list might be a useful resource, if it gets enough contributions. To start it, you could create a page on the [Wiki](https://github.com/rollerderby/scoreboard/wiki).

**Comment by blauwblaatje** [comment]
Side note,  I was hoping that the IWB view would still work, as it doesn't have the popup. And then I could use the old tablets as a display for benches and/or other people that are interested (THO table, announcers...). 

Unfortunately IWB gives a blank page :(   

Just curious, would it be possible to create a "simple" display, or will that be harder to maintain?  Alternative would probably be using an external application like Jamstats, which might also work for me.

(Note, this post is mostly informative. If I'm able to find why it's not showing, I'll report it)

**Comment by webdingens** [comment]
Tested on virtual iOS 9.3, these errors were thrown:

![image](https://github.com/user-attachments/assets/030c925f-d232-4c81-a9c8-c890718c67b9)

`let` is only supported from iOS 10 upwards. `const` seems to have problems with strict mode. (checked on caniuse.com)
This would need a build step like running Babel7 + corejs 3 compiling back to ES5 to support iOS 9: https://compat-table.github.io/compat-table/es6/

**Comment by frank-weinberg** [comment]
Wow, didn't see that coming.
Looking for other ES6 features I know I'm using, => seems to also be a problem on iOS 9.
At least var, let, and => are rather straightforward to replace. I don't really like the thought of going back to var nor that of actually doing the conversion, but at least it is doable with reasonable effort.

**Comment by atkinsonm** [comment]
@webdingens nice find! Any tips on how to run tests on virtual devices? If we could add some frontend tests, we could come up with a list of "officially" supported OS versions and browsers.

**Comment by frank-weinberg** [comment]
What would also be nice to know is what devices people actually use (and when some old devices stop being used), so we can eventually start using newer features. But I guess the only way to find that out is dropping support and seeing if there are complaints.

**Comment by webdingens** [comment]
I used [lambdatest.com](https://www.lambdatest.com/) for testing, because I have a subscription for that.

Bundlerwise Parcel seems promising, as it's the only one supporting multiple html files as entry point for bundles out of the box and inline scripts with es5 fallback are mentioned: https://parceljs.org/features/targets/
Without import/export you can also do a file by file babel transpilation using a node script. For inline scripts in html the big LLM suggests `html-minifier-terser`, where the script/style blocks are handled with callbacks based on their types.

CSS grid btw. also not working on iOS 9. But it just stacks the content as fallback.
