### ISSUE TITLE
[BUG] PBT Edit/Preselect unexpected behaviour

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#733]
**Describe the bug**
Let's say we have several skaters with the similar numbers on one team skating in jam.
112 is the Jammer having the helmet cover in their hand and coming to the box. 
PB-Timer thinks it's Skater 12 and pushes the Pre-Select Button 12. Now as 112 is coming closer PB-Timer notices that 12 is 112 and tries to change the pre-Selected Number from 12 to 112 in the Pop-up. This push affects the whole Lineup. Now 112 is marked as Blocker and 12 is deleted from the Lineup and  we also don't have a Jammer anymore. Also the Cancel Button wouldn't help as all changes are made immediately and can't be reversed bv pushing the Cancel Button

The same behavior can be reproduced by several different occasions. When we have a skater marked as seated it should not be allowed to push the same Skater in the Edit/Pre-Select section again. This could happen for the same reasons before and instead of using the "Change" Button PB-Timer could think they could change the skater by pressing the button again.

**Expected behavior**
1. Don't allow pressing the pre-select button when that skater already is marked as seated
2. Maybe separate the Skater-Number Section in the Pop-Up into two rows. One would only show the Skaters who are in the lineup and the second one the remaining roster. The First row would then be handled the same way like with the change button, so only the penalty assignment would be changed and not the lineup itself

**Screenshots**
<img width="892" alt="pbt-1" src="https://github.com/rollerderby/scoreboard/assets/58275718/4a152c81-36ad-4ada-b999-5e8de6077bf9">
<img width="708" alt="pbt-2" src="https://github.com/rollerderby/scoreboard/assets/58275718/fb80d863-412a-4325-bfd6-78ab078bba8d">
<img width="710" alt="pbt-3" src="https://github.com/rollerderby/scoreboard/assets/58275718/a4e4942a-6901-4a74-9bc4-98d6eb215e3c">
<img width="895" alt="pbt-4" src="https://github.com/rollerderby/scoreboard/assets/58275718/6907f9de-f0fd-463d-9534-2a9edc8d8f3d">
<img width="766" alt="pbt-5" src="https://github.com/rollerderby/scoreboard/assets/58275718/ed577ce6-2471-4c6b-aaac-59cda921f654">

**Version:**
2025.beta2

**Additional context**
I know that's not a easy one to be resolved and we would need a GUI-expert here in making it more intuitive for people.
But it's already quite good working.

**Comment by frank-weinberg** [comment]
I have gone a different way: Unless no skater is selected yet, the row of buttons is hidden behind an "Edit Lineup" button.
Disallowing the pre-select button is not an option as this is the only place where the operator can mark that a skater left early.

**Comment by reflexdd** [comment]
OK great.
is there something which prevents us having the Left early button right next to the other buttons. This way the PBT could mark this faster without having to got via a Pop up
<img width="504" alt="pbt-6" src="https://github.com/rollerderby/scoreboard/assets/58275718/a3be82df-94eb-4a34-b1b4-c01a84d8a441">
