### ISSUE TITLE
[BUG] Creating a game / Team color adding not consistent to editing a game

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#736]
**Describe the bug**
If you have pre-defined teams with pre-defined colors and would like to create a new game, then the adding a color section is behaving different to the editing a game tab.

**To Reproduce**
1. add some colors in the Gamedata/Teams/Edit-Team-Section
<img width="1791" alt="team-0" src="https://github.com/user-attachments/assets/bf682779-6286-41d2-a9ea-a15e6634d9d7">

2. add a new Game in the Gamedata-Section, go to Teams-Tab and select the team with the pre-defined Color
<img width="900" alt="team-1" src="https://github.com/user-attachments/assets/2a47dee0-dff2-4f2b-a457-b6064ee34bca">
The pre-defined Colors are not shown

3. Adding e.g. Black again as color
<img width="893" alt="team-2" src="https://github.com/user-attachments/assets/0f970bbc-f411-4d64-b3c5-2d1ddb81dbd1">

leads to an unexpected behaviour
<img width="895" alt="team-3" src="https://github.com/user-attachments/assets/dc690408-c28f-456f-a757-920f558b4d86">

**Expected behavior**
When selecting a team the predefined Colors should be shown as when you later edit a Game 
<img width="893" alt="team-4" src="https://github.com/user-attachments/assets/4e8e1b2b-aecb-4e24-a805-886af68b870c">

<img width="895" alt="team-5" src="https://github.com/user-attachments/assets/df9e0f2b-b4d4-412e-9219-a144e9167591">

**Version:**
2025.beta2

**Comment by reflexdd** [comment]
This doesn't work correctly yet with the pre-defined white and black Teams.

I'v added a new Team Green with pre-defined Color green.
Then add a new Game and go to team Section and select Teams
<img width="1621" alt="NT-1" src="https://github.com/user-attachments/assets/2dfb8f46-50b2-458c-9a37-2130b39200b7">

Select Pre-Defined Color

<img width="1619" alt="NT-2" src="https://github.com/user-attachments/assets/0f8ed018-e500-47b0-b4ab-0b0fb7f34f39">

and Go back to Other
I'ts not possible to enter now a different color for Black or White Team but for the Green Team it works as expected


<img width="1614" alt="NT-3" src="https://github.com/user-attachments/assets/a6afc00b-ac7a-44fa-b761-7c6db397ca5f">

**Comment by frank-weinberg** [comment]
Is this with a clean install or with importing from an older beta?
I had to amend the conversion for older json files but that conversion won't run if the file is already marked as v2025.

**Comment by reflexdd** [comment]
This was with a clean download of the dev-Version.

**Comment by frank-weinberg** [comment]
This must have imported an autosave - the pre-defined teams do not have pre-defined colors.

**Comment by reflexdd** [comment]
I downloaded the dev version, edited the Black Team by adding Black as Uniform Color. I then added a new Team Green and added Green as Uniform Color. 

No autosave to load from, using builtin defaults only

**Comment by frank-weinberg** [comment]
Ok, now I can reproduce it. And it's very weird. It does not happen, if you add e.g. "Red" as UC, only if the color matches the team.
