### ISSUE TITLE
[2025-beta2] Start New AdHoc Game defaulting to JRDA Ruleset

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#737]
**Describe the bug**
When using the _Start New Game_ and opting for an AdHoc game, CRG is defaulting to the JRDA ruleset instead of the WFDA ruleset

**To Reproduce**
1. Download fresh version of v2025-Beta2
2. Extract and start scorebard-windows.exe
3. Open CRG and then the Operator Panel
4. Start New Game

**Expected behavior**
WFTDA Ruleset should be the default

**Screenshots**
![image](https://github.com/user-attachments/assets/e1dbac12-0a28-4307-9a8b-e8b1336edd3c)

![image](https://github.com/user-attachments/assets/a4ce85e9-31eb-4db7-a00e-14b93cf9cfc3)

**Version:**
2025 Beta 2

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Windows 11 Pro 23H2 - 22631.3737
 - Browser: Chrome
 - Version: 126.0.6478.127

**Comment by reflexdd** [comment]
that seems to be a browser related thing. With safari 17.5 it shows WFTDA
Firefox 127 shows JRDA

**Comment by bullseye555** [comment]
Just checked Edge Version 126.0.2592.87 and it's JRDA too
