### ISSUE TITLE
[2025-beta2 FR] Penalty Box Timing screen choices

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#739]
**Is your feature request related to a problem? Please describe.**
While the goal of ePBT is to have a single-person Penalty Box (works very well, tested on the weekend), there are multiple possible use-case scenarios possible that it would be nice to account for
- 3 Person Penalty Box (PBM, and 1 PBT per team)
- 2 Person Penalty Box (PBM, and 1 PBT handling both teams blockers)
- 2 Person Penalty Box (2 Penalty timers, one for each team [handling Jammer and blockers for the one team])

**Describe the solution you'd like**
When entering the PBT screen, have a pop-up similar to that when entering the PLT screen that has the same _Select Team_ section (Team 1, Team 2, Both Teams), and a second section (where the current _LT, PT, PLT_ selection is in the PLT screen) for **Jammers Only, Blockers Only, All Skaters**

**Describe alternatives you've considered**
Having the one screen in the situation where there are 2 PBTs, if PBT 1 uses the _skater sat down_ option (no pre-selection) and PBT uses the same option very quickly afterwards, the wrong time may be selected. Having the options for each Penalty Timer to have their own screen would resolve this issue

Alternative considered would be to split the _Skater Sat Down_ buttons in two (so there would be 4 in total, 2 for each team) so that the "skater" could at least be assigned the correct side. This would also see the main screen split in two vertically (the same as the _PLT Both Teams_ screen) so that each team had their own side. This would also require the ability to "swap sides" in the instance that the team on the left of the screen is actually sitting on the right

**Comment by frank-weinberg** [comment]
The goal is not a single-person Penalty Box. Read https://github.com/rollerderby/scoreboard/wiki/Penalty-Box-Staffing

Having the starting of clocks separated by teams/positions is fundamentally not supported by the code. Each clock is either unassigned or assigned to a specific position. Adding in the possibility of having partial assignments would make the code even more complex for little to no gain.
