### ISSUE TITLE
[BUG] Teams with no colour have no text in ePLT/ePBM 

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#745]
Not sure if this is related to #736 or not

**Describe the bug**
Teams that don't have an associated Colour don't have any text in the button for ePLT, the heading for ePLT & ePBT, etc initially

Once a colour is added and then removed, it works as expected using the _Team Name for Display_ setting to display the Team/League/Both

**Expected behavior**
Teams that do not have a colour populated should use the _Team Name for Display_ setting to display the Team/League/Both

**Screenshots**
Initial with no colour
![image](https://github.com/user-attachments/assets/7b1003af-b295-4a17-b305-460c903c0996)
Colour added
![image](https://github.com/user-attachments/assets/fb26e788-3fd3-4468-bc49-bb92e91beccb)
Colour Removed
![image](https://github.com/user-attachments/assets/34070531-9d67-4001-97cf-cc86e70fa1f7)

**Version:**
2025-beta2 with enhancements upto commit [0c6b671]

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: WIndows 11 Pro 23H2 build 22631.3880 **and** WSL 2 running Ubuntu
 - Browser: Chrome  
 - Version 126.0.6478.127

**Additional context**
This also applies to the default Black & White teams

**Comment by Capt-Brunch** [comment]
This is also resolved if an explicit alternate name is supplied for these teams.

This issue also occurs on eSK.
