### ISSUE TITLE
Web Socket view in 3.9.4-a and 3.9.3 does not display Ads

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#75]
We have confirmed in 3.9.3 and the test build of 3.9.4a when utilising the web socket view for the scoreboard, the ad banners loaded do not display.

They do however work in the legacy display.

**Comment by brian-brazil** [comment]
This was never implemented, so this is an incomplete feature.

**Comment by official-sounding** [comment]
I did some investigation on the effort to add this to the WS view this evening, and I think it's going to involve quite a bit of work.

Essentially, all of the media elements (logos, fullscreen images, sponsor banners) do not tie into the larger eventing system.  Instead, a file is uploaded or removed, and the media folders have a commons-io filealterationlistener watching for  changes.  Then the results of the upload or removal, the details are added directly to the xml.

So, to add this we'd have to do the following:

1. rewrite media metadata storage to pass through the events system (so the JSON/WS system can see it)
2. rewrite media metadata storage to sit under Scoreboard
3. rewrite/update media management page to use that new metadata format
4. update legacy scoreboard to use new metadata format
5. add code to WS scoreboard to listen for images

This does have the benefit of getting rid of a ton of very gnarly special case code, but it is not a light undertaking by any means.

**Comment by brian-brazil** [comment]
Ugh, that's more work than I thought this would take to get going. However that's also all work that I want to get done ultimately anyway, though towards the end of the list due to difficulty.

I think you can skip 3, as the XML can still be used directly - though I'm not going to complain about starting to switch the operator controls over to WS. One thing I wonder is if we need the media information in the XML at all, as any state will be automatically picked up at restart by scanning the directories.

**Comment by frank-weinberg** [comment]
We offer an interface to upload media into a running scoreboard instance. Requiring a restart for that media to be available would be a bad UX.

**Comment by brian-brazil** [comment]
Yeah, we should maintain that functionality. And the change I made recently to list a category/directory even if it has no images currently.

**Comment by brian-brazil** [comment]
Something I noticed here at playoffs is that with the XML scoreboard, if you've more than one scoreboard then the banners aren't in sync. I think it'd be nice to have them in sync, as it'd look a little more professional.

**Comment by brian-brazil** [comment]
1-4 have been done, so only 5 which is the actual banner display needs to be done now.
