### ISSUE TITLE
Team and Player shirt colour on penalty box timing

### ISSUE THREAD

**Issue by SirWhistleton-the-3rd** [rollerderby/scoreboard#753]
**Is your feature request related to a problem? Please describe.**
Would like a little note to say what team colour and what team name or just colour to show on the player countdown

**Describe the solution you'd like**
Would like a little note to say what team colour and what team name or just colour to show on the player countdown

**Describe alternatives you've considered**

**Additional context**
Only shows player number but if PBT'ing on reduced staff could be hard to manage especially if both teams have a same number. sorry if already raised, I couldn't see it in the open items

**Comment by frank-weinberg** [comment]
If a uniform color for the team is set, it should be displayed. (Unless there is an alternate name for the PBT screen.)
Have you by any chance set an empty alternate name?

**Comment by SirWhistleton-the-3rd** [comment]
Ahh possibly, i am using it tomorrow so will double check the set up

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bullseye555** [comment]
@SirWhistleton-the-3rd - If you're using 2025-Beta's in the _release_, I don't think these have the fixes added for a couple of colour display bugs, either. You'll need to build this yourself, unless @frank-weinberg can create a new Beta build with the latest fixes in it?

**Comment by frank-weinberg** [comment]
Creating a new beta is on my list. I hope to do it this weekend.

**Comment by SirWhistleton-the-3rd** [comment]
It was user error, colour is shown, thanks for your help

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
