### ISSUE TITLE
[BUG] 2025.1_Beta3 PBM view shows no penalties when player is boxed

### ISSUE THREAD

**Issue by queekusme** [rollerderby/scoreboard#759]
**Describe the bug**
I opened the PBM screen to see what the new feature entailed, however the view was unresponsive and only displayed 'Current Penalties' in a red box

**To Reproduce**
1. Initialise a game through standard methods
2. Open the PBM view seperate to the scoreboard
3. Lineup a player to box
3. Start Jam
4. box the player
5. See error (also note javascript console)

**Expected behavior**
PBM screen to respond (I am unsure of desired effect due to how new this feature is), current penalties to be shown on the screen.

**Screenshots**
![IMG_3447](https://github.com/user-attachments/assets/6b8fdd4e-3131-4d06-ad25-505e33b8f07b)
![Screenshot 2024-08-12 at 13 59 36](https://github.com/user-attachments/assets/7416bfe5-f496-4a27-8711-9618a9a95951)

**Version:**
2025.1_Beta3

**If this issue occurred on a computer, please complete the following information:**
 - MacOS 11.4
 - Chrome 127.0.6533.100 64 bit

**Additional context**
[crg-game-2024-08-12__Black_vs._White_(Running__16_-_8).json](https://github.com/user-attachments/files/16581946/crg-game-2024-08-12__Black_vs._White_.Running__16_-_8.json)

**Comment by frank-weinberg** [comment]
The PBM screen is just the top part of the PBT screen, intended to be used on a phone strapped to the arm or hand (so the PBM has their hands free o give hand signals to skaters).

So you will only see timers show up there after you start them on the PBT screen. In your Photo, I see a skater marked as penalized but not in the box yet, so no timer on the PBM screen would be expected.

**Comment by queekusme** [comment]
Ah, I see, as I'm testing solo I can only do so much, might rope some others in to see if we can simulate more roles,

The JS errors are still slightly concerning, however feel free to close if you're happy

**Comment by frank-weinberg** [comment]
The "failed to load" errors are ok for this screen - it will always try to load the index.js and index.css files but this screen doesn't have either.
I'm not sure where exactly the $.widget one is coming from but I get it as well in Chrome and it doesn't appear to affect functionality. My guess is that it is also an artefact of the load errors.

And I get the trouble with trying to do everything alone. That is a struggle at times during development as well.
