### ISSUE TITLE
[Investigation of Bug? 2025-beta3] Corrupted data

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#761]
@frank-weinberg - copying this verbatim from Facebook. Devon has raised an issue where on restarting CRG the day after a game, they've identified some corrupted data. Can you have a look into this and see what's going on? I had a brief look and there wasn't anything obvious that stood out. I haven't tried importing, based on Devon's comments.

Each quote block is a separate comment that I've just copy/pasted from the FB thread

>Nick hoping you may be able to help. We ran a double-header yesterday using this latest beta. Came across a few visual glitches that we were able to get around. Booted up the scoreboard laptop today to retrieve the statsbook files and the java console started throwing errors left and right and it appears to have corrupted the game data. Trying to figure out if there is any way to salvage the games data. I have placed log files and json files here: https://drive.google.com/drive/folders/17emBw0S1DinLZ1iddLvvxZzvPe4VWNKQ?usp=sharing
I have been troubleshooting already and did find if I load the autosave files from when we first booted up the scoreboard laptop yesterday it loads fine and shows both games in a prepared state. If I then load the autosave files from this morning which are much bigger in size it throws the errors and the data does not look correct.

(At this point I requested JSON from the post-game autosave, and if possible, the full zip, which were provided)
>FYI the JSON autosave files in folder 2024-08-17-16-30-38 are the last known working JSON files which will load properly. The much larger ones in the 2024-08-18-10-19-57 are from when I first booted up the scoreboard this morning looking to download the statsbook and noticed everything got corrupted.

> I did take a look at the JSON file from when I first started the laptop up this morning and did find the lines where it shows that both bouts finished and the final score, so I believe the actual data is there and is correct, now just to see if we can get the scoreboard software to read it properly so I can get statsbooks and the paperwork

>Ok so was doing some more troubleshooting today. Spun up a fresh copy of 2025-beta3 on another computer and I was able to load the game JSON file from the first game no issues and get a correct statsbook, so at least we have data for that game. When looking at the second game it appears the scoreboard software for some reason broke the game up into 2 separate JSON files. If I import the first JSON it loads a PREPARED game status for the two teams. If I then load the second JSON file it switches the game to a RUNNING state and adds some data, but not all. About the only thing I can tell that it properly adds is the amount of penalties but scores it keeps at 0-0. Idk if there is another JSON I may be able to load from the autosaves possibly that would bring in the correct data for the second game or if there is another place I should look for another file, but wanted to give me troubleshooting updates in case it helps the devs at all.

>So on a whim I decided to load the autosave JSON files from the morning when I opened the scoreboard and first noticed the corruption. I loaded each one individually and was able to get the game to a FINISHED state. It gave one team the correct score, but the second team it is saying 0 points, but it does show how many points they earned each period so that should be a simple adjustment on the paperwork to fix. So looks like I will have valid-ish data for the second bout. Still doesn't explain the java errors and what sequence of events caused this to happen, but hopefully the devs can figure out what caused it to go haywire.

**Comment by frank-weinberg** [comment]
Got the same one while testing unrelated changes in my local install. Will include a fix with those changes (since I need it to complete the test).
