### ISSUE TITLE
[BUG] SBO can field ineligible skater

### ISSUE THREAD

**Issue by blauwblaatje** [rollerderby/scoreboard#786]
**Describe the bug**
Jammer is injured and need to sit out 3 jams. 
Jammer is lined up within these 3 jams. 
The SBO is able to select that jammer. 

**To Reproduce**
1. On the ePLT screen mark a skater injured
2. Start a new jam
3. On the SBO screen, select the injured skater
4. The injured skater is allowed to skate 

**Expected behavior**
The ePLT is not able to select this skater, but the SBO is, which might make sense... 
Maybe give a colour to an injured skater, so there is an extra indicator that the skater is not allowed to skate. 
Maybe highlight the skater at ePLT as well when selected, so ePLT can notify the skater. 

**Version:**
2023.7 and 2025.0

**Additional context**
We had this issue last weekend and were surprised CRG wasn't complaining. We then realised it was because it was set by the SBO and the jammer lined up in the last moment. We can imagine that it might freak out an SBO even more when they cannot select a skater, like with ePLT, but it might be helpful if the number is coloured so you have a visual indicator and can quickly call a OTO.

**Comment by reflexdd** [comment]
Do we have the possibility to mark someone as the reason for injury call off beside that it was a call of for injury?
Marking the Jam as INJ is not related to a Skater at all at the moment or am I wrong?

**Comment by blauwblaatje** [comment]
@reflexdd in the ePLT screen you can by clicking on "Sit out next 3".  But then as an SBO you can still select them. It's also not always an INJ call off that makes someone sit out the next 3... 
![image](https://github.com/user-attachments/assets/3a61a827-b66f-44a7-a22e-cb377b56e4ed)

**Comment by reflexdd** [comment]
Ah right.. I missed that. It's unmarked but also still possible to select for Lineup. Is this intended?

**Comment by blauwblaatje** [comment]
for ePLT that skater is then not clickable.  
![image](https://github.com/user-attachments/assets/81de72ef-d314-4756-9c9c-1ad2c37a2ed9)

but for sbo it is. 
![image](https://github.com/user-attachments/assets/575d8372-ee7e-4cf8-820b-e9f8437695cf)

**Comment by reflexdd** [comment]
ok, maybe with  a tablet. I tried it with the mouse and it was still clickable

**Comment by blauwblaatje** [comment]
ohh, you're right..  I saw the 11 being white and that was for me enough of an indicator.  It makes sense that you can click the skater, as you'd need to fill in what's happening, so an indicator that someone should not be allowed might be a good thing.

**Comment by frank-weinberg** [comment]
The skater can be fielded because if they are on the track and the Jam is run (officiating errors happen), they have to be put in the paperwork. So not a bug.

An indication for SBO as well sounds reasonable, so I'll leave this open as a feature request.

**Comment by blauwblaatje** [comment]
I agree it should be on the paperwork, sorry for calling it a bug :)   
And I think indicating it on various screen when someone does select that skater (I guess that could also be ePBT and eSK now?) would make the most sense to me, so multiple people will panic and ask for an OTO :)

**Comment by frank-weinberg** [comment]
WDYT about this way of displaying ineligible skaters on the SBO screen? (The same style will also be used for fouled out/expelled skaters as that is encoded in the same way.)
![grafik](https://github.com/user-attachments/assets/dc48cc36-93ff-4172-9988-8c8125ae105f)

(The current data format causes ineligibility to be hidden when a skater is fielded. So indicating that a skater is fielded but shouldn't be would require a breaking change to the data format. I'm a bit reluctant to make such a change after the major version has been released.)

**Comment by blauwblaatje** [comment]
that looks reasonable. At least it's an indicator to the SBO
