### ISSUE TITLE
[BUG] adding a Letter as Number is allowed 

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#788]
**Describe the bug**
You can add a Letter as Number 

**To Reproduce**
1. Create a new game
2. put in a letter as Number

**Expected behavior**
Give a warning the only digits are allowed

**Screenshots**
<img width="771" alt="Bildschirmfoto 2024-11-12 um 16 57 50" src="https://github.com/user-attachments/assets/450a1401-b215-46fd-80b7-913c2cacadab">

<img width="777" alt="Bildschirmfoto 2024-11-12 um 16 57 42" src="https://github.com/user-attachments/assets/4553489b-41e4-4aa9-a1c5-35dc4d456e1e">

**Version:**
The version of the scoreboard you were running 2025.0

**Comment by frank-weinberg** [comment]
Works as expected. Even WFTDA rules do not restrict skater "numbers" to sequences of digits (only the Sanctioning Policy does). And CRG supports rule sets beyond that.
