### ISSUE TITLE
[BUG] First scoring trip shows . on SBO SK paperwork instead of points

### ISSUE THREAD

**Issue by Capt-Brunch** [rollerderby/scoreboard#793]
When assigning points to a jammer's first scoring trip, the "." trip indicator remains on the SK paperwork displayed on the SBO screen, rather than the points submitted. If the trip is edited, the modal window does show the correct points, but this is the only place it is displayed. 

The points for trips 3 and beyond function properly, I have only been able to reproduce this for Trip 2. 

**To Reproduce**
1. Start a new game, and start the first jam
2. Press Lead on one of the jammers and wait several seconds
3. Add points to the jammer, either with +1 or the quick-score buttons
4. Notice that the "." in Trip 2 remains, despite the points otherwise displaying correctly. 
5. This can be repeated for the other jammer as well, completing their initial trip and assigning points.

**Expected behavior**
Trip 2 should reflect the points assigned on that trip.

**Screenshots**
![chrome_AKv3Ety4Su](https://github.com/user-attachments/assets/d2638933-c303-4507-837e-c7a7f4d543b9)
<img width="1280" alt="chrome_driYfx1fIX" src="https://github.com/user-attachments/assets/a89c07eb-24a4-4d8d-8b87-08f858a040b0">

**Version:**
2025.0

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Windows 11, however CRG is running in an Alpine 3.20 container
 - Browser Chrome 
 - Version 130.0.6723.117

**Additional context**
This visual issue is resolved if the page is refreshed, leading me to believe that this is simply a DOM update getting blocked from updating the first trip.

**Comment by frank-weinberg** [comment]
Narf. I noticed this shortly before release and thought I had fixed it. Looks like I was mistaken and we need a 2025.1 really soon...
