### ISSUE TITLE
[BUG] empty Sponsor-Banner has a white edge / Hide sponsors not working

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#795]
**Describe the bug**
The Main-Scoreboardview has a black rectangle with grey border visible. This Container is moving and behaving like a banner.

**To Reproduce**
Open a fresh relase version and open the Mainscoreboard view

**Expected behavior**
Down show a container with an border or hide the container when no banners are loaded

**Screenshots**
Firefox
<img width="2056" alt="Bildschirmfoto 2024-11-15 um 11 56 09" src="https://github.com/user-attachments/assets/a11eecfd-b650-4421-b967-d9b6d7e11d15">
<img width="2056" alt="Bildschirmfoto 2024-11-15 um 11 56 20" src="https://github.com/user-attachments/assets/724b8e0f-b4a5-44ae-bf8e-f0d7232cbb2c">

Chrome:
<img width="1876" alt="Bildschirmfoto 2024-11-15 um 15 50 48" src="https://github.com/user-attachments/assets/bef7eed8-aa75-4525-bab9-7458f2760bab">

**Version:**
 2025.1

**If this issue occurred on a computer, please complete the following information:**
 - OS and version:  Mac 15.1
 - Browser [firefox 132.0.2, safari 18.0.1, Chrome 130.0.6723.117]

**Comment by reflexdd** [comment]
Workaround meanwhile would be inserting an empty transparent Sponsor banner

**Comment by bullseye555** [comment]
Same on Windows 11 & Chrome

**Comment by frank-weinberg** [comment]
I don't see these boxes when the "Hide Sponsor Banners" option is active. So that's presumably the go-to workaround.

**Comment by reflexdd** [comment]
The Fix with the box works, but the "Hide Sponsor Banners" still has no function. Tested under Mac and Windows 10

**Comment by reflexdd** [comment]
ahh... I forgot that this was a Preview which had to be applied
