### ISSUE TITLE
Improvement overlay before Gamestart

### ISSUE THREAD

**Issue by reflexdd** [rollerderby/scoreboard#796]
**Is your feature request related to a problem? Please describe.**
When starting a new game the overlay is set to not showing the Score at the moment.
Enabling  the Score leads to Score with an empty lineup.

**Describe the solution you'd like**
Having the Score and Teams visible & the Lineup hidden until the Start Jam or Lineup Button is clicked

Also having the Score activated as default would be nice as the basic information for a Stream should be visible from the beginning without the need to activate something over the admin view

<img width="1968" alt="Bildschirmfoto 2024-11-15 um 15 38 29" src="https://github.com/user-attachments/assets/792d1f2f-a70b-4377-a9cc-1aaf22ec2cb2">

**Comment by reflexdd** [comment]
Does the fix also hide the empty grey Lineup Information before the start of the first jam of a period?

**Comment by frank-weinberg** [comment]
No. Showing them between jams was an intentional change and them being displayed before the game is tied to that. (I did write a comment stating that yesterday but it somehow seems to have been lost.)
