### ISSUE TITLE
Update Welcome Page

### ISSUE THREAD

**Issue by jaredquinn** [rollerderby/scoreboard#8]
Updated Welcome Page & Overlay Dialog

![image](https://cloud.githubusercontent.com/assets/151566/25783271/c7a53676-339c-11e7-8e05-98edbca31e48.png)

**Comment by rogerharkavy** [comment]
The Welcome page has some old information. (SourceForge links, etc.)

**Comment by official-sounding** [comment]
I think this ticket is done? looks like it was fixed in PR #37

**Comment by rogerharkavy** [comment]
Looks like it.

**Comment by brian-brazil** [comment]
Yip.
