### ISSUE TITLE
ePBT/ePBM view confusing and crowded

### ISSUE THREAD

**Issue by blauwblaatje** [rollerderby/scoreboard#808]
**Is your feature request related to a problem? Please describe.**
Relaying from FB:
"Don't know if it is planned yet but maybe it would be great to have splitted views for the penalty box, one for each team. We tested it out in our last game and found there were some confusions from ePBTs in figuring out which penalty was started by who (in the cases they didn't catch the players numbers early enough)."

I have a similar sentiment about it. The screen feels like "too much".  (Note: I'm not an experienced PBT/PBM) 

1) I'm not sure if I need to see Team White when I'm PBT'ing Team White, so maybe the option to just show Team White, like with ePLT, might be good. 
2) When you have a lot of penalties in a jam, the bottom bar will scroll out of screen. Maybe make that sticky at the bottom or put at at the top, so you'll always see the buttons and the active sitters?
3) I get that the PBM view should have both sides, but here I'm missing the Jammer buttons. 
4) I agree with the writer on FB that a split might be useful when seeing both teams.

**Describe the solution you'd like**
1) Option to only see one team, like with ePLT
2) Different placement of bottom bar
3) Jammer buttons for ePBM
4) Split view of penalties when seeing both teams

**Comment by frank-weinberg** [comment]
Your bullets 1,3, and 4 are based on a misconception as to how the screens are supposed to be used. I have rewritten https://github.com/rollerderby/scoreboard/wiki/Penalty-Box-Staffing in order to hopefully make this clearer.

A change addressing bullet 2 is made and will be in 2025.4.

**Comment by blauwblaatje** [comment]
Thanks, that write up makes sense and I'll try it next month.
