### ISSUE TITLE
[BUG] JRDA's Jam continuation after an injury doesn't appear

### ISSUE THREAD

**Issue by LexPendragon** [rollerderby/scoreboard#815]
**Describe the bug**
When starting a Jam, one side gets lead, then the INJ button is hit, the continuation upcoming button does not appear.  I tried the same thing in 2023.5 and it worked as expected.

**To Reproduce**
1. Start a game
2. Start a Jam
3. Give one side Lead
4. Click INJ

**Expected behavior**
Next to Start Jam, a Continuation Upcoming button should appear.

**Screenshots**
In 2023.5, this button shows up:
![image](https://github.com/user-attachments/assets/658926d4-9b51-48a1-ab1d-b2d4fd95594c)

In 2025.3 (and in 2025.0) it does not show up:
![image](https://github.com/user-attachments/assets/4351bfe5-9e0b-4e17-ae2b-237061401e06)

**Version:**
2025.3 (first noticed in 2025.0)

**If this issue occurred on a computer, please complete the following information:**
 - Windows 11 Pro (22H2) OS build: 22621.4317
 - Chrome Version 131.0.6778.140 (Official Build) (64-bit)
 - Version 131.0.6778.140 (Official Build) (64-bit)

**If this issue occurred on a smartphone, tablet, or other device, please complete the following information:**
Computer

**Additional context**
I am available to test/troubleshoot any other steps you'd like.

**Comment by LexPendragon** [comment]
I installed 2025.4, and the behavior was the same.

**Comment by frank-weinberg** [comment]
Just double checked and it works for me:
![Bildschirmfoto_20250106_183617](https://github.com/user-attachments/assets/cbff95d4-5380-4390-8b93-67bce783f9da)

Did you maybe not reload your browser after updating?

**Comment by LexPendragon** [comment]
![image](https://github.com/user-attachments/assets/ef392f2b-d633-44f8-ac35-db37e5fb2c53)

I exited the browser, reloaded, and cleared the cache/site-data.

I even verified the new version showed up.
![image](https://github.com/user-attachments/assets/2ed6a85a-2bc3-4d3f-b135-6920953ced9f)

**Comment by frank-weinberg** [comment]
That's weird. Have you verified that you have the corresponding rule activated?
![Bildschirmfoto_20250106_185328](https://github.com/user-attachments/assets/e08e76ce-1939-4387-82c4-3772090eaeaf)

**Comment by LexPendragon** [comment]
I do, yes:
![image](https://github.com/user-attachments/assets/65f36e3e-78ff-42a3-a5a1-6c9ce0b10fee)

**Comment by frank-weinberg** [comment]
Then the only explanation I have is that your browser for some reason did not load the new Javascript and is somehow still using the old one. (Note that the version displayed on the menu screen comes from the backend and does not indicate which version of the frontend code is running in the browser.) I double checked that there is nothing beyond this rule and the Inj flag that controls display of the button and I can see in the screenshots that they are as they should be.

If Ctrl+F5 does not resolve the problem, then I am at a loss.

**Comment by LexPendragon** [comment]
Thank you!

![image](https://github.com/user-attachments/assets/e9e8c1a6-3e0e-467d-a4ab-96a1ccbddc8c)


When you mentioned JavaScript, I went back in, blew away any trace of what was there so there wasn't a chance of a cached Java or anything, and reloading after all that make it find the new stuff.  I'm good to go.

Thank you especially for putting up with the one edge case and helping me to get it working.
