### ISSUE TITLE
Have releases on github

### ISSUE THREAD

**Issue by brian-brazil** [rollerderby/scoreboard#9]
Currently it appears the primary way to find the most recent release is to find the Facebook group, and from there download from Google drive.

It'd be great it you could attach the zip to the tagged releases within Github, such as at https://github.com/rollerderby/scoreboard/releases/tag/v3.9.0

The README should also point there for those not used to using github.

**Comment by jaredquinn** [comment]
Updated! Thanks for the suggestion!

https://github.com/rollerderby/scoreboard/releases

**Comment by brian-brazil** [comment]
Thanks!
